function trimStr(a){for(var c=-1,b=a.length;33>a.charCodeAt(--b););for(;33>a.charCodeAt(++c););return a.slice(c,b+1)}function BuildComboboxStore(a,c){Ext.define("comboboxModel",{extend:"Ext.data.Model",fields:[{name:"label",type:"string"},{name:"value",type:"string"}]});return new Ext.data.Store({id:"ComboboxStore",model:"comboboxModel",autoLoad:!1,proxy:{type:"ajax",url:a,actionMethods:{read:"POST"},reader:{type:"json",root:"values"},extraParams:c}})}
Ext.define("DCI.LKB.Customer.OpenWinTrigger",{extend:"Ext.form.field.Trigger",alias:"DCI.OpenWinTrigger",multiSelect:!1,displayColumns:[],returnColumn:"",openWinDataUrl:"",openWinParams:{},depComps:[],ouid:"",langobj:null,onTriggerClick:function(){if(""==this.id)alert("元件設定錯誤");else{for(var a=null,c=null,b=0;b<this.depComps.length;b++)c=-1==this.depComps[b].indexOf("_")?this.depComps[b]:this.depComps[b].substring(0,this.depComps[b].indexOf("_")),this.openWinParams.hasOwnProperty(c)&&(a=Ext.getCmp(this.depComps[b]),
null!=a&&(this.openWinParams[c]=a.getValue()));this.openWinParams.uid=this.ouid;createOpenWin(this,this.multiSelect,this.displayColumns,this.returnColumn,this.openWinDataUrl,this.openWinParams,this.langobj).show()}}});
function createOpenWin(a,c,b,d,e,f,g){c=null;var h=[];c=[];h.push({name:"selected",type:"bool"});c.push({xtype:"checkcolumn",text:"",dataIndex:"selected"});for(var k=0;k<b.length;k++)h.push({name:b[k][0],type:"string"}),c.push({text:b[k][1],dataIndex:b[k][0]});b=Ext.define("WinModel",{extend:"Ext.data.Model",fields:h});var l=new Ext.data.Store({id:"WinStore",model:b,autoLoad:!1,proxy:{type:"ajax",url:e,actionMethods:{read:"POST"},reader:{type:"json",root:"items"},extraParams:f}});e=Ext.create("Ext.grid.Panel",
{renderer:"component",stripeRows:!0,store:l,autoScroll:!0,columns:c});l.load();return c=Ext.create("Ext.window.Window",{title:g.open_win,width:500,height:300,minWidth:300,minHeight:200,layout:"fit",plain:!0,modal:!0,items:e,buttons:[{text:g.ok,handler:function(){var b="";if(0!=l.getCount())for(var c=null,e=null,e=d.split(";"),f=0;f<l.getCount();f++)if(c=l.getAt(f),c.get("selected")){if(""==b)for(var h=0;h<e.length;h++)b=0==h?trimStr(c.get(e[h])):1==h?b+("("+trimStr(c.get(e[h]))):b+(","+trimStr(c.get(e[h])));
else{b+=";";for(h=0;h<e.length;h++)b=0==h?b+trimStr(c.get(e[h])):1==h?b+("("+trimStr(c.get(e[h]))):b+(","+trimStr(c.get(e[h])))}1<e.length&&(b+=")")}a.setValue(b);this.up(".window").close()}},{text:g.cancel,handler:function(){this.up(".window").close()}}]})}var PageMode=buildMultiLangObjct(["View","Edit","Add"],["View","Edit","Add"]);Ext.define("DCI.Customer.Img",{extend:"Ext.Img",alias:"DCI.Customer.Img",width:50,height:50,loadDefault:function(){this.setSrc("")},setReadOnly:function(a){}});
Ext.define("DCI.Customer.FileField",{extend:"Ext.form.field.File",alias:"DCI.Customer.FileField",buttonText:"",buttonConfig:{iconCls:"upload-icon"},emptyText:"",defaultvalue:"",ispk:!1,canEdit:!0,loadDefault:function(){},setReadOnly:function(a){this.readOnly=a;this.setDisabled(a)}});
Ext.define("DCI.Customer.TextField",{extend:"Ext.form.field.Text",alias:"DCI.Customer.TextField",msgTarget:"side",oriAllowBlank:!1,defaultvalue:"",ispk:!1,canEdit:!0,cusStyle:null,loadDefault:function(){this.setValue(this.defaultvalue)},setReadOnly:function(a){a?(this.allowBlank=!0,this.setFieldStyle({backgroundColor:"#ddd",backgroundImage:"none"})):(this.allowBlank=this.oriAllowBlank,null!=this.cusStyle&&""!=this.cusStyle?this.setFieldStyle(this.cusStyle):this.setFieldStyle({backgroundColor:"#FFFFFF"}));
this.callParent(arguments)},initComponent:function(){this.oriAllowBlank=this.allowBlank;null!=this.style&&(this.cusStyle=this.style);this.callParent(arguments)}});
Ext.define("DCI.Customer.ComboBox",{extend:"Ext.form.field.ComboBox",alias:"DCI.Customer.ComboBox",displayField:"label",valueField:"value",typeAhead:!0,editable:!1,queryMode:"local",matchFieldWidth:!1,multiSelect:!1,forceSelection:!0,store:{fields:["label","value"],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}},defaultvalue:"",ispk:!1,canEdit:!0,cusStyle:null,loadDefault:function(){null!=this.store&&0<this.store.getCount()&&(null==this.defaultvalue||""==this.defaultvalue?this.setValue(this.store.getAt(0).get("value")):
this.setValue(this.defaultvalue))},setReadOnly:function(a){a?this.setFieldStyle({backgroundColor:"#ddd",backgroundImage:"none"}):null!=this.cusStyle&&""!=this.cusStyle?this.setFieldStyle(this.cusStyle):this.setFieldStyle({backgroundColor:"#FFFFFF"});this.callParent(arguments)},initComponent:function(){null!=this.style&&(this.cusStyle=this.style);this.callParent(arguments)}});
Ext.define("DCI.Customer.HeadFormPanel",{extend:"Ext.form.Panel",alias:"DCI.Customer.HeadFormPanel",region:"center",layout:"absolute",frame:!0,width:1E3,bodyPadding:5,waitMsgTarget:!0,method:"POST",languageObj:null,searchWin:null,searchStore:null,currmode:PageMode.View,currrow:0,dataloaded:!1,bodypanel:null,toolpanel:null,defaults:{xtype:"textfield"},fieldDefaults:{labelAlign:"right",labelWidth:80,msgTarget:"side"},loadDefault:function(){if(null!=this.items&&0<this.items.length)for(var a=0;a<this.items.length;a++)-1!=
Ext.getClassName(this.items.get(a)).indexOf("DCI")&&this.items.get(a).loadDefault();null!=this.bodypanel&&this.bodypanel.clearGrid();this.resetDataLoaded()},showQueryWindow:function(){},initQueryWindow:function(){if(this.getCurrMode()==PageMode.Add){this.loadDefault();for(var a=0;a<this.items.length;a++)try{"function"==typeof this.items.get(a).clearInvalid&&this.items.get(a).clearInvalid()}catch(c){window.console&&console.log(c.message)}}},getCurrMode:function(){return this.currmode},setCurrMode:function(a){this.currmode=
a;this.currmode==PageMode.View?(setCompsReadOnly(this.items,!0),null!=this.bodypanel&&this.bodypanel.changeMode(PageMode.Edit)):this.currmode==PageMode.Add?setCompsReadOnly(this.items,!1):this.currmode==PageMode.Edit&&setPageEdit(this.items)},resetDataLoaded:function(){this.setDataLoaded(!1)},setDataLoaded:function(a){this.dataloaded=a;null!=this.bodypanel&&this.bodypanel.dataloaded(a);null!=this.toolpanel&&this.toolpanel.setDataLoadMode(a)},cusValid:function(a){a()},initComponent:function(){this.callParent(arguments);
setCompsReadOnly(this.items,!0)}});
Ext.define("DCI.Customer.QueryWindow",{extend:"Ext.window.Window",alias:"DCI.Customer.QueryWindow",layout:"border",title:"Query",height:200,width:400,minWidth:300,minHeight:200,modal:!0,plain:!0,headform:null,items:[{xtype:"panel",region:"north",height:35,layout:"absolute",items:[{xtype:"combobox",fieldLabel:"",displayField:"label",valueField:"value",typeAhead:!0,editable:!1,queryMode:"local",labelWidth:1,matchFieldWidth:!1,multiSelect:!1,forceSelection:!0,store:Ext.create("Ext.data.Store",{fields:[{name:"label",
type:"string"},{name:"value",type:"string"}],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}}),x:5,y:5},{xtype:"textfield",name:"qvalue",fieldLabel:"",labelWidth:1,width:160,x:155,y:5},{xtype:"button",cls:"search-toolbar",width:30,height:30,x:315,y:1,handler:function(){this.up("panel").up("window").clickFunc()}}]},{xtype:"grid",region:"center",renderer:"component",stripeRows:!0,autoScroll:!0,loadMask:!0,enableTextSelection:!0,viewConfig:{forceFit:!1,autoLoad:!1},columns:[],store:null,dockedItems:[{xtype:"pagingtoolbar",
store:null,dock:"bottom",displayInfo:!0,listeners:{beforechange:function(a,c,b){this.store.getProxy().extraParams.hasOwnProperty("page")&&(null==c||0==c?this.store.getProxy().extraParams.page=1:this.store.getProxy().extraParams.page=c);this.store.load()}}}],listeners:{celldblclick:function(a,c,b,d,e,f,g,h){c=this.up("window");a=a.getStore();null!=c.headform&&(c.headform.currrow=1==a.currentPage?f:(a.currentPage-1)*a.pageSize+f);this.up("window").loadHeadData(d)}}}],setInitObjects:function(a,c,b){if(0<
a.length){var d=this.items.get(0).items.get(0);d.getStore().loadData(a[0].get("cols"));0<d.getStore().getCount()&&("undefined"!=typeof d&&null!=d)&&d.setValue(d.getStore().getAt(0).get("value"))}this.items.get(1).reconfigure(c,b);this.items.get(1).child("pagingtoolbar").bindStore(c);c.load()},loadHeadData:function(a){this.headform.loadRecord(a);this.headform.setDataLoaded(!0);this.close()},clickFunc:function(){var a=this.items.get(1).getStore(),c=this.items.get(0).items.get(0).getValue(),b=this.items.get(0).items.get(1).getValue();
a.getProxy().extraParams.hasOwnProperty("filter")&&(a.getProxy().extraParams.filter=" and "+c+" like '%"+b+"%' ");a.getProxy().extraParams.hasOwnProperty("page")&&(a.getProxy().extraParams.page=1);a.currentPage=1;a.load()}});
Ext.define("DCI.Customer.SubTabPanel",{extend:"Ext.tab.Panel",alias:"DCI.Customer.SubTabPanel",minWidth:900,minHeight:400,widthChangeControls:[],bodyStyle:{background:"#eaf1fb"},resize:function(a,c){if(a>this.width){this.width=a;for(var b=0;b<this.widthChangeControls.length;b++)null!=this.widthChangeControls[b]&&this.widthChangeControls[b].setWidth(a-20)}else{var d=this.minWidth;a>this.minWidth&&(d=a);for(b=0;b<this.widthChangeControls.length;b++)null!=this.widthChangeControls[b]&&this.widthChangeControls[b].setWidth(d-
20);this.width=a}c<this.minHeight&&(c=this.minHeight);this.setHeight(c)},beforeClose:function(){},focusPage:function(){null!=Ext.get(this.renderTo)&&this.resize(Ext.get(this.renderTo).getWidth(),Ext.get(this.renderTo).getHeight())},leavePage:function(){},globalTimerEvent:function(a,c){},globalTimerStop:function(){}});
Ext.define("DCI.Customer.SubPanel",{extend:"Ext.Panel",alias:"DCI.Customer.SubPanel",minWidth:900,minHeight:400,parentComp:null,bodyStyle:{background:"#eaf1fb"},widthChangeControls:[],setParent:function(a){this.parentComp=a},resize:function(a,c){if(a>this.width){this.width=a;for(var b=0;b<this.widthChangeControls.length;b++)null!=this.widthChangeControls[b]&&this.widthChangeControls[b].setWidth(a-20)}else{var d=this.minWidth;a>this.minWidth&&(d=a);for(b=0;b<this.widthChangeControls.length;b++)null!=
this.widthChangeControls[b]&&this.widthChangeControls[b].setWidth(d-20);this.width=a}c<this.minHeight&&(c=this.minHeight);this.setHeight(c)},beforeClose:function(){},focusPage:function(){null!=Ext.get(this.renderTo)&&this.resize(Ext.get(this.renderTo).getWidth(),Ext.get(this.renderTo).getHeight())},leavePage:function(){},globalTimerEvent:function(a,c){},globalTimerStop:function(){}});
Ext.define("DCI.Customer.ToolBarPanel",{extend:"Ext.Panel",alias:"DCI.Customer.ToolBarPanel",region:"north",width:300,height:35,bodyStyle:{background:"#99bce8"},x:0,y:0,border:0,layout:"absolute",bindform:null,postvalue:"",uid:"",canEdit:!0,cusMsg:[],keepAdd:!0,items:[{xtype:"button",cls:"search-toolbar",x:5,y:3,width:30,height:30,handler:function(){var a=this,c=a.up("panel").bindform,b=!1;null!=c&&(c.setLoading(!1),c.bodypanel&&(null!=c.bodypanel&&c.bodypanel.getCurrMode()==PageMode.Edit)&&(b=!0),
c.getCurrMode()==PageMode.View&&!b?c.showQueryWindow():Ext.MessageBox.confirm(c.languageObj.confirm_title,c.languageObj.data_lose_warning,function(b){"yes"==b&&(c.showQueryWindow(),c.setCurrMode(PageMode.View),a.up("panel").ModeChange(PageMode.View))}))}},{xtype:"button",cls:"add-toolbar",x:40,y:3,width:30,height:30,handler:function(){var a=this.up("panel").bindform;null!=a&&a.getCurrMode()==PageMode.View&&(a.setLoading(!1),this.up("panel").canEdit?(a.loadDefault(),a.setCurrMode(PageMode.Add),this.up("panel").ModeChange(PageMode.Add)):
Ext.MessageBox.alert(a.languageObj.errmsg,a.languageObj.no_edit_auth))}},{xtype:"button",cls:"edit-toolbar",x:75,y:3,width:30,height:30,handler:function(){var a=this.up("panel").bindform;if(null!=a&&a.getCurrMode()==PageMode.View&&a.dataloaded)if(a.setLoading(!1),this.up("panel").canEdit){var c=this.up("panel").exceptionEditAuth();null!=c&&2==c.length&&("1"==c[0]?(a.setCurrMode(PageMode.Edit),this.up("panel").ModeChange(PageMode.Edit)):Ext.MessageBox.alert(a.languageObj.errmsg,c[1]))}else Ext.MessageBox.alert(a.languageObj.errmsg,
a.languageObj.no_edit_auth)}},{xtype:"button",cls:"delete-toolbar",x:110,y:3,width:30,height:30,handler:function(){var a=this.up("panel").bindform,c=this.up("panel").postvalue,b=this.up("panel").uid,d=this.up("panel").cusMsg;if(null!=a&&a.getCurrMode()==PageMode.Edit)if(a.setLoading(!1),this.up("panel").canEdit){var e=this.up("panel"),f=e.exceptionDeleteAuth();null!=f&&2==f.length&&("1"==f[0]?Ext.MessageBox.confirm(a.languageObj.delete_confirm_title,a.languageObj.delete_confirm_msg,function(f){"yes"==
f&&Ext.Ajax.request({method:"POST",url:a.url,params:{action:"del",datas:Ext.encode(a.getForm().getValues()),DCITag:c,uid:b},success:function(b){b=Ext.JSON.decode(b.responseText);if(b.success){a.loadDefault();a.setCurrMode(PageMode.View);e.ModeChange(PageMode.View);for(b=0;b<a.items.length;b++)try{"function"==typeof a.items.get(b).clearInvalid&&a.items.get(b).clearInvalid()}catch(c){window.console&&console.log(c.message)}null!=d&&3<=d.length?Ext.Msg.alert(a.languageObj.delete_result_title,d[2]):Ext.Msg.alert(a.languageObj.delete_result_title,
a.languageObj.delete_success)}else Ext.Msg.alert(a.languageObj.save_result_title,a.languageObj.delete_fail+" :</br>"+b.errorMessage)},failure:function(b,c){Ext.MessageBox.alert(a.languageObj.errmsg,a.languageObj.system_error)}})}):Ext.MessageBox.alert(a.languageObj.errmsg,f[1]))}else alerExt.MessageBox.alert(a.languageObj.errmsg,a.languageObj.no_edit_auth)}},{xtype:"button",cls:"save-toolbar",x:145,y:3,width:30,height:30,handler:function(){var a=this.up("panel").bindform,c=this.up("panel"),b=this.up("panel").cusMsg,
d=this.up("panel").keepAdd;if(null!=a&&(a.getCurrMode()==PageMode.Add||a.getCurrMode()==PageMode.Edit))a.setLoading(!1),this.up("panel").canEdit?a.isValid()&&a.cusValid(function(){a.getForm().submit({waitMsg:a.languageObj.save_msg,params:{action:"save",datas:Ext.encode(a.getForm().getValues()),DCITag:c.postvalue,uid:c.uid,mode:a.getCurrMode()},failure:function(b,c){Ext.Msg.alert(a.languageObj.save_result_title,a.languageObj.save_fail+" :</br>"+c.result.errorMessage)},success:function(e,f){var g=a.getCurrMode();
if(g==PageMode.Add){if(d)a.loadDefault(),a.setCurrMode(PageMode.View),c.ModeChange(PageMode.View);else{a.setCurrMode(PageMode.View);c.ModeChange(PageMode.View);var h=f.result.resultData.items[0];null==h?a.loadDefault():(a.getForm().setValues(h),a.setDataLoaded(!0))}null!=a.bodypanel&&a.bodypanel.setNewCondi()}else a.setCurrMode(PageMode.View),c.ModeChange(PageMode.View);for(var k=0;k<a.items.length;k++)try{"function"==typeof a.items.get(k).clearInvalid&&a.items.get(k).clearInvalid()}catch(l){window.console&&
console.log(l.message)}null!=h&&c.afterSaveFunc(h);g==PageMode.Add&&null!=b&&1<=b.length?Ext.Msg.alert(a.languageObj.save_result_title,b[0]):g==PageMode.Edit&&null!=b&&2<=b.length?Ext.Msg.alert(a.languageObj.save_result_title,b[1]):Ext.Msg.alert(a.languageObj.save_result_title,a.languageObj.save_success)}})}):Ext.MessageBox.alert(a.languageObj.errmsg,a.languageObj.no_edit_auth)}},{xtype:"button",cls:"exit-toolbar",x:180,y:3,width:30,height:30,handler:function(){var a=this,c=a.up("panel").bindform;
null!=c&&(c.setLoading(!1),(c.getCurrMode()==PageMode.Add||c.getCurrMode()==PageMode.Edit)&&Ext.MessageBox.confirm(c.languageObj.confirm_title,c.languageObj.data_lose_warning,function(b){if("yes"==b){c.getCurrMode()==PageMode.Add&&c.loadDefault();for(b=0;b<c.items.length;b++)try{"function"==typeof c.items.get(b).clearInvalid&&c.items.get(b).clearInvalid()}catch(d){window.console&&console.log(d.message)}c.setCurrMode(PageMode.View);a.up("panel").ModeChange(PageMode.View)}}))}},{xtype:"label",text:"",
height:30,style:"font: bold 20px courier",x:215,y:5}],dockedItems:[{xtype:"toolbar",dock:"right",width:122,style:{background:"#99bce8"},layout:"absolute",items:[{xtype:"button",cls:"first-disable-toolbar",x:0,y:3,width:30,height:30,handler:function(){var a=this,c=a.up("panel").bindform;if(null!=c){var b=c.searchStore;null!=b&&(1<b.getTotalCount()&&0!=c.currrow)&&(c.getCurrMode()==PageMode.View?1==b.currentPage?(c.currrow=0,c.searchWin.loadHeadData(b.getAt(0))):(b.getProxy().extraParams.hasOwnProperty("page")&&
(b.getProxy().extraParams.page=1),b.currentPage=1,b.load(function(){c.currrow=0;c.searchWin.loadHeadData(b.getAt(0))})):c.getCurrMode()==PageMode.Edit&&Ext.MessageBox.confirm(c.languageObj.confirm_title,c.languageObj.data_lose_warning,function(d){if("yes"==d){1==b.currentPage?(c.currrow=0,c.searchWin.loadHeadData(b.getAt(0))):(b.getProxy().extraParams.hasOwnProperty("page")&&(b.getProxy().extraParams.page=1),b.currentPage=1,b.load(function(){c.currrow=0;c.searchWin.loadHeadData(b.getAt(0))}));for(d=
0;d<c.items.length;d++)try{"function"==typeof c.items.get(d).clearInvalid&&c.items.get(d).clearInvalid()}catch(e){window.console&&console.log(e.message)}c.setCurrMode(PageMode.View);a.up("panel").ModeChange(PageMode.View)}}))}}},{xtype:"button",cls:"back-disable-toolbar",x:30,y:3,width:30,height:30,handler:function(){var a=this,c=a.up("panel").bindform;if(null!=c){var b=c.searchStore,d=c.currrow;if(null!=b&&1<b.getTotalCount()&&1<=d){d--;var e=1,e=0==d%b.pageSize?d/b.pageSize+1:Math.ceil(d/b.pageSize);
c.getCurrMode()==PageMode.View?b.currentPage==e?(c.currrow=d,c.searchWin.loadHeadData(b.getAt(d%b.pageSize))):(b.getProxy().extraParams.hasOwnProperty("page")&&(b.getProxy().extraParams.page=e),b.currentPage=e,b.load(function(){c.currrow=d;c.searchWin.loadHeadData(b.getAt(d%b.pageSize))})):c.getCurrMode()==PageMode.Edit&&Ext.MessageBox.confirm(c.languageObj.confirm_title,c.languageObj.data_lose_warning,function(f){if("yes"==f){b.currentPage==e?(c.currrow=d,c.searchWin.loadHeadData(b.getAt(d%b.pageSize))):
(b.getProxy().extraParams.hasOwnProperty("page")&&(b.getProxy().extraParams.page=e),b.currentPage=e,b.load(function(){c.currrow=d;c.searchWin.loadHeadData(b.getAt(d%b.pageSize))}));for(f=0;f<c.items.length;f++)try{"function"==typeof c.items.get(f).clearInvalid&&c.items.get(f).clearInvalid()}catch(g){window.console&&console.log(g.message)}c.setCurrMode(PageMode.View);a.up("panel").ModeChange(PageMode.View)}})}}}},{xtype:"button",cls:"forward-disable-toolbar",x:60,y:3,width:30,height:30,handler:function(){var a=
this,c=a.up("panel").bindform;if(null!=c){var b=c.searchStore,d=c.currrow;if(null!=b&&1<b.getTotalCount()&&d<b.getTotalCount()-1){d++;var e=1,e=0==d%b.pageSize?d/b.pageSize+1:Math.ceil(d/b.pageSize);c.getCurrMode()==PageMode.View?b.currentPage==e?(c.currrow=d,c.searchWin.loadHeadData(b.getAt(d%b.pageSize))):(b.getProxy().extraParams.hasOwnProperty("page")&&(b.getProxy().extraParams.page=e),b.currentPage=e,b.load(function(){c.currrow=d;c.searchWin.loadHeadData(b.getAt(d%b.pageSize))})):c.getCurrMode()==
PageMode.Edit&&Ext.MessageBox.confirm(c.languageObj.confirm_title,c.languageObj.data_lose_warning,function(f){if("yes"==f){b.currentPage==e?(c.currrow=d,c.searchWin.loadHeadData(b.getAt(d%b.pageSize))):(b.getProxy().extraParams.hasOwnProperty("page")&&(b.getProxy().extraParams.page=e),b.currentPage=e,b.load(function(){c.currrow=d;c.searchWin.loadHeadData(b.getAt(d%b.pageSize))}));for(f=0;f<c.items.length;f++)try{"function"==typeof c.items.get(f).clearInvalid&&c.items.get(f).clearInvalid()}catch(g){window.console&&
console.log(g.message)}c.setCurrMode(PageMode.View);a.up("panel").ModeChange(PageMode.View)}})}}}},{xtype:"button",cls:"end-disable-toolbar",x:90,y:3,width:30,height:30,handler:function(){var a=this,c=a.up("panel").bindform;if(null!=c){var b=c.searchStore,d=-1;if(null!=b&&1<b.getTotalCount())if(c.getCurrMode()==PageMode.View)if(b.currentPage==Math.ceil(b.getTotalCount()/b.pageSize))c.currrow=b.getTotalCount()-1,d=b.getTotalCount()%b.pageSize,d=0==d?b.pageSize-1:d-1,c.searchWin.loadHeadData(b.getAt(d));
else{var e=Math.ceil(b.getTotalCount()/b.pageSize);b.getProxy().extraParams.hasOwnProperty("page")&&(b.getProxy().extraParams.page=e);b.currentPage=e;b.load(function(){c.currrow=b.getTotalCount()-1;d=b.getTotalCount()%b.pageSize;d=0==d?b.pageSize-1:d-1;c.searchWin.loadHeadData(b.getAt(d))})}else c.getCurrMode()==PageMode.Edit&&Ext.MessageBox.confirm(c.languageObj.confirm_title,c.languageObj.data_lose_warning,function(e){if("yes"==e){b.currentPage==Math.ceil(b.getTotalCount()/b.pageSize)?(c.currrow=
b.getTotalCount()-1,d=b.getTotalCount()%b.pageSize,d=0==d?b.pageSize-1:d-1,c.searchWin.loadHeadData(b.getAt(d))):(e=Math.ceil(b.getTotalCount()/b.pageSize),b.getProxy().extraParams.hasOwnProperty("page")&&(b.getProxy().extraParams.page=e),b.currentPage=e,b.load(function(){c.currrow=b.getTotalCount()-1;d=b.getTotalCount()%b.pageSize;d=0==d?b.pageSize-1:d-1;c.searchWin.loadHeadData(b.getAt(d))}));for(e=0;e<c.items.length;e++)try{"function"==typeof c.items.get(e).clearInvalid&&c.items.get(e).clearInvalid()}catch(g){window.console&&
console.log(g.message)}c.setCurrMode(PageMode.View);a.up("panel").ModeChange(PageMode.View)}})}}}]}],setBindForm:function(a){this.bindform=a},ModeChange:function(a){var c=this.items.get(this.items.length-1);null!=c&&(a==PageMode.Edit||a==PageMode.Add?c.setText(this.bindform.languageObj.mode_edit):c.setText(this.bindform.languageObj.mode_view));var c=this.items.get(1),b=this.items.get(2),d=this.items.get(3),e=this.items.get(4),f=this.items.get(5);a==PageMode.Add?(e.removeCls("save-disable-toolbar"),
e.addCls("save-toolbar"),f.removeCls("exit-disable-toolbar"),f.addCls("exit-toolbar"),b.removeCls("edit-toolbar"),b.addCls("edit-disable-toolbar"),d.removeCls("delete-toolbar"),d.addCls("delete-disable-toolbar"),c.removeCls("add-disable-toolbar"),c.addCls("add-toolbar")):a==PageMode.Edit?(f.removeCls("exit-disable-toolbar"),f.addCls("exit-toolbar"),b.removeCls("edit-disable-toolbar"),b.addCls("edit-toolbar"),d.removeCls("delete-disable-toolbar"),d.addCls("delete-toolbar"),e.removeCls("save-disable-toolbar"),
e.addCls("save-toolbar"),c.removeCls("add-toolbar"),c.addCls("add-disable-toolbar")):a==PageMode.View&&(f.removeCls("exit-toolbar"),f.addCls("exit-disable-toolbar"),this.bindform.dataloaded?(b.removeCls("edit-disable-toolbar"),b.addCls("edit-toolbar")):(b.removeCls("edit-toolbar"),b.addCls("edit-disable-toolbar")),d.removeCls("delete-toolbar"),d.addCls("delete-disable-toolbar"),e.removeCls(e.cls),e.addCls("save-disable-toolbar"),c.removeCls("add-disable-toolbar"),c.addCls("add-toolbar"))},setCusButtons:function(a){if(null!=
a){for(var c=0;c<a.length;c++)this.insert(this.items.length-1,a[c]);var c=this.items.get(this.items.length-1),b=c.x,b=b+35*a.length;c.x=b}},exceptionEditAuth:function(){return["1",""]},exceptionDeleteAuth:function(){return["1",""]},setDataLoadMode:function(a){var c=this.items.get(2),b=this.getDockedItems('[dock="right"]')[0],d=this.bindform,e=d.searchStore,f=d.currrow;null!=c&&(a?(c.removeCls("edit-disable-toolbar"),c.addCls("edit-toolbar")):(c.removeCls("edit-toolbar"),c.addCls("edit-disable-toolbar")));
a&&null!=e&&1<e.getTotalCount()?0==f?(b.items.get(0).removeCls("first-toolbar"),b.items.get(0).addCls("first-disable-toolbar"),b.items.get(1).removeCls("back-toolbar"),b.items.get(1).addCls("back-disable-toolbar"),b.items.get(2).removeCls("forward-disable-toolbar"),b.items.get(2).addCls("forward-toolbar"),b.items.get(3).removeCls("end-disable-toolbar"),b.items.get(3).addCls("end-toolbar")):f==e.getTotalCount()-1?(b.items.get(0).removeCls("first-disable-toolbar"),b.items.get(0).addCls("first-toolbar"),
b.items.get(1).removeCls("back-disable-toolbar"),b.items.get(1).addCls("back-toolbar"),b.items.get(2).removeCls("forward-toolbar"),b.items.get(2).addCls("forward-disable-toolbar"),b.items.get(3).removeCls("end-toolbar"),b.items.get(3).addCls("end-disable-toolbar")):(b.items.get(0).removeCls("first-disable-toolbar"),b.items.get(0).addCls("first-toolbar"),b.items.get(1).removeCls("back-disable-toolbar"),b.items.get(1).addCls("back-toolbar"),b.items.get(2).removeCls("forward-disable-toolbar"),b.items.get(2).addCls("forward-toolbar"),
b.items.get(3).removeCls("end-disable-toolbar"),b.items.get(3).addCls("end-toolbar")):(b.items.get(0).removeCls("first-toolbar"),b.items.get(0).addCls("first-disable-toolbar"),b.items.get(1).removeCls("back-toolbar"),b.items.get(1).addCls("back-disable-toolbar"),b.items.get(2).removeCls("forward-toolbar"),b.items.get(2).addCls("forward-disable-toolbar"),b.items.get(3).removeCls("end-toolbar"),b.items.get(3).addCls("end-disable-toolbar"),a||(d.searchStore=null))},setTips:function(a){var c=this.getDockedItems('[dock="right"]')[0];
this.items.get(0).setTooltip(a.search);this.items.get(1).setTooltip(a.add);this.items.get(2).setTooltip(a.edit);this.items.get(3).setTooltip(a._delete);this.items.get(4).setTooltip(a.save);this.items.get(5).setTooltip(a.exit);c.items.get(0).setTooltip(a.first_row);c.items.get(1).setTooltip(a.back_row);c.items.get(2).setTooltip(a.next_row);c.items.get(3).setTooltip(a.last_row)}});
Ext.define("DCI.Customer.BodyGridPanel",{extend:"Ext.panel.Panel",alias:"DCI.Customer.BodyGridPanel",region:"center",layout:"border",bodyStyle:{background:"#eaf1fb"},bodyPadding:5,headform:null,actionurl:"",languageObj:null,currmode:PageMode.View,dataloaded:!1,gridid:"",postvalue:"",keyfields:[],headKeys:{},canEdit:!0,oriGStore:null,oriGColumns:[],stopUsingBtn:[],uid:"",cusFormatIconPath:"",items:[{xtype:"panel",region:"north",border:0,layout:"absolute",height:40,x:400,y:0,items:[{xtype:"button",
width:50,disabled:!0,x:0,y:5,handler:function(){this.up("panel").up("panel").currmode==PageMode.Edit&&this.up("panel").up("panel").addNewRow()}},{xtype:"button",disabled:!0,width:50,x:55,y:5,handler:function(){var a=this.up("panel").up("panel");if(a.currmode==PageMode.Edit&&a.valided()){var c=a.languageObj,b=a.items.get(1).getStore();null!=a.items.get(1).plugins[0]&&a.items.get(1).plugins[0].completeEdit();for(var d=[],e=0,f=0;f<b.getCount();f++)1==b.getAt(f).get("moditag")&&(d.push(b.getAt(f).data),
"add"==b.getAt(f).get("moditp")&&e++);Ext.Ajax.request({method:"POST",url:a.actionurl,params:{DCITag:a.postvalue,uid:a.uid,action:"bodySave",datas:Ext.encode(d),allAdd:b.getCount()==e},success:function(b){a.gridReload();Ext.Msg.alert(c.save_result_title,c.save_success)},failure:function(a,b){Ext.Msg.alert(c.save_result_title,c.save_fail+" :</br>"+b.result.errorMessage)}})}}},{xtype:"button",disabled:!0,width:50,x:110,y:5,handler:function(){var a=this.up("panel").up("panel"),c=a.currmode,b=a.items.get(1),
d=a.languageObj,e=a.actionurl;Ext.MessageBox.confirm(d.delete_confirm_title,d.delete_confirm_msg,function(f){"yes"==f&&(c==PageMode.Edit&&null!=b)&&(f=b.getSelectionModel().getSelection(),0<f.length&&Ext.Ajax.request({method:"POST",url:e,params:{DCITag:a.postvalue,uid:a.uid,action:"bodyDelete",datas:Ext.encode(f[0].data)},success:function(b){a.gridReload();Ext.Msg.alert(d.delete_result_title,d.delete_success)},failure:function(a,b){Ext.Msg.alert(d.delete_result_title,d.delete_fail+" :</br>"+b.result.errorMessage)}}))})}},
{xtype:"button",disabled:!0,width:100,x:165,y:5,handler:function(){var a=this.up("panel").up("panel");a.canEdit?(a.changeMode(a.currmode),a.currmode==PageMode.View&&a.gridReload()):Ext.MessageBox.alert(this.up("panel").up("panel").languageObj.errmsg,this.up("panel").up("panel").languageObj.no_edit_auth)}},{xtype:"button",width:100,x:270,y:5,handler:function(){for(var a=this.up("panel").up("panel"),c=a.items.get(1).getView().headerCt.getGridColumns(),b=a.languageObj,d=[],e=0;e<c.length;e++){var f=
{};f.col_id=c[e].colid;f.col_index=c[e].getIndex();f.col_width=c[e].width;f.col_visible=c[e].hidden?0:1;d.push(f)}Ext.Ajax.request({method:"POST",url:"./../../PublicCtrl.dsc",params:{DCITag:this.up("panel").up("panel").postvalue,uid:this.up("panel").up("panel").uid,action:"saveGFormat",gridid:this.up("panel").up("panel").gridid,datas:Ext.encode(d)},success:function(c){a.addCusFormatIcon();Ext.Msg.alert(b.save_result_title,b.save_success)},failure:function(a,c){Ext.Msg.alert(b.save_result_title,b.save_fail+
" :</br>"+c.result.errorMessage)}})}},{xtype:"button",width:120,x:375,y:5,handler:function(){var a=this.up("panel").up("panel"),c=a.items.get(1),b=a.languageObj,d=a.getOGC();Ext.MessageBox.confirm(b.load_def_confirm_title,b.load_def_confirm_msg,function(e){"yes"==e&&Ext.Ajax.request({method:"POST",url:"./../../PublicCtrl.dsc",params:{DCITag:a.postvalue,uid:a.uid,action:"clearGFormat",gridid:a.gridid},success:function(e){c.reconfigure(null,d);a.rmCusFormatIcon();Ext.Msg.alert(b.load_def_result_title,
b.load_def_success)},failure:function(a,c){Ext.Msg.alert(b.load_def_result_title,b.load_def_fail+" :</br>"+c.result.errorMessage)}})})}}]},{xtype:"grid",region:"center",stripeRows:!0,autoScroll:!0,loadMask:!0,allowDeselect:!0,selModel:{allowDeselect:!0},enableTextSelection:!0,viewConfig:{forceFit:!1,autoLoad:!1},columns:[],store:null,listeners:{celldblclick:function(a,c,b,d,e,f,g,h){this.up("panel").griddbclick(a,c,b,d,e,f,g,h)},selectionchange:function(a,c,b){this.up("panel").gridselectionchange(a,
c,b)},deselect:function(a,c,b,d){this.up("panel").griddeselect(a,c,b,d)}},plugins:[Ext.create("Ext.grid.plugin.CellEditing",{clicksToEdit:1,listeners:{beforeedit:function(a,c,b){if(c.grid.up("panel").currmode==PageMode.View)return!1;if("add"!=c.record.get("moditp")&&null!=c.grid.up("panel").keyfields){a=c.grid.up("panel").keyfields;for(b=0;b<a.length;b++)if(a[b]==c.column.dataIndex)return!1}},edit:function(a,c,b){1!=c.record.get("moditag")&&null!=c.record&&(c.record.set("moditag",1),c.record.set("moditp",
"edit"),c.record.commit())}}})]}],setCusButton:function(a){if(null!=a)for(var c=0;c<a.length;c++)this.insert(this.items.length-1,a[c])},getOGS:function(){return this.oriGStore},getOGC:function(){return this.oriGColumns},isCusFormatExist:function(){for(var a=this.items.get(0),c=!1,b=0;b<a.items.length;b++)if("cusicon"==a.items.get(b).iconid){c=!0;break}return c},addCusFormatIcon:function(){var a=this,c=this.items.get(0),b=c.items.length-1;a.isCusFormatExist()||(c.items.insert(c.items.length,Ext.create("DCI.Customer.Img",
{iconid:"cusicon",src:a.cusFormatIconPath,x:c.items.get(b).x+c.items.get(b).width+2,y:8,width:20,height:20,listeners:{afterrender:function(b){Ext.create("Ext.tip.ToolTip",{target:b.getEl(),html:a.languageObj.cus_format})}}})),c.update())},rmCusFormatIcon:function(){var a=this.items.get(0);this.isCusFormatExist()&&(a.items.remove(a.items.get(a.items.length-1)),a.update())},initBody:function(a,c){var b=this,d=this.items.get(1),e=b.items.get(0),f=[],g=null;b.oriGStore=a;b.oriGColumns=[];if(null==b.cusFormatIconPath||
""==b.cusFormatIconPath)b.cusFormatIconPath="../../images/icons/CusGridFormat.png";for(var h=0;h<c.length;h++){var g={},k;for(k in c[h])g[k]=c[h][k];b.oriGColumns.push(g)}Ext.create("Ext.data.Store",{autoLoad:!1,fields:["colFormats"],proxy:{type:"ajax",url:"./../../PublicCtrl.dsc",actionMethods:{read:"POST"},reader:{type:"json"},extraParams:{DCITag:this.postvalue,uid:this.uid,action:"getGFormat",gridid:this.gridid}}}).load(function(e){if(0<e.length){var h=Ext.create("Ext.data.Store",{fields:["col_id",
"col_index","col_width","col_visible"],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}});h.loadData(e[0].get("colFormats"));if(0<h.getCount()){b.addCusFormatIcon();for(e=0;e<h.getCount();e++)for(var g=0;g<c.length;g++)if(c[g].colid==h.getAt(e).get("col_id")){"1"==h.getAt(e).get("col_visible")?(c[g].hasOwnProperty("hidden"),c[g].hidden=!1,0!=h.getAt(e).get("col_width")&&(c[g].hasOwnProperty("width"),c[g].width=parseInt(h.getAt(e).get("col_width")))):(0!=h.getAt(e).get("col_width")&&(c[g].hasOwnProperty("width"),
c[g].width=parseInt(h.getAt(e).get("col_width"))),c[g].hasOwnProperty("hidden"),c[g].hidden=!0);f.push(c[g]);c.splice(g,1);break}if(null!=c&&0!=c.leght)for(e=0;e<c.length;e++)c[e].hidden=!0,f.push(c[e])}else f=c;d.reconfigure(a,f)}else d.reconfigure(a,c)});b.changeMode(PageMode.Edit);b.dataloaded(!1);null!=b.languageObj&&(e.items.get(0).setText(b.languageObj.add),e.items.get(1).setText(b.languageObj.save),e.items.get(2).setText(b.languageObj._delete),e.items.get(3).setText(b.languageObj.to_edit),
e.items.get(4).setText(b.languageObj.save_format),e.items.get(5).setText(b.languageObj.load_def_format));null!=this.headform&&(this.headform.bodypanel=this)},getCurrMode:function(){return this.currmode},addNewRow:function(){},dataloaded:function(a){var c=this.items.get(0).items.get(3);null!=c&&(c.setDisabled(!a),a||this.changeMode(PageMode.Edit))},clearGrid:function(){var a=this.items.get(1).getStore();null!=a&&a.removeAll()},changeMode:function(a){var c=this.items.get(0).items;if(a==PageMode.View){for(a=
0;3>=a;a++)if(3==a)c.get(a).setText(this.languageObj.to_view);else if(null!=this.stopUsingBtn&&0<this.stopUsingBtn.length){for(var b=!1,d=0;d<this.stopUsingBtn.length;d++)if(this.stopUsingBtn[d]==a){b=!0;break}c.get(a).setDisabled(b)}else c.get(a).setDisabled(!1);this.currmode=PageMode.Edit}else{for(a=0;3>=a;a++)3==a?c.get(a).setText(this.languageObj.to_edit):c.get(a).setDisabled(!0);this.currmode=PageMode.View}},setNewCondi:function(){},gridReload:function(){var a=this.items.get(1);null!=a&&a.getStore().load()},
griddbclick:function(a,c,b,d,e,f,g,h){},gridselectionchange:function(a,c,b){},griddeselect:function(a,c,b,d){},getGrid:function(){return this.items.get(1)},valided:function(){return!0}});
Ext.define("DCI.Customer.ViewGridPanel",{extend:"Ext.panel.Panel",alias:"DCI.Customer.ViewGridPanel",region:"center",layout:"border",bodyStyle:{background:"#eaf1fb"},bodyPadding:5,actionurl:"",dataloaded:!1,gridid:"",postvalue:"",uid:"",cusFormatIconPath:"",oriGStore:null,oriGColumns:[],items:[{xtype:"panel",region:"north",border:0,header:!1,split:!0,collapsible:!0,collapseMode:"mini",animCollapse:!1,collapsed:!0,layout:"absolute",height:35,items:[{xtype:"button",text:"save format",width:150,x:0,
y:5,handler:function(){for(var a=this.up("panel").up("panel"),c=a.items.get(2).getView().headerCt.getGridColumns(),b=a.languageObj,d=[],e=0;e<c.length;e++){var f={};f.col_id=c[e].colid;f.col_index=c[e].getIndex();f.col_width=c[e].width;f.col_visible=c[e].hidden?0:1;d.push(f)}Ext.Ajax.request({method:"POST",url:"./../../PublicCtrl.dsc",params:{DCITag:a.postvalue,uid:a.uid,action:"saveGFormat",gridid:a.gridid,datas:Ext.encode(d)},success:function(c){a.addCusFormatIcon();Ext.Msg.alert(b.save_result_title,
b.save_success)},failure:function(a,c){Ext.Msg.alert(b.save_result_title,b.save_fail+" :</br>"+c.result.errorMessage)}})}},{xtype:"button",width:120,x:155,y:5,handler:function(){var a=this.up("panel").up("panel"),c=a.items.get(2),b=a.languageObj,d=a.getOGS(),e=a.getOGC();Ext.MessageBox.confirm(b.load_def_confirm_title,b.load_def_confirm_msg,function(f){"yes"==f&&Ext.Ajax.request({method:"POST",url:"./../../PublicCtrl.dsc",params:{DCITag:a.postvalue,uid:a.uid,action:"clearGFormat",gridid:a.gridid},
success:function(f){c.reconfigure(d,e);a.rmCusFormatIcon();Ext.Msg.alert(b.load_def_result_title,b.load_def_success)},failure:function(a,c){Ext.Msg.alert(b.load_def_result_title,b.load_def_fail+" :</br>"+c.result.errorMessage)}})})}}]},{xtype:"grid",region:"center",stripeRows:!0,autoScroll:!0,loadMask:!0,allowDeselect:!0,selModel:{allowDeselect:!0},enableTextSelection:!0,viewConfig:{forceFit:!1,autoLoad:!1},columns:[],store:null,listeners:{celldblclick:function(a,c,b,d,e,f,g,h){this.up("panel").griddbclick(a,
c,b,d,e,f,g,h)}}}],getOGS:function(){return this.oriGStore},getOGC:function(){return this.oriGColumns},isCusFormatExist:function(){for(var a=this.items.get(0),c=!1,b=0;b<a.items.length;b++)if("cusicon"==a.items.get(b).iconid){c=!0;break}return c},addCusFormatIcon:function(){var a=this,c=this.items.get(0),b=c.items.length-1;a.isCusFormatExist()||(c.items.insert(c.items.length,Ext.create("DCI.Customer.Img",{iconid:"cusicon",src:a.cusFormatIconPath,x:c.items.get(b).x+c.items.get(b).width+2,y:8,width:20,
height:20,listeners:{afterrender:function(b){Ext.create("Ext.tip.ToolTip",{target:b.getEl(),html:a.languageObj.cus_format})}}})),c.update())},rmCusFormatIcon:function(){var a=this.items.get(0);this.isCusFormatExist()&&(a.items.remove(a.items.get(a.items.length-1)),a.update())},initBody:function(a,c){var b=this,d=b.items.get(2),e=b.items.get(0),f=[],g=null;b.oriGStore=a;b.oriGColumns=[];if(null==b.cusFormatIconPath||""==b.cusFormatIconPath)b.cusFormatIconPath="../../images/icons/CusGridFormat.png";
for(var h=0;h<c.length;h++){var g={},k;for(k in c[h])g[k]=c[h][k];b.oriGColumns.push(g)}Ext.create("Ext.data.Store",{autoLoad:!1,fields:["colFormats"],proxy:{type:"ajax",url:"./../../PublicCtrl.dsc",actionMethods:{read:"POST"},reader:{type:"json"},extraParams:{DCITag:b.postvalue,uid:b.uid,action:"getGFormat",gridid:b.gridid}}}).load(function(e){if(0<e.length){var h=Ext.create("Ext.data.Store",{fields:["col_id","col_index","col_width","col_visible"],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}});
h.loadData(e[0].get("colFormats"));if(0<h.getCount()){b.addCusFormatIcon();for(e=0;e<h.getCount();e++)for(var g=0;g<c.length;g++)if(c[g].colid==h.getAt(e).get("col_id")){"1"==h.getAt(e).get("col_visible")?(c[g].hasOwnProperty("hidden"),c[g].hidden=!1,0!=h.getAt(e).get("col_width")&&(c[g].hasOwnProperty("width"),c[g].width=parseInt(h.getAt(e).get("col_width")))):(0!=h.getAt(e).get("col_width")&&(c[g].hasOwnProperty("width"),c[g].width=parseInt(h.getAt(e).get("col_width"))),c[g].hasOwnProperty("hidden"),
c[g].hidden=!0);f.push(c[g]);c.splice(g,1);break}if(null!=c&&0!=c.leght)for(e=0;e<c.length;e++)c[e].hidden=!0,f.push(c[e])}else f=c;d.reconfigure(a,f)}else d.reconfigure(a,c)});null!=b.languageObj&&(e.items.get(0).setText(b.languageObj.save_format),e.items.get(1).setText(b.languageObj.load_def_format))},clearGrid:function(){var a=this.items.get(2).getStore();null!=a&&a.removeAll()},gridReload:function(){var a=this.items.get(2);null!=a&&a.getStore().load()},griddbclick:function(a,c,b,d,e,f,g,h){},
getGrid:function(){return this.items.get(2)}});
Ext.define("DCI.Customer.HeadPanel",{extend:"Ext.panel.Panel",alias:"DCI.Customer.HeadPanel",region:"north",width:300,border:0,headform:null,postvalue:"",uid:"",layout:"border",canEdit:!0,cusMsg:[],keepAdd:!0,exceptionEditAuth:function(){return["1",""]},exceptionDeleteAuth:function(){return["1",""]},afterSaveFunc:function(a){},initComponent:function(){if(null!=this.headform){var a=Ext.create("DCI.Customer.ToolBarPanel",{bindform:this.headform,postvalue:this.postvalue,uid:this.uid,canEdit:this.canEdit,
exceptionEditAuth:this.exceptionEditAuth,exceptionDeleteAuth:this.exceptionDeleteAuth,afterSaveFunc:this.afterSaveFunc,cusMsg:this.cusMsg,keepAdd:this.keepAdd});a.setTips(this.headform.languageObj);a.ModeChange(PageMode.View);this.headform.toolpanel=a;this.items=[a,this.headform]}this.callParent(arguments)},setCusButtons:function(a){null!=this.items.get(0)&&this.items.get(0).setCusButtons(a)},getCurrMode:function(){if(null!=this.headform)return this.headform.getCurrMode()}});
Ext.define("DCI.Customer.ProgressBar",{extend:"Ext.ProgressBar",xtype:"dciprogressBar",alias:"DCI.Customer.ProgressBar",tbgcolor:"#73a3e0",textStyle:"",renderTpl:'<tpl if="internalText">,<div class="{baseCls}-text {baseCls}-text-back">{text}</div>,</tpl>,<div id="{id}-bar" class="{baseCls}-bar" style="background-color:{textbgcolor};width:{percentage}%">,<tpl if="internalText">,<div <tpl if="textStyle">style={textStyle}</tpl> class="{baseCls}-text">,<div>{text}</div>,</div>,</tpl>,</div>'.split(","),
initRenderData:function(){return Ext.apply(this.callParent(),{internalText:!this.hasOwnProperty("textEl"),text:this.text||"&#160;",percentage:this.value?100*this.value:0,textbgcolor:this.tbgcolor,textStyle:""==this.textStyle?null:this.textStyle})}});
Ext.define("DCI.Customer.CheckColumn",{extend:"Ext.grid.column.CheckColumn",xtype:"dcicheckcolumn",alias:"DCI.Customer.CheckColumn",colid:"",showOnly:!1,isSingleSelect:!1,width:200,canEditControl:function(a,c){return!0},listeners:{beforecheckchange:function(a,c,b,d){return this.showOnly?!1:this.up("panel").up("panel").currmode==PageMode.View?!1:this.canEditControl(a,c)},checkchange:function(a,c,b,d){b=this.up("panel").getStore();!this.showOnly&&(null!=b&&1!=b.getAt(c).get("moditag"))&&(b.getAt(c).set("moditag",
1),b.getAt(c).set("moditp","edit"),b.getAt(c).commit());if(this.isSingleSelect&&b)for(d=0;d<b.getCount();d++)d!=c&&(b.getAt(d).set(a.dataIndex,!1),1!=b.getAt(d).get("moditag")&&(b.getAt(d).set("moditag",1),b.getAt(d).set("moditp","edit"),b.getAt(d).commit()))}}});
Ext.define("DCI.Customer.P2DisplayColumn",{extend:"Ext.grid.column.Column",xtype:"dcip2column",alias:"DCI.Customer.P2DisplayColumn",colid:"",width:100,renderer:function(a,c,b,d,e,f){this.callParent(arguments);var g=null,h=this.headerCt.getGridColumns()[e].dataIndex,k=b.get(h+"_type"),g=b.get(h+"_ptcolor"),h=b.get(h+"_pbgcolor");if("LIGHT"==k)g="<img src='./../../ImageLoader.dsc?iconid="+a+"' width=16 hight=16/>";else if("CHECKBOX"==k)g=a?'<img class="x-grid-checkcolumn x-grid-checkcolumn-checked" src="data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==">':
'<img class="x-grid-checkcolumn" src="data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==">';else if("IMAGELINK"==k)g="<img src='"+a+"' />";else if("IMAGEMAPPING"==k)g="<img src='./../../ImageLoader.dsc?imgpath="+a+"'/>";else if("PROGRESS"==k){var k=a.replace(/,/g,""),l=1*a.replace(/,/g,"")/100,m="#FFFFFF";g&&(g&&""!=g&&""!=g)&&(m="#"+g);g=Ext.create("DCI.Customer.ProgressBar",{tbgcolor:g&&h&&""!=g&&""!=h?"#"+h:51<=k&&81>k?"brown":81<=k&&100>k?"blue":100<=k?"green":
"red",textStyle:"color:"+m,style:{width:"100%"}});1<l&&(l=1);g.updateProgress(l,k+"%",!0);g=Ext.DomHelper.markup(g.getRenderTree())}else g=a;return g}});
Ext.define("DCI.Customer.NumberBox",{extend:"Ext.form.field.Number",alias:"DCI.Customer.NumberBox",defaultvalue:30,labelAlign:"right",ispk:!1,canEdit:!0,maxValue:9999,minValue:30,cusStyle:null,loadDefault:function(){this.setValue(this.defaultvalue)},setReadOnly:function(a){a?this.setFieldStyle({backgroundColor:"#ddd",backgroundImage:"none"}):null!=this.cusStyle&&""!=this.cusStyle?this.setFieldStyle(this.cusStyle):this.setFieldStyle({backgroundColor:"#FFFFFF"});this.callParent(arguments)},initComponent:function(){null!=
this.style&&(this.cusStyle=this.style);this.callParent(arguments)}});Ext.define("DCI.Customer.LightColumn",{extend:"Ext.grid.column.Column",xtype:"dcilightcolumn",alias:"DCI.Customer.LightColumn",colid:"",width:100,renderer:function(a,c,b,d,e,f,g){c=g.ownerCt.columns[e].sqlid;void 0==c&&(c="");g=g.ownerCt.columns[e].rowHeight;void 0==g&&(g="16");return" <img id='light"+c+d+";"+e+"' src='./../../ImageLoader.dsc?iconid="+a+"' width="+g+" hight="+g+"/> "}});
Ext.define("DCI.Customer.ImgPickerColumn",{extend:"Ext.grid.column.Column",xtype:"dciimgpickercolumn",alias:"DCI.Customer.ImgPickerColumn",colid:"",text:"",menuDisabled:!0,sortable:!1,maxWidth:30,minWidth:30,width:30,renderer:function(a){this.callParent(arguments);return"<img src='./../../images/button_icon/ToolBarSearch.png' />"}});
Ext.define("DCI.Customer.ImgColumn",{extend:"Ext.grid.column.Column",xtype:"dciimgcolumn",alias:"DCI.Customer.ImgColumn",align:"center",colid:"",width:100,renderer:function(a){this.callParent(arguments);return"<img src='"+a+"' />"}});Ext.define("DCI.Customer.ImgMapColumn",{extend:"Ext.grid.column.Column",xtype:"dciimgmapcolumn",alias:"DCI.Customer.ImgMapColumn",colid:"",width:100,renderer:function(a){this.callParent(arguments);return"<img src='./../../ImageLoader.dsc?imgpath="+a+"'/>"}});
Ext.define("DCI.Customer.DateField",{extend:"Ext.form.field.Date",xtype:"dcidatefield",alias:"DCI.Customer.DateField",oriAllowBlank:!1,defaultvalue:"",ispk:!1,canEdit:!0,cusStyle:null,loadDefault:function(){this.setValue(this.defaultvalue)},setReadOnly:function(a){a?(this.allowBlank=!0,this.setFieldStyle({backgroundColor:"#ddd",backgroundImage:"none"})):(this.allowBlank=this.oriAllowBlank,null!=this.cusStyle&&""!=this.cusStyle?this.setFieldStyle(this.cusStyle):this.setFieldStyle({backgroundColor:"#FFFFFF"}));
this.callParent(arguments)},initComponent:function(){this.oriAllowBlank=this.allowBlank;null!=this.style&&(this.cusStyle=this.style);this.callParent(arguments)}});
Ext.define("DCI.Customer.ColorPicker",{extend:"Ext.form.field.Trigger",xtype:"dcicolorpicker",alias:"DCI.Customer.ColorPicker",picker:null,defaultColor:"FFFFFF",curColor:"",setValue:function(a){this.curColor=a;this.callParent(arguments);return this},getValue:function(){return this.curColor},onTriggerClick:function(){var a=this;a.picker?a.picker.hidden?a.picker.show():a.picker.hide():(a.picker=Ext.create("Ext.picker.Color",{pickerField:this,ownerCt:this,renderTo:document.body,floating:!0,hidden:!1,
focusOnShow:!0,style:{backgroundColor:"#fff"},listeners:{scope:this,select:function(c,b,d){a.setValue(b);a.setFieldStyle("background:#"+b);a.picker.hide()},show:function(c,b){c.getEl().monitorMouseLeave(500,c.hide,c);a.picker.setXY([a.getX()+a.getLabelWidth(),a.getY()+a.getHeight()])},move:function(c,b,d,e){c.setXY([a.getX()+a.getLabelWidth(),a.getY()+a.getHeight()])}}}),a.picker.alignTo(a.inputEl,"tl-bl?"),a.picker.show(a.inputEl))},initComponent:function(){null!=this.curColor&&""!=this.curColor?
this.setFieldStyle("background:#"+this.curColor):this.setFieldStyle("background:#"+this.defaultColor);this.callParent(arguments)},setCurrColor:function(a){this.curColor=a;this.setFieldStyle("background:#"+this.curColor)},loadDefault:function(){var a="FFFFFF";this.defaultColor&&(null!=this.defaultColor&&""!=this.defaultColor)&&(a=this.defaultColor);this.picker&&null!=this.picker&&this.picker.select(a);this.setValue(a);this.setFieldStyle("background:#"+this.curColor)}});
Ext.define("DCI.Customer.ProgressBarColumn",{extend:"Ext.grid.column.Column",xtype:"dciprogressbarcolumn",alias:"DCI.Customer.ProgressBarColumn",colid:"",width:100,renderer:function(a,c,b,d,e,f){this.callParent(arguments);var g=this.headerCt.getGridColumns()[e].dataIndex,h=b.get(g+"_ptcolor"),k=b.get(g+"_pbgcolor"),g=a.replace(/,/g,""),l=1*a.replace(/,/g,"")/100,m="#FFFFFF";h&&(h&&""!=h&&""!=h)&&(m="#"+h);h=Ext.create("DCI.Customer.ProgressBar",{tbgcolor:h&&k&&""!=h&&""!=k?"#"+k:51<=g&&81>g?"brown":
81<=g&&100>g?"blue":100<=g?"green":"red",textStyle:"color:"+m,style:{width:"100%"}});1<l&&(l=1);h.updateProgress(l,g+"%",!0);return Ext.DomHelper.markup(h.getRenderTree())}});Ext.define("DCI.Customer.Hidden",{extend:"Ext.form.field.Hidden",alias:"DCI.Customer.Hidden",defaultvalue:"",triggerModi:!0,loadDefault:function(){this.setValue(this.defaultvalue)}});
Ext.define("DCI.Customer.CheckBox",{extend:"Ext.form.field.Checkbox",xtype:"dcicheckbox",alias:"DCI.Customer.CheckBox",defaultvalue:"",ispk:!1,canEdit:!0,checked:!1,loadDefault:function(){this.setValue(this.defaultvalue)},getSubmitValue:function(){var a=0;return a=this.checked?1:0}});Ext.define("DCI.Customer.EmptyButton",{extend:"Ext.button.Button",alias:"DCI.Customer.EmptyButton",targetComp:null,ispk:!1,canEdit:!0});
Ext.define("DCI.Customer.OpenWinWindow",{extend:"Ext.window.Window",alias:"DCI.Customer.OpenWinWindow",layout:"border",title:"Query",height:200,width:400,minWidth:300,minHeight:200,modal:!0,plain:!0,parentButton:null,showSelectAll:!1,items:[{xtype:"panel",region:"north",layout:"absolute",height:35,items:[{xtype:"combobox",fieldLabel:"",displayField:"label",valueField:"value",typeAhead:!0,editable:!1,queryMode:"local",labelWidth:1,matchFieldWidth:!1,multiSelect:!1,forceSelection:!0,store:Ext.create("Ext.data.Store",
{fields:[{name:"label",type:"string"},{name:"value",type:"string"}],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}}),x:5,y:5},{xtype:"textfield",name:"qvalue",fieldLabel:"",labelWidth:1,width:160,x:140,y:5},{xtype:"button",cls:"search-toolbar",width:30,height:30,x:300,y:1,handler:function(){var a=this.up("panel").up("window").items.get(1).getStore(),c=this.up("panel").items.get(0).getValue(),b=this.up("panel").items.get(1).getValue();a.getProxy().extraParams.hasOwnProperty("filter")&&(a.getProxy().extraParams.filter=
" and "+c+" like '%"+b+"%' ");a.load()}},{xtype:"dcicheckbox",labelWidth:30,defaultvalue:0,x:335,y:5,triggerChange:!0,listeners:{change:function(a,c,b,d){this.triggerChange&&null!=this.up("panel").up("panel").parentButton&&this.up("panel").up("panel").parentButton.selectAllEvent(a,c,b,d)}},setChecked:function(a){this.triggerChange=!1;this.setValue(a);this.triggerChange=!0}}]},{xtype:"grid",region:"center",renderer:"component",border:0,stripeRows:!0,autoScroll:!0,loadMask:!0,enableTextSelection:!0,
viewConfig:{forceFit:!1,autoLoad:!1},columns:[],store:null}],buttons:[{xtype:"button",text:"OK",btnkey:"btn001",handler:function(){var a=this.up("window");a.parentButton.setSelectedData(a.items.get(1).getStore());a.close()}},{xtype:"button",text:"Cancel",btnkey:"btn002",handler:function(){this.up("window").close()}}],setInitObjects:function(a,c,b){if(0<a.length){var d=this.items.get(0).items.get(0);d.getStore().loadData(a[0].get("cols"));0<d.getStore().getCount()&&("undefined"!=typeof d&&null!=d)&&
d.setValue(d.getStore().getAt(0).get("value"))}this.items.get(1).reconfigure(c,b);null!=this.parentButton.langsObj&&(this.down("button[btnkey=btn001]").setText(this.parentButton.langsObj.ok),this.down("button[btnkey=btn002]").setText(this.parentButton.langsObj.cancel),this.setTitle(this.parentButton.langsObj.toolbar_query_title),this.items.get(0).items.get(3).setFieldLabel(this.parentButton.langsObj.select_all));this.items.get(0).items.get(3).setVisible(this.showSelectAll);this.showSelectAll&&this.items.get(0).items.get(3).setValue(this.parentButton.isAll())}});
Ext.define("DCI.Customer.OpenWinTrigger",{extend:"Ext.button.Button",alias:"DCI.Customer.OpenWinTrigger",targetComp:null,ispk:!1,canEdit:!0,displayCols:[],gridStore:null,filterComboRecord:null,actionurl:"",buttonID:"",pvalue:"",puid:"",winHeight:200,winWidth:450,langsObj:null,showSelectAll:!1,handler:function(){var a=Ext.create("DCI.Customer.OpenWinWindow",{height:this.winHeight,width:this.winWidth,parentButton:this,showSelectAll:this.showSelectAll});a.setInitObjects(this.filterComboRecord,this.gridStore,
this.displayCols);a.show()},setReadOnly:function(a){this.setDisabled(a)},loadDefault:function(){null!=this.targetComp&&this.targetComp.loadDefault()},setInitObjs:function(a){this.filterComboRecord=a;null!=this.gridStore&&this.gridStore.load()},setSelectedData:function(){},initComponent:function(){var a=this;Ext.create("Ext.data.Store",{autoLoad:!1,fields:["cols"],proxy:{type:"ajax",url:a.actionurl,actionMethods:{read:"POST"},reader:{type:"json"},extraParams:{DCITag:a.pvalue,uid:a.puid,action:"openwinQcombo",
btnid:a.buttonID}}}).load(function(c){0<c.length&&a.setInitObjs(c)});this.callParent(arguments)},selectAllEvent:function(a,c,b,d){},isAll:function(){return 0}});
Ext.define("DCI.Customer.SqlEditor",{extend:"Ext.form.TextArea",alias:"DCI.Customer.SqlEditor",width:"100%",labelWidth:75,msgTarget:"side",autoScroll:!0,cusStyle:null,defaultvalue:"",ispk:!1,canEdit:!0,codemirror:null,initComponent:function(){null!=this&&(this.maxHeight=this.height);null!=this.style&&(this.cusStyle=this.style);this.callParent(arguments)},loadDefault:function(){this.setValue(this.defaultvalue)},setReadOnly:function(a){a?this.setFieldStyle({backgroundColor:"#ddd",backgroundImage:"none"}):
null!=this.cusStyle&&""!=this.cusStyle?this.setFieldStyle(this.cusStyle):this.setFieldStyle({backgroundColor:"#FFFFFF"});this.callParent(arguments)}});
Ext.define("Ext.ux.plugins.FitToParent",{alias:"plugin.fittoparent",extend:"Object",fitWidth:!0,fitHeight:!0,offsets:[0,0],constructor:function(a){a=a||{};if(a.tagName||a.dom||Ext.isString(a))a={parent:a};Ext.apply(this,a)},init:function(a){this.component=a;a.on("render",function(a){this.parent=Ext.get(this.parent||a.getPositionEl().dom.parentNode);a.doLayout&&(a.monitorResize=!0,a.doLayout=Ext.Function.createInterceptor(a.doLayout,this.fitSize,this));this.fitSize();Ext.EventManager.onWindowResize(this.fitSize,
this)},this,{single:!0})},fitSize:function(){var a=this.component.getPosition(!0),c=this.parent.getViewSize();this.component.setSize(this.fitWidth?c.width-a[0]-this.offsets[0]:void 0,this.fitHeight?c.height-a[1]-this.offsets[1]:void 0)}});var viewHeight=0;
function showview(a,c){var b=180;refalshTime=Ext.create("Ext.toolbar.TextItem",{text:getCurrentTime()});Ext.define("TreeModel",{extend:"Ext.data.Model",fields:[{name:"id",type:"string"},{name:"text",type:"string"},{name:"level",type:"int"},{name:"leaf",type:"boolean"},{name:"url",type:"string"},{name:"cls",type:"string"},{name:"parent",type:"string"},{name:"lkbcolor",type:"string"},{name:"imgurl",type:"string"}]});var d=Ext.create("Ext.data.Store",{fields:["display","value"],data:[{display:"5",value:"5"},
{display:"10",value:"10"},{display:"30",value:"30"},{display:"60",value:"60"},{display:"120",value:"120"},{display:"180",value:"180"},{display:"300",value:"300"},{display:"600",value:"600"}]}),e=Ext.create("Ext.Button",{enableToggle:!0,iconCls:"startbutton",tooltip:"Auto Refresh",handler:function(){null!=mainPanel.items&&0!=mainPanel.items.length?timerControl(g,this,c,b):this.toggle(!1)}}),f=Ext.create("Ext.Button",{iconCls:"refreshbutton",tooltip:"Refresh",handler:function(){refreshTab(c)}});timergapcombo=
Ext.create("Ext.form.field.ComboBox",{store:d,queryMode:"local",displayField:"display",valueField:"value",width:60,typeAhead:!0,editable:!1,listeners:{change:function(a,c,d,e){b!=c&&(timerisrunning?(alert("please stop timmer"),a.setValue(d)):b=c)}}});timergapcombo.setValue("180");d=Ext.create("Ext.data.TreeStore",{model:"TreeModel",proxy:{type:"ajax",url:"index.do",actionMethods:{read:"POST"},reader:{type:"json",root:"datas"},extraParams:{DCITag:c}},root:{text:"LKB Functions",id:"FuncTreeRoot",expanded:!0}});
funcTree=Ext.create("Ext.tree.Panel",{rootVisible:!1,width:150,height:150,viewConfig:{loadMask:!0},useArrows:!0,store:d,listeners:{itemclick:function(d,f,l,m,n){if(!0==f.data.leaf){timerisrunning&&timerControl(g,e,c,b);indexstatusbar.showBusy();d="tab"+f.data.id;l=!1;for(m=0;m<mainPanel.items.length&&!l;m++)mainPanel.items.getAt(m).id==d&&(l=!0);l?(mainPanel.setActiveTab(d),indexstatusbar.clearStatus({useDefaults:!0})):(l="",l=-1!=d.indexOf("EKBQ")?"/LKB/FuncViews/Query/"+d.substring(3)+".jsp":-1!=
d.indexOf("SCH")?"/LKB/FuncViews/WS/"+d.substring(3)+".jsp":"/LKB/FuncViews/LKB01.jsp",functab=Ext.create("Ext.Panel",{id:d,title:f.data.text,closable:!0,loader:{url:l,scripts:!0,params:{SFTTag:a,funcid:f.data.id,lkbcolor:f.data.lkbcolor,imgurl:f.data.imgurl},listeners:{load:function(a,b,c,d){indexstatusbar.clearStatus({useDefaults:!0})}}},listeners:{added:function(a){a.loader.load()}}}),mainPanel.add(functab),functab.show(),mainPanel.setActiveTab(d))}}}});indexstatusbar=Ext.create("Ext.ux.StatusBar",
{id:"index-statusbar",defaultText:"Ready",defaultIconCls:"x-status-valid",items:["-",f,"-",e,timergapcombo,"-","Last Update Time :",refalshTime]});mainPanel=Ext.create("Ext.tab.Panel",{region:"center",xtype:"tabpanel",deferredRender:!1,bbar:indexstatusbar,listeners:{tabchange:function(a,d,f,m){timerisrunning&&timerControl(g,e,c,b);-1==a.getActiveTab().getId().indexOf("EKBQ")?indexstatusbar.show():indexstatusbar.hide();indexstatusbar.doLayout()},resize:function(a,b,c,d,e,f){null!=a.getActiveTab()&&
(d=Ext.getCmp(a.getActiveTab().getId().substring(3)+"main"),"undefined"!=typeof d&&null!=d?(d.setWidth(b),d.setHeight(c-a.getTabBar().getHeight())):(d=Ext.getCmp("KBP"+a.getActiveTab().getId().substring(3)),"undefined"!=typeof d&&null!=d&&(d.setWidth(b),d.setHeight(c-a.getTabBar().getHeight()-indexstatusbar.getHeight()))))}}});Ext.create("Ext.Viewport",{id:"DCIIndex",layout:"border",items:[{region:"west",stateId:"funcPanel",id:"west-panel",title:"功能列表",split:!0,width:200,minWidth:175,maxWidth:300,
collapsible:!0,animCollapse:!0,layout:"fit",items:[funcTree]},mainPanel]});viewHeight=mainPanel.getHeight()-mainPanel.getTabBar().getHeight();var g=(new Ext.util.TaskRunner).newTask({run:function(){refreshTab(c)}})}
function refreshTab(a){if(null!=mainPanel.items&&0!=mainPanel.items.length){var c=mainPanel.getActiveTab();null==c?alert("no active tab"):(c=c.id.substring(3),Ext.define("DCI.DCIBLKModel1",{extend:"Ext.data.Model",fields:[{name:"id",type:"string",mapping:"id"},{name:"pattern",type:"int"},{name:"bodyStyle",type:"string"},{name:"html",type:"string"},{name:"height",type:"int"}]}),a=new Ext.data.Store({id:"DCIBLKStore",requires:"DCI.DCIBLKModel1",model:"DCI.DCIBLKModel1",proxy:{type:"ajax",url:"showlkb.do",
actionMethods:{read:"POST"},reader:{type:"json"},extraParams:{action:"refresh",DCITag:a,funcid:c}}}),c="KBP"+c,a.load(function(a){if(null!=a&&0<a.length)for(var c=null,e=0;e<a.length;e++)c=Ext.getCmp(a[e].get("id")),1==a[e].get("pattern")?(c.body.update(a[e].get("html")),c.setBodyStyle(a[e].get("bodyStyle"))):(3==a[e].get("pattern")||4==a[e].get("pattern"))&&c.body.update(a[e].get("html"))}),Ext.fly(refalshTime.getEl()).update(getCurrentTime()))}}
function timerControl(a,c,b,d){timerisrunning?(a.stop(),timerisrunning=!1,c.setIconCls("startbutton"),indexstatusbar.setStatus({text:"Ready",iconCls:"x-status-valid"}),c.toggle(!1)):(c.setIconCls("pausebutton"),indexstatusbar.setStatus({text:"",iconCls:"timerrunning"}),c.toggle(!0),timerisrunning=!0,refreshTab(b),a.start(1E3*d))}
function getCurrentTime(){var a=new Date,c=a.getHours(),b=a.getMinutes(),a=a.getSeconds();10>c&&(c="0"+c.toString());10>b&&(b="0"+b.toString());10>a&&(a="0"+a.toString());return c+":"+b+":"+a}
function getCurrentDateTime(){var a=new Date,c=a.getFullYear(),b=a.getMonth()+1,d=a.getDate(),e=a.getHours(),f=a.getMinutes(),a=a.getSeconds();10>b&&(b="0"+b.toString());10>d&&(d="0"+d.toString());10>e&&(e="0"+e.toString());10>f&&(f="0"+f.toString());10>a&&(a="0"+a.toString());return c+"/"+b+"/"+d+" "+e+":"+f+":"+a}
function loadLKB(a,c,b,d){a=Ext.create("Ext.panel.Panel",{renderTo:c,id:"KBP"+c,layout:"absolute",autoScroll:!0,height:mainPanel.getHeight()-mainPanel.getTabBar().getHeight()-indexstatusbar.getHeight(),border:!1,bodyBorder:!1,bodyStyle:"background : "+d+";",loader:{url:"showlkb.do",params:{DCITag:a,funcid:c}},renderer:function(a,b,c,d,k,l){}});null!=b&&""!=b&&(b=Ext.create("Ext.Img",{src:b}),a.add(b));a.loader.load({renderer:"component"})};
