/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-01-14 05:42:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Customer.Funcs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class IndKanBan02420302_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Customer/Funcs/./../../../dcitag/dcitag.tld", Long.valueOf(1452650348276L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\">\r\n");
      out.write("<title>");
      if (_jspx_meth_dcitag_005freqParam_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"./../../extjs/resources/css/ext-all.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./../../dcicss/dcicss.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"./../../extjs/js/ext-all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./../../dcijs/dci-all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      if (_jspx_meth_dcitag_005fextLangFile_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" charset=\"UTF-8\">\r\n");
      out.write("var test;\r\n");
      out.write("\tpagekey = '");
      if (_jspx_meth_dcitag_005freqAttr_005f0(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\tglobeuid = '");
      if (_jspx_meth_dcitag_005freqAttr_005f1(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\tfunction loadJS(file) {\r\n");
      out.write("\t    var jsFile = document.createElement('script');\r\n");
      out.write("\t    jsFile.type = 'text/javascript';\r\n");
      out.write("\t    jsFile.src = file;\r\n");
      out.write("\t    test=document.body;\r\n");
      out.write("\t    document.body.appendChild(jsFile);\r\n");
      out.write("\t}\r\n");
      out.write("\tthis.dcistore.setUid(globeuid);\r\n");
      out.write("\tthis.dcistore.load(function(records) {\r\n");
      out.write("\t\tif (records != null && records.length == 1) {\r\n");
      out.write("\t\t\tvar postvalue = records[0].get('dcitagValue');\r\n");
      out.write("\t\t\tExt.Ajax.request({\r\n");
      out.write("\t\t\t\tmethod : 'POST',\r\n");
      out.write("\t\t\t\turl : './../../EKB/OpenLink/IndKanBan.dsc',\r\n");
      out.write("\t\t\t\tparams : {\r\n");
      out.write("\t\t\t\t\tDCITag : postvalue,\r\n");
      out.write("\t\t\t\t\tuid : globeuid,\r\n");
      out.write("\t\t\t\t\taction : 'getparams',\r\n");
      out.write("\t\t\t\t\tpagekey : pagekey\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t\t\t// console.log(response.responseText);\r\n");
      out.write("\t\t\t\t\tif (response.responseText.indexOf(\"@dcifiltererrtag@$\") != -1) {\r\n");
      out.write("\t\t\t\t\t\tvar result = response.responseText.split('$');\r\n");
      out.write("\t\t\t\t\t\tif (result.length >= 2) {\r\n");
      out.write("\t\t\t\t\t\t\tvar resultdata = Ext.JSON.decode(result[1]);\r\n");
      out.write("\t\t\t\t\t\t\tExt.Msg.alert(langs.errmsg, resultdata.msg, function() {\r\n");
      out.write("\t\t\t\t\t\t\t\tiserror = true;\r\n");
      out.write("\t\t\t\t\t\t\t\tlogout(postvalue, globeuid);\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.location = resultdata.result;\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tvar result = Ext.JSON.decode(response.responseText);\r\n");
      out.write("\t\t\t\t\t\tif (result.success == true) {\r\n");
      out.write("\t\t\t\t\t\t\tif(result.params.func_id.charAt(0)=='J'&&result.params.func_id.length==4){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tloadJS('./../../Customer/js/C02420302/IndKanBan02420302.js');\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tloadJS('./../../FuncViews/js/IndKanBan.js');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tExt.Msg.alert(langs.errmsg, langs.kanban_not_exist);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"indkbPage\" class=\"indpage_div\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_dcitag_005freqParam_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dcitag:reqParam
    com.dci.jweb.DCITags.Request.getReqParameter _jspx_th_dcitag_005freqParam_005f0 = (new com.dci.jweb.DCITags.Request.getReqParameter());
    _jsp_instancemanager.newInstance(_jspx_th_dcitag_005freqParam_005f0);
    _jspx_th_dcitag_005freqParam_005f0.setJspContext(_jspx_page_context);
    // /Customer/Funcs/IndKanBan02420302.jsp(9,7) name = paramName type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_dcitag_005freqParam_005f0.setParamName("func_name");
    _jspx_th_dcitag_005freqParam_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_dcitag_005freqParam_005f0);
    return false;
  }

  private boolean _jspx_meth_dcitag_005fextLangFile_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dcitag:extLangFile
    com.dsc.dci.jweb.aptags.getExtLangFilePath _jspx_th_dcitag_005fextLangFile_005f0 = (new com.dsc.dci.jweb.aptags.getExtLangFilePath());
    _jsp_instancemanager.newInstance(_jspx_th_dcitag_005fextLangFile_005f0);
    _jspx_th_dcitag_005fextLangFile_005f0.setJspContext(_jspx_page_context);
    // /Customer/Funcs/IndKanBan02420302.jsp(16,6) name = langDirPath type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_dcitag_005fextLangFile_005f0.setLangDirPath("./../../extjs/js");
    // /Customer/Funcs/IndKanBan02420302.jsp(16,6) name = useType type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_dcitag_005fextLangFile_005f0.setUseType("2");
    _jspx_th_dcitag_005fextLangFile_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_dcitag_005fextLangFile_005f0);
    return false;
  }

  private boolean _jspx_meth_dcitag_005freqAttr_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dcitag:reqAttr
    com.dci.jweb.DCITags.Request.getReqAttribut _jspx_th_dcitag_005freqAttr_005f0 = (new com.dci.jweb.DCITags.Request.getReqAttribut());
    _jsp_instancemanager.newInstance(_jspx_th_dcitag_005freqAttr_005f0);
    _jspx_th_dcitag_005freqAttr_005f0.setJspContext(_jspx_page_context);
    // /Customer/Funcs/IndKanBan02420302.jsp(19,12) name = attrName type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_dcitag_005freqAttr_005f0.setAttrName("pagekey");
    _jspx_th_dcitag_005freqAttr_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_dcitag_005freqAttr_005f0);
    return false;
  }

  private boolean _jspx_meth_dcitag_005freqAttr_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dcitag:reqAttr
    com.dci.jweb.DCITags.Request.getReqAttribut _jspx_th_dcitag_005freqAttr_005f1 = (new com.dci.jweb.DCITags.Request.getReqAttribut());
    _jsp_instancemanager.newInstance(_jspx_th_dcitag_005freqAttr_005f1);
    _jspx_th_dcitag_005freqAttr_005f1.setJspContext(_jspx_page_context);
    // /Customer/Funcs/IndKanBan02420302.jsp(20,13) name = attrName type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_dcitag_005freqAttr_005f1.setAttrName("uid");
    _jspx_th_dcitag_005freqAttr_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_dcitag_005freqAttr_005f1);
    return false;
  }
}
