function showPage(e){Ext.create("DCI.Customer.ComboBox",{fieldLabel:"選擇序號",name:"serial_number",x:0,y:10});var g=Ext.create("Ext.panel.Panel",{renderTo:"RegSerialForm",frame:!0,width:"80%",height:500,layout:{type:"vbox",align:"center"},bodyPadding:3,items:[Ext.create("Ext.form.Panel",{title:"step 1",flex:2,frame:!0,layout:"absolute",width:"100%",bodyPadding:5,waitMsgTarget:!0,method:"POST",defaults:{xtype:"textfield"},fieldDefaults:{labelAlign:"right",labelWidth:60,msgTarget:"side"},items:[{fieldLabel:"序號",
emptyText:"",name:"serial_number",width:350,allowBlank:!1,x:0,y:10},{xtype:"button",cls:"savebutton",width:30,height:30,x:350,y:10,handler:function(){var a=this.up("panel"),c=a.up("panel");a.isValid()&&a.getForm().submit({url:"../../Configs/RegSerial.dsc",waitMsg:"資料儲存中...",params:{DCITag:e,action:"save_serial"},failure:function(a,b){Ext.Msg.alert("儲存失敗",b.result.errorMessage)},success:function(d,b){c.datareload();if(b.result.success){var e="儲存成功";b.result.regstatus||(e+=";序號已過期");Ext.Msg.alert("儲存成功",
e,function(){a.items.get(0).setValue("");a.items.get(0).clearInvalid()})}else Ext.Msg.alert("儲存失敗",b.result.errorMessage,function(){a.items.get(0).markInvalid(b.result.errorMessage)})}})}}]}),Ext.create("Ext.form.Panel",{title:"step 2",flex:3,frame:!0,layout:"absolute",width:"100%",bodyPadding:5,waitMsgTarget:!0,method:"POST",defaults:{xtype:"textfield"},fieldDefaults:{labelAlign:"right",labelWidth:60,msgTarget:"side"},items:[Ext.create("DCI.Customer.ComboBox",{fieldLabel:"選擇序號",name:"serial_number",
width:350,allowBlank:!1,x:0,y:10}),{fieldLabel:"機碼",emptyText:"",width:350,name:"mkey",readOnly:!0,allowBlank:!1,x:0,y:40},{fieldLabel:"執行碼",emptyText:"",name:"execute_code",width:350,allowBlank:!1,x:0,y:70},{xtype:"button",cls:"savebutton",width:30,height:30,x:350,y:10,handler:function(){var a=this.up("panel"),c=a.up("panel");a.isValid()&&a.getForm().submit({url:"../../Configs/RegSerial.dsc",waitMsg:"資料儲存中...",params:{DCITag:e,action:"save_execute"},failure:function(a,b){Ext.Msg.alert("授權結果","授權失敗<br/>"+
b.result.errorMessage)},success:function(d,b){c.datareload();b.result.success?Ext.Msg.alert("授權結果",b.result.errorMessage,function(){b.result.regstatus?(a.items.get(0).setValue(""),a.items.get(2).setValue(""),a.items.get(0).clearInvalid(),a.items.get(2).clearInvalid()):(a.items.get(0).markInvalid(b.result.errorMessage),a.items.get(2).markInvalid(b.result.errorMessage))}):Ext.Msg.alert("授權結果","授權失敗<br/>"+b.result.errorMessage)}})}}]}),{xtype:"grid",title:"已安裝序號",flex:5,border:0,width:"100%",stripeRows:!0,
autoScroll:!0,loadMask:!0,enableTextSelection:!0,viewConfig:{forceFit:!1,autoLoad:!1},columns:[{text:"已安裝序號",dataIndex:"display_serial",width:250},{text:"模組",dataIndex:"module_name",width:80,renderer:function(a){return a}},{text:"人數",dataIndex:"user_qty",width:50},{text:"使用期限",dataIndex:"display_expired_date",width:90,renderer:function(a){return"99999999"==a?"永久":a}},{text:"序號用途</br>(正式/借貨)",dataIndex:"area",width:80,renderer:function(a){return"0123456789"==a?"借貨":"正式"}},{text:"是否註冊執行碼",dataIndex:"isReg",
width:100,renderer:function(a){return"1"==a?"N":"Y"}},{text:"授權狀態",dataIndex:"status",width:80,renderer:function(a){return"A"==a?"授權成功":"B"==a?"過期":"C"==a?"尚未授權":"D"==a?"授權失敗":""}}],store:{fields:"display_serial module_id user_qty area display_expired_date isReg status module_name".split(" "),autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}}}],setInitData:function(a){var c=this.items.get(1).items.get(0),d=this.items.get(1).items.get(1),b=this.items.get(2);null!=c&&c.getStore().loadData(a.get("serials"));
null!=d&&d.setValue(a.get("mkey"));null!=b&&b.getStore().loadData(a.get("regs"))},datareload:function(){var a=this.items.get(1).items.get(0),c=this.items.get(2);f.load(function(d){0<d.length&&(null!=a&&a.getStore().loadData(d[0].get("serials")),null!=c&&c.getStore().loadData(d[0].get("regs")))})}}),f=Ext.create("Ext.data.Store",{autoLoad:!1,fields:["regs","serials","mkey"],proxy:{type:"ajax",url:"../../Configs/RegSerial.dsc",actionMethods:{read:"POST"},reader:{type:"json"},extraParams:{DCITag:e,action:"init"}}});
f.load(function(a){0<a.length&&g.setInitData(a[0])})};
