var tlang=[],slang=[],lang=null;tlang.dbtype="資料庫類型";slang.dbtype="数据库类型";tlang.langType="預設語言";slang.langType="默认语言";tlang.localIP="主機IP";slang.localIP="主机IP";tlang.dbaddr="資料庫位址";slang.dbaddr="数据库地址";tlang.dbport="資料庫連接埠";slang.dbport="数据库端口";tlang.dbname="資料庫名稱";slang.dbname="数据库名称";tlang.userName="資料庫登入名稱";slang.userName="数据库登入名称";tlang.password="資料庫登入密碼";slang.password="数据库登入密码";tlang.guardIP="安控服務IP";slang.guardIP="安控服务IP";tlang.guardPort="安控服務連接埠";slang.guardPort="安控服务端口";
tlang.officialUrl="正式區URL";slang.officialUrl="正式区URL";tlang.goreg="進行授權";slang.goreg="进行授权";tlang.save="儲存";slang.save="储存";tlang.savesuccess="儲存成功";slang.savesuccess="储存成功";tlang.savefail="儲存失敗";slang.savefail="储存失败";tlang.saving="資料儲存中...";slang.saving="数据储存中...";tlang.loading="資料載入中...";slang.loading="数据加载中...";
var lang=tlang,combodata=Ext.create("Ext.data.Store",{fields:["display","value"],data:[{display:"SQL Server",value:"SqlServer"},{display:"Oracle",value:"Oracle"}]}),langcombodata=Ext.create("Ext.data.Store",{fields:["display","value"],data:[{display:"繁體中文",value:"CHT"},{display:"简体中文",value:"CHS"}]});
function showconfig(e){var k=Ext.create("Ext.data.Store",{autoLoad:!1,fields:["ips"],proxy:{type:"ajax",url:"../../Configs/SysDBConfig.dsc",actionMethods:{read:"POST"},reader:{type:"json"},extraParams:{DCITag:e,action:"getAllIP"}}}),f=Ext.create("Ext.form.field.ComboBox",{fieldLabel:"資料庫類型",store:combodata,name:"DBType",id:"dbtype",displayField:"display",valueField:"value",typeAhead:!0,editable:!1,queryMode:"local",forceSelection:!0,listeners:{change:function(a,c,b,d){a=this.up();null!=a&&(a=a.items.get(1),
"Oracle"==c?a.setValue(1521):a.setValue(1433))}}}),g=Ext.create("Ext.form.field.ComboBox",{fieldLabel:"預設語言",store:langcombodata,name:"LangType",id:"langType",displayField:"display",valueField:"value",typeAhead:!0,editable:!1,queryMode:"local",forceSelection:!0,listeners:{change:function(a,c,l,d){lang="CHS"==c?slang:tlang;for(c=0;c<b.items.get(0).items.length;c++)a=b.items.get(0).items.get(c),a.setFieldLabel(lang[a.id]);for(c=0;c<b.items.get(1).items.length;c++)a=b.items.get(1).items.get(c),a.setFieldLabel(lang[a.id]);
b.down("#regbtn").setText(lang.goreg);b.down("#savebtn").setText(lang.save)}}}),h=Ext.create("Ext.form.ComboBox",{fieldLabel:"LocalIP",name:"LocalIP",id:"localIP",allowBlank:!1,displayField:"display",valueField:"value",typeAhead:!0,editable:!1,queryMode:"local",matchFieldWidth:!1,multiSelect:!1,forceSelection:!0,store:{fields:["display","value"],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}},width:280}),b=new Ext.form.Panel({renderTo:"ConfigForm",frame:!0,title:"KanBan Config Setting",width:340,
bodyPadding:5,waitMsgTarget:!0,method:"POST",defaults:{xtype:"textfield"},fieldDefaults:{labelAlign:"right",labelWidth:100,msgTarget:"side"},items:[{xtype:"fieldset",title:"System Information",defaultType:"textfield",defaults:{width:280},items:[{fieldLabel:"資料庫位址",emptyText:"",id:"dbaddr",name:"DBAddr",allowBlank:!1},{xtype:"numberfield",fieldLabel:"資料庫連接埠",emptyText:"",id:"dbport",name:"DBPort",allowBlank:!1,allowDecimals:!1,maxValue:25536,minValue:0,hideTrigger:!0,keyNavEnabled:!1,mouseWheelEnabled:!1},
{fieldLabel:"資料庫名稱",id:"dbname",name:"DBName",allowBlank:!1},{fieldLabel:"資料庫登入名稱",id:"userName",name:"UserName",allowBlank:!1},{fieldLabel:"資料庫登入密碼",inputType:"password",id:"password",name:"Password",allowBlank:!1},f,g]},{xtype:"fieldset",title:"Guard Service Information",hidden:!0,items:[h,{xtype:"textfield",fieldLabel:"Guard Server IP",name:"GuardIP",id:"guardIP",allowBlank:!1,width:280},{fieldLabel:"Port",name:"GuardPort",id:"guardPort",xtype:"numberfield",width:280,allowBlank:!1,allowDecimals:!1,
maxValue:25535,minValue:0,hideTrigger:!0,keyNavEnabled:!1,mouseWheelEnabled:!1}]},{xtype:"fieldset",title:"Database Connection Pool Information",hidden:!0,defaultType:"numberfield",defaults:{width:280,allowBlank:!1,allowDecimals:!1,maxValue:999999,minValue:0,hideTrigger:!0,keyNavEnabled:!1,mouseWheelEnabled:!1,allowBlank:!1},items:[{fieldLabel:"最大連接數量",name:"maxActive"},{fieldLabel:"最大等待數量",name:"maxWait"},{fieldLabel:"最大閒置數量",name:"maxIdle"},{fieldLabel:"最小閒置數量",name:"minIdle"}]},{xtype:"hiddenfield",
value:"save",id:"action",name:"action"},{xtype:"fieldset",title:"Test Area Information",hidden:!0,items:[{xtype:"textfield",fieldLabel:"正式區URL",name:"OfficialUrl",id:"officialUrl",allowBlank:!1,width:280}]}],buttons:[{text:"進行授權",itemId:"regbtn",handler:function(){window.location="./../../FuncViews/Configs/RegSerial.jsp"}},{text:"儲存",itemId:"savebtn",checkSession:!1,disabled:!0,formBind:!0,handler:function(){this.up("form").getForm().submit({url:"../../Configs/SysDBConfig.dsc",waitMsg:lang.saving,
timeout:18E4,params:{confdata:Ext.encode(this.up("form").getForm().getValues()),DCITag:e},failure:function(a,c){Ext.Msg.alert(lang.savefail,c.result.errorMessage)},success:function(a,c){c.result.success?Ext.Msg.alert(lang.savesuccess,lang.savesuccess):Ext.Msg.alert(lang.savefail,c.result.errorMessage)}})}}]});b.setLoading(!0);k.load(function(a){0<a.length?(h.getStore().loadData(a[0].get("ips")),b.setLoading(!1),b.getForm().load({url:"../../Configs/SysDBConfig.dsc",waitMsg:lang.loading,params:{DCITag:e},
failure:function(a,b){Ext.Msg.alert("Load fail",b.result.errorMessage)},success:function(a,e){null==f.getValue()&&f.setValue(combodata.getAt(0).get("value"));null==g.getValue()&&g.setValue(langcombodata.getAt(0).get("value"));var d=Ext.JSON.decode(e.response.responseText);b.items.get(1).setVisible(d.isvm);b.items.get(1).items.get(0).allowBlank=!d.isvm;b.items.get(1).items.get(1).allowBlank=!d.isvm;b.items.get(4).setVisible(d.isTestArea);b.items.get(4).items.get(0).allowBlank=!d.isTestArea}})):b.setLoading(!1)})}
;
