function openIE(){(new ActiveXObject("WScript.Shell")).Exec("iexplore.exe -nomerge "+document.URL)}function isIE(a){var c=document.createElement("b");c.innerHTML="\x3c!--[if IE "+a+"]><i></i><![endif]--\x3e";return 1===c.getElementsByTagName("i").length}function isRightVersionIE(){return isIE(5)?!1:isIE(6)?!1:isIE(7)?!1:isIE(8)?!1:!0}var langs,deflang,urllang="",keys="loginforme01 no_user_selected errmsg online_num lic_limit used_lic_num login reset user_id user_pwd lang_type login_ip use_lic close kill user_list please_enter_pwd enter_pwd_title system_error wrong_ie_ver".split(" ");
Ext.onReady(function(){var a=location.href;if(-1!=a.indexOf("?"))for(var a=a.substring(a.indexOf("?")+1).split("&"),c=0;c<a.length;c++)a[c]=a[c].split("="),"ltp"==a[c][0]&&(urllang=a[c][1]);this.loginstore.setLoginMultiLangKeys(keys,urllang);this.loginstore.load(function(a){if(null!=a&&1==a.length){langs=buildMultiLangObjct(keys,a[0].get("langValues"));"Microsoft Internet Explorer"==navigator.appName&&!isRightVersionIE()&&(alert(langs.wrong_ie_ver),window.opener=null,window.open("","_self"),window.close());
this.ccode=a[0].get("frowardTagValue");var c=a[0].get("frowardTagValue"),d=a[0].get("dcitagValue"),f=document.getElementById("checkcode"),g=document.getElementById("DCITag"),h=document.getElementById("action");f.value=c;g.value=d;h.value="login";deflang=a[0].get("defLangType");document.getElementById("labelver").innerHTML=a[0].get("currVersion");null==urllang||""==urllang?(document.getElementById("langtp").value=deflang,changeBGImage(deflang)):(document.getElementById("langtp").value=urllang,changeBGImage(urllang))}})});
function changeBGImage(a){"CHT"==a?document.getElementById("loginmain").style.backgroundImage="url(images/background/KanBan_login_TC.jpg)":document.getElementById("loginmain").style.backgroundImage="url(images/background/KanBan_login_SC.jpg)"}function formCheck(){var a=document.getElementById("uid");return null==a.value||0==a.value.length?(alert(langs.loginforme01),!1):!0}
function resetForm(){var a=document.getElementById("uid"),c=document.getElementById("pwd"),b=document.getElementById("langtp");a.value="";c.value="";b.value=deflang;changeBGImage(b.value)}
function changeLang(){var a=document.getElementById("langtp");this.loginstore.setLoginMultiLangKeys(keys,a.value);this.loginstore.load(function(c){null!=c&&1==c.length&&(langs=buildMultiLangObjct(keys,c[0].get("langValues")),document.getElementById("labelid").innerHTML=langs.user_id,document.getElementById("labelpwd").innerHTML=langs.user_pwd,document.getElementById("labeltp").innerHTML=langs.lang_type,document.getElementById("userlistbtn").value=langs.user_list,document.getElementById("resetbtn").value=
langs.reset,document.getElementById("submit").value=langs.login,changeBGImage(a.value))})}
function showUserList(){Ext.onReady(function(){var a=Ext.create("Ext.window.Window",{layout:"border",title:langs.user_list,closeAction:"hide",height:300,width:520,minHeight:300,minWidth:520,modal:!0,plain:!0,items:[{xtype:"panel",region:"north",layout:"absolute",height:30,items:[{xtype:"button",text:langs.kill,x:0,y:3,width:90,handler:function(){var a=this.up("panel").up("window"),b=a.items.get(1);null==b.getSelectionModel().getSelection()||null==b.getSelectionModel().getSelection()[0]?Ext.Msg.alert(langs.errmsg,
langs.no_user_selected):Ext.MessageBox.prompt(langs.enter_pwd_title,langs.please_enter_pwd,function(e,d){"ok"==e&&Ext.Ajax.request({method:"POST",url:"./LoginInfo.dsc",params:{DCITag:document.getElementById("DCITag").value,action:"removeUser",user_id:b.getSelectionModel().getSelection()[0].data.user_id,ip_addr:b.getSelectionModel().getSelection()[0].data.ip_addr,pwd:d,langtp:document.getElementById("langtp").value},success:function(b){b=Ext.JSON.decode(b.responseText);b.success?a.loadDatas():Ext.MessageBox.alert(langs.errmsg,
b.errorMessage)},failure:function(a,c){Ext.MessageBox.alert(langs.errmsg,langs.system_error)}})}).textField.inputEl.dom.type="password"}},Ext.create("DCI.Customer.TextField",{fieldLabel:langs.online_num,labelWidth:60,width:100,emptyText:"0",readOnly:!0,fieldStyle:"text-align: right;",x:100,y:3}),Ext.create("DCI.Customer.TextField",{fieldLabel:langs.used_lic_num,labelWidth:90,width:130,emptyText:"0",readOnly:!0,fieldStyle:"text-align: right;",x:215,y:3}),Ext.create("DCI.Customer.TextField",{fieldLabel:langs.lic_limit,
labelWidth:90,width:130,emptyText:"0",readOnly:!0,fieldStyle:"text-align: right;",x:355,y:3})]},{xtype:"grid",region:"center",stripeRows:!0,autoScroll:!0,loadMask:!0,allowDeselect:!0,selModel:{allowDeselect:!0},enableTextSelection:!0,viewConfig:{forceFit:!1,autoLoad:!1},columns:[{dataIndex:"seq",width:100},{text:langs.user_id,dataIndex:"user_id",width:150},{text:langs.login_ip,dataIndex:"ip_addr_d",width:100},Ext.create("DCI.Customer.CheckColumn",{text:langs.use_lic,dataIndex:"use_lic",showOnly:!0,
width:100})],store:Ext.create("Ext.data.Store",{autoLoad:!1,fields:["seq","user_id","ip_addr","ip_addr_d","use_lic"],proxy:{type:"memory",reader:{type:"json"}}})}],buttons:[{xtype:"button",text:langs.close,handler:function(){this.up("window").close()}}],loadDatas:function(){var a=this;Ext.create("Ext.data.Store",{autoLoad:!1,fields:["griduser","head"],proxy:{type:"ajax",url:"./LoginInfo.dsc",actionMethods:{read:"POST"},reader:{type:"json"},extraParams:{DCITag:document.getElementById("DCITag").value,
action:"userlist"}}}).load(function(b){0<b.length&&(a.items.get(1).getStore().loadData(b[0].get("griduser")),null!=b[0].get("head")&&(a.items.get(0).items.get(1).setValue(b[0].get("head").onlineUser),a.items.get(0).items.get(2).setValue(b[0].get("head").usedLic),a.items.get(0).items.get(3).setValue(b[0].get("head").licLimit)))})}});a.loadDatas();a.show()})};
