var pagekey,globeuid;function createAJAX(){if(window.ActiveXObject)try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(m){try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(e){return null}}else return window.XMLHttpRequest?new XMLHttpRequest:null}
function logout(m,e){if("Firefox"==navigator.userAgent.match("Firefox")){var k=new XMLHttpRequest;k&&(k.open("GET","/KanBan/Login.dsc?action=logout&uid="+e+"&DCITag="+m,!1),k.send(""))}else"Microsoft Internet Explorer"==navigator.appName?window.navigate("./../../Login.dsc?action=logout&uid="+e+"&DCITag="+m):Ext.Ajax.request({method:"POST",url:"./../../Login.dsc",params:{DCITag:m,uid:e,action:"logout"}})}
function updatePanelOpen(m,e,k,s,d){Ext.Ajax.request({method:"POST",url:"../../Funcs/EKB/KanBan.dsc",params:{DCITag:e,uid:k,action:"updatePanelOpen",params_value:d,sql_id:m.func_id},failure:function(d,k){Ext.Msg.alert(s.save_result_title,s.save_fail+" :</br>"+k.result.errorMessage)}})}function removeAllStyle(m){for(var e=0;null!=document.getElementById(m);){Ext.util.CSS.removeStyleSheet(m);if(10<=e)break;e++}}
function setLightSize(m,e,k){k=parseInt(k);k=28>=k?16:k-12;for(var s=e.getView().getHeaderCt().getGridColumns(),d=0;d<s.length;d++)if(void 0!=s[d].xtype&&"dcilightcolumn"==s[d].xtype){s[d].rowHeight=k;for(var p=0;p<e.getStore().getCount();p++)document.getElementById("light"+m+p+";"+d).style.height=k+"px",document.getElementById("light"+m+p+";"+d).style.width=k+"px"}}
function changeKanbanGrid(m,e,k,s){try{var d=null,p=null;"FS"==k?(d="font-size",p=m+"pt",Ext.util.CSS.updateRule("."+e+" .x-progress-text",d,m-2+"pt")):"FC"==k?(d="color",p="#"+m):"BC"==k?(d="background-color",p="#"+m):"RH"==k?(d="height",p=m+"px",Ext.util.CSS.updateRule("."+e+" .x-progress-default",d,m-8+"px"),Ext.util.CSS.updateRule("."+e+" .x-progress-text","line-height",m-8+"px"),setLightSize(e.substring(0,e.length-4),s,m)):"BcEven"==k&&(d="background-color",p="#"+m);null!=d&&("BcEven"!=k&&Ext.util.CSS.updateRule("."+
e+" .x-grid-row .x-grid-cell",d,p),"BC"!=k&&Ext.util.CSS.updateRule("."+e+" .x-grid-row-alt .x-grid-cell",d,p),"background-color"!=d&&"height"!=d&&Ext.util.CSS.updateRule("."+e+" .x-column-header",d,p))}catch(F){window.console&&console.log(F.message)}}
function filterComboData(m,e){var k=null;return k="NUM"==m||"DATE"==m?[{label:e.bigger,value:">"},{label:e.bigger_equal,value:">="},{label:e.smaller,value:"<"},{label:e.smaller_equal,value:"<="},{label:e.equal,value:"="},{label:e.not_equal,value:"<>"}]:"LIGHT"==m||"MAPPING"==m?[{label:e.equal,value:"="},{label:e.not_equal,value:"<>"}]:[{label:e.start_with,value:"startwith"},{label:e.end_with,value:"endwith"},{label:e.bigger,value:">"},{label:e.bigger_equal,value:">="},{label:e.smaller,value:"<"},
{label:e.smaller_equal,value:"<="},{label:e.equal,value:"="},{label:e.not_equal,value:"<>"},{label:e.like,value:"like"},{label:e.not_like,value:"notlike"}]}
Ext.onReady(function(){function m(k,e,d,p){var m=!1,w=!1,E=new Ext.util.TaskRunner,n=k.func_id+"grid",y=Ext.create("Ext.data.Store",{autoLoad:!1,fields:[],proxy:{type:"ajax",timeout:3E5,url:"./../../Funcs/EKB/KanBan.dsc",actionMethods:{read:"POST"},reader:{root:"items",totalProperty:"total"},extraParams:{DCITag:e,uid:p,action:"query",page:1,pagesize:20,filter:"",sort:"",sql_id:k.func_id,conn_id:k.conn_id},listeners:{exception:function(a,b,c,f){if(-1!=b.responseText.indexOf("@dcifiltererrtag@")){if(a=
b.responseText.split("$"),2<=a.length){var g=Ext.JSON.decode(a[1]);Ext.Msg.alert("error",g.msg,function(){iserror=!0;window.location=g.result})}}else h&&null!=h?Ext.Msg.alert(d.errmsg,b.responseText,function(){h.setLoading(!1)}):Ext.Msg.alert(d.errmsg,b.responseText)}}},pageSize:20,gridreload:function(a,b){var c=a.items.get(0),f=a.items.get(1),g="",d="";if(null==b||0==b.length){var l=c.condiParams.condi_col,e=c.condiParams.condi_type,A=c.condiParams.condi_value;null!=l&&""!=l&&(g=" and "+l+" ",g=
"startwith"==e?g+("like '"+A+"%' "):"endwith"==e?g+("like '%"+A+"' "):"like"==e?g+("like '%"+A+"%' "):"notlike"==e?g+("not like '%"+A+"%' "):g+(e+" '"+A+"' "))}else g=b;null!=f.displayParams.sort_col&&""!=f.displayParams.sort_col&&(d=f.displayParams.sort_col+" "+f.displayParams.sort_type);this.getProxy().extraParams.hasOwnProperty("page")&&(this.currentPage=this.getProxy().extraParams.page=1);this.getProxy().extraParams.hasOwnProperty("pagesize")&&(this.pageSize=this.getProxy().extraParams.pagesize=
f.sortParams.page_size);this.getProxy().extraParams.hasOwnProperty("filter")&&(null!=k.relation_filter&&0<k.relation_filter.length?this.getProxy().extraParams.filter=k.relation_filter:this.getProxy().extraParams.filter=g);this.getProxy().extraParams.hasOwnProperty("sort")&&(this.getProxy().extraParams.sort=d);this.load();null!=c.targetGrid&&c.targetGrid.getSelectionModel().deselectAll()}}),r=Ext.create("Ext.panel.Panel",{region:"north",height:30,width:"100%",border:2,title:"",dock:"top",dataTask:null,
scrollTask:null,marqueeUrl:"./../../Funcs/EKB/KanBan.dsc",html:"",startMarquee:function(a,b,c){function f(b){null!=l&&l.load(function(g){if(0<g.length){var f="";if("1"==c){for(var d=0;d<g.length;d++)f=0==d?'<div style="font-size:22px;"><Marquee height="'+a.height+'" scrollamount="3" onmouseover="this.stop()" onmouseout="this.start()">'+g[d].get("message"):f+("                              "+g[d].get("message")),d==g.length-1&&(f+="</div></Marquee>");a.update(f)}else{null!=a.scrollTask&&(a.scrollTask.stop(),
a.body.dom.scrollTop=0);for(var l="",d=0;d<g.length;d++)0==d?(l='<div style="font-size:22px;text-align:center;overflow:hidden;height:'+a.height+'px;">'+g[d].get("message")+"</div>",f="<div>"+l):f+='<div  style="font-size:22px;text-align:center;overflow:hidden;height:'+a.height+'px;">'+g[d].get("message")+"</div>",d==g.length-1&&(f+=l+"</div>");a.update(f);null!=a.scrollTask&&a.scrollTask.start(5E3)}b(a)}})}var g=new Ext.util.TaskRunner,d=null,l=Ext.create("Ext.data.Store",{autoLoad:!1,fields:["message"],
proxy:{type:"ajax",url:this.marqueeUrl,actionMethods:{read:"POST"},reader:{root:"marquee"},extraParams:{DCITag:e,uid:p,action:"marqueeData",sql_id:k.func_id,conn_id:k.conn_id}}}),h=g.newTask({run:function(){f(function(a){})}});this.dataTask=h;f(function(a){h.start(1E3*b);var f=0;"2"==c?(d=g.newTask({run:function(){0<l.getCount()&&(0==f&&(a.body.dom.scrollTop=0),f==l.getCount()-1?f=0:f++,a.scrollBy(0,a.height,!0))}}),a.scrollTask=d,d.start(5E3)):a.scrollTask=null})},stopScrollTask:function(){null!=
this.dataTask&&this.dataTask.stop();null!=this.scrollTask&&this.scrollTask.stop()},listeners:{el:{mouseover:function(a,b,c){null!=r&&null!=r.scrollTask&&r.scrollTask.stop()}},body:{mouseout:function(a,b,c){null!=r&&null!=r.scrollTask&&r.scrollTask.start(5E3)}}}}),q=Ext.create("Ext.window.Window",{layout:"border",title:d.toolbar_query_title,closeAction:"hide",height:300,width:520,minHeight:300,minWidth:520,modal:!0,plain:!0,condiStr:"",kanbanStore:null,headPanel:null,lightsData:null,langObj:d,items:[{xtype:"panel",
region:"north",layout:"anchor",border:0,height:70,items:[{xtype:"panel",layout:"absolute",anchor:"100% 50%",height:35,condiParams:{condi_col:"",condi_type:"",condi_value:"",dcondi_col:"",dcondi_type:"",dcondi_value:""},items:[Ext.create("DCI.Customer.ComboBox",{fieldLabel:d.condi_col,store:{fields:["label","value","col_type","config_value"],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}},labelWidth:90,width:250,x:0,y:5,listeners:{change:function(a,b,c,f){c=this.up("panel");var g=c.items.get(1),
x=a.getStore();f=c.items.get(2);for(var l=null,e=null,k=null,h=0;h<x.getCount();h++)if(b==x.getAt(h).get("value")){l=x.getAt(h).get("col_type");k=x.getAt(h).get("config_value");break}if(null!=l){g.getStore().loadData(filterComboData(l,d));g.loadDefault();if("DATE"==l)e=Ext.create("DCI.Customer.DateField",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:c,x:340,y:5,listeners:{change:function(a,b,c,g){a.parentPanel.condiParams.condi_value=Ext.Date.format(new Date(b),
"Ymd");a.parentPanel.condiParams.dcondi_value=Ext.Date.format(new Date(b),"Y/m/d")}}});else if("MAPPING"==l||"LIGHT"==l){e=Ext.create("DCI.Customer.ComboBox",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:c,x:340,y:5,listeners:{change:function(b,c,g,f){b.parentPanel.condiParams.condi_value=c;b.parentPanel.condiParams.dcondi_value=a.getRawValue()}}});if("MAPPING"==l){g=[];k=k.split(";");x=null;for(h=0;h<k.length;h++)x=k[h].split("="),null!=x&&2==x.length&&g.push({value:x[0],
label:x[1]});e.getStore().loadData(g)}else null!=c.up("panel").up("window").lightsData&&e.getStore().loadData(c.up("panel").up("window").lightsData);e.loadDefault()}else e=Ext.create("DCI.Customer.TextField",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:c,x:340,y:5,listeners:{change:function(a,b,c,g){a.parentPanel.condiParams.condi_value=b;a.parentPanel.condiParams.dcondi_value=b}}});c.remove(f.getId());c.insert(2,e)}c.condiParams.condi_col=b;c.condiParams.dcondi_col=
a.getRawValue()}}}),Ext.create("DCI.Customer.ComboBox",{fieldLabel:"",labelWidth:0,width:90,x:250,y:5,listeners:{change:function(a,b,c,f){c=this.up("panel");c.condiParams.condi_type=b;c.condiParams.dcondi_type=a.getRawValue()}}}),Ext.create("DCI.Customer.TextField",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",x:340,y:5})]},{xtype:"panel",anchor:"100% 50%",layout:"absolute",items:[{xtype:"radiogroup",fieldLabel:d.condi_relation,columns:2,vertical:!0,width:200,x:0,y:5,items:[{boxLabel:"AND",
name:"rb",inputValue:"AND",checked:!0},{boxLabel:"OR",name:"rb",inputValue:"OR"}]},{xtype:"button",text:d.add,x:200,y:5,handler:function(){var a=this.up("panel"),b=a.up("panel").items.get(0),c=a.up("panel").up("window").items.get(1).getStore(),a=a.items.get(0).getValue();null!=c&&c.add({condi_relation:a.rb,condi_col_display:b.condiParams.dcondi_col,condi_type_display:b.condiParams.dcondi_type,condi_value_display:b.condiParams.dcondi_value,condi_col:b.condiParams.condi_col,condi_type:b.condiParams.condi_type,
condi_value:b.condiParams.condi_value})}},{xtype:"button",text:d._delete,x:250,y:5,handler:function(){var a=this.up("panel").up("panel").up("window").items.get(1);a.getSelectionModel().hasSelection()&&a.getStore().remove(a.getSelectionModel().getSelection()[0])}},{xtype:"button",text:d.clear,x:300,y:5,handler:function(){var a=this.up("panel").up("panel").up("window").items.get(1).getStore();null!=a&&a.removeAll()}}]}]},{xtype:"grid",region:"center",renderer:"component",border:0,stripeRows:!0,autoScroll:!0,
loadMask:!0,hideHeaders:!0,enableTextSelection:!0,viewConfig:{forceFit:!1,autoLoad:!1},columns:[{dataIndex:"condi_relation",width:50},{dataIndex:"condi_col_display",width:150},{text:d.conn_id,dataIndex:"condi_type_display",width:100},{text:d.conn_id,dataIndex:"condi_value_display",width:200}],store:Ext.create("Ext.data.Store",{fields:"condi_relation condi_col_display condi_type_display condi_value_display condi_col condi_type condi_value".split(" "),autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}},
syncCondiString:function(a){for(var b="",c=0;c<this.getCount();c++)b+=" "+this.getAt(c).get("condi_relation")+" "+this.getAt(c).get("condi_col")+" ",b="startwith"==this.getAt(c).get("condi_type")?b+("like '"+this.getAt(c).get("condi_value")+"%' "):"endwith"==this.getAt(c).get("condi_type")?b+("like '%"+this.getAt(c).get("condi_value")+"' "):"like"==this.getAt(c).get("condi_type")?b+("like '%"+this.getAt(c).get("condi_value")+"%' "):"notlike"==this.getAt(c).get("condi_type")?b+("not like '%"+this.getAt(c).get("condi_value")+
"%' "):b+(this.getAt(c).get("condi_type")+" '"+this.getAt(c).get("condi_value")+"' ");a.condiStr=b},listeners:{datachanged:function(a,b){var c=null;null!=u&&(c=u.items.get(4),null!=c&&(0<a.getCount()?c.getEl().setStyle({borderWidth:"2px 2px 2px 2px",borderColor:"red",boderStyle:"solid"}):c.getEl().setStyle({borderWidth:"1px 1px 1px 1px",borderColor:"",boderStyle:""})))}}})}],buttons:[{xtype:"button",text:d.ok,handler:function(){var a=this.up("window"),b=a.items.get(1).getStore();null!=b&&(b.syncCondiString(a),
null!=a.kanbanStore&&a.kanbanStore.gridreload(a.headPanel,a.condiStr));a.close()}},{xtype:"button",text:d.cancel,handler:function(){this.up("window").close()}}],setComboData:function(a,b){var c=this.items.get(0).items.get(0).items.get(0),f=c.getStore();null!=f&&(f.loadData(a),null==b||""==b?c.loadDefault():c.setValue(b))},setInitData:function(a,b,c,f){var g=this.items.get(0).items.get(0).items.get(0);null==c.filter_col||""==c.filter_col?g.loadDefault():g.setValue(c.filter_col);g=this.items.get(0).items.get(0).items.get(1);
null==c.filter_condi||""==c.filter_condi?g.loadDefault():g.setValue(c.filter_condi);g=this.items.get(0).items.get(0).items.get(2);null==c.filter_value||""==c.filter_value?g.loadDefault():g.setValue(c.filter_value);this.headPanel=a;this.kanbanStore=b;null!=f&&(this.items.get(1).getStore().loadData(f),this.items.get(1).getStore().syncCondiString(q));var e=this.items.get(0).items.get(0);f=e.items.get(0).getStore();g=e.items.get(1);a=e.items.get(2);var l=null;c=b=null;if(null!=f&&0<f.getCount()&&(l=f.getAt(0).get("col_type"),
c=f.getAt(0).get("config_value"),null!=l)){g.getStore().loadData(filterComboData(l,d));g.loadDefault();if("DATE"==l)b=Ext.create("DCI.Customer.DateField",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:e,x:340,y:5,listeners:{change:function(a,b,c,g){a.parentPanel.condiParams.condi_value=Ext.Date.format(new Date(b),"Ymd");a.parentPanel.condiParams.dcondi_value=Ext.Date.format(new Date(b),"Y/m/d")}}});else if("MAPPING"==l||"LIGHT"==l){b=Ext.create("DCI.Customer.ComboBox",
{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:e,x:340,y:5,listeners:{change:function(a,b,c,g){a.parentPanel.condiParams.condi_value=b;a.parentPanel.condiParams.dcondi_value=e.items.get(2).getRawValue()}}});if("MAPPING"==l){f=[];c=c.split(";");g=null;for(l=0;l<c.length;l++)g=c[l].split("="),null!=g&&2==g.length&&f.push({value:g[0],label:g[1]});b.getStore().loadData(f)}else null!=this.lightsData&&b.getStore().loadData(this.lightsData);b.loadDefault();e.condiParams.condi_value=
b.getValue();e.condiParams.dcondi_value=b.getRawValue()}else b=Ext.create("DCI.Customer.TextField",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:e,x:340,y:5,listeners:{change:function(a,b,c,g){a.parentPanel.condiParams.condi_value=b;a.parentPanel.condiParams.dcondi_value=b}}});e.remove(a.getId());e.insert(2,b)}},getCondiValue:function(){var a=[],b=this.items.get(1).getStore();if(null!=b)for(var c=0;c<b.getCount();c++)a.push({condi_relation:b.getAt(c).get("condi_relation"),
condi_col:b.getAt(c).get("condi_col"),condi_type:b.getAt(c).get("condi_type"),condi_value:b.getAt(c).get("condi_value"),condi_col_display:b.getAt(c).get("condi_col_display"),condi_type_display:b.getAt(c).get("condi_type_display"),condi_value_display:b.getAt(c).get("condi_value_display"),seq:c});return a}}),u=Ext.create("Ext.panel.Panel",{title:"",anchor:"100% 50%",layout:"absolute",border:0,bodyStyle:{background:"#d3e1f1"},bodyPadding:0,targetGrid:null,lightsData:null,condiParams:{condi_col:"",condi_type:"",
condi_value:""},items:[Ext.create("DCI.Customer.ComboBox",{fieldLabel:d.condi_col,store:{fields:["label","value","col_type","config_value"],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}},labelWidth:90,width:250,x:0,y:8,listeners:{change:function(a,b,c,f){c=this.up("panel");var g=c.items.get(1),e=a.getStore();a=c.items.get(2);for(var l=null,h=f=null,k=0;k<e.getCount();k++)if(b==e.getAt(k).get("value")){l=e.getAt(k).get("col_type");h=e.getAt(k).get("config_value");break}if(null!=l){g.getStore().loadData(filterComboData(l,
d));g.loadDefault();if("DATE"==l)f=Ext.create("DCI.Customer.DateField",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:c,x:340,y:8,listeners:{change:function(a,b,c,g){a.parentPanel.condiParams.condi_value=Ext.Date.format(new Date(b),"Ymd")}}});else if("MAPPING"==l||"LIGHT"==l){f=Ext.create("DCI.Customer.ComboBox",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:c,x:340,y:8,listeners:{change:function(a,b,c,g){a.parentPanel.condiParams.condi_value=
b}}});if("MAPPING"==l){g=[];h=h.split(";");e=null;for(k=0;k<h.length;k++)e=h[k].split("="),null!=e&&2==e.length&&g.push({value:e[0],label:e[1]});f.getStore().loadData(g)}else f.getStore().loadData(c.lightsData);f.loadDefault()}else f=Ext.create("DCI.Customer.TextField",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:c,x:340,y:8,listeners:{change:function(a,b,c,g){a.parentPanel.condiParams.condi_value=b}}});c.remove(a.getId());c.insert(2,f)}c.condiParams.condi_col=
b}}}),Ext.create("DCI.Customer.ComboBox",{fieldLabel:"",labelWidth:0,width:90,x:250,y:8,listeners:{change:function(a,b,c,f){this.up("panel").condiParams.condi_type=b}}}),Ext.create("DCI.Customer.TextField",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",x:340,y:8}),{xtype:"button",cls:"search-toolbar",tooltip:d.search,width:30,height:30,x:500,y:3,handler:function(){var a=this.up("panel"),b=a.targetGrid.getStore();k.relation_filter="";b.gridreload(a.up("panel"),q.condiStr)}},
{xtype:"button",cls:"advsearchbutton",tooltip:d.adv_search,width:30,height:30,x:530,y:3,handler:function(){null!=q&&q.show()}},{xtype:"button",cls:"savebutton",tooltip:d.save_format,width:30,height:30,x:560,y:3,handler:function(){var a=this.up("panel"),b=this.up("panel").up("panel").items.get(1),c=this.up("panel").targetGrid.columns,f=[],g={},h=a.targetGrid;g.popup_width=null==h?200:h.getPopupWidth();for(var l in b.displayParams)g[l]=b.displayParams[l];for(a=0;a<c.length;a++)l={},l.col_id=c[a].colid,
l.col_index=c[a].getIndex(),l.col_width=c[a].width,l.col_visible=c[a].hidden?0:1,f.push(l);Ext.Ajax.request({method:"POST",url:"../../Funcs/EKB/KanBan.dsc",params:{DCITag:e,uid:p,action:"saveFormat",gridid:k.func_id,datas:Ext.encode(g),coldatas:Ext.encode(f)},success:function(a){null!=h&&h.addCusFormatIcon();b.setCss({grid_font_size:b.displayParams.fs,grid_font_color:b.displayParams.fc,grid_row_height:b.displayParams.rh,grid_row_color:b.displayParams.bc,grid_row_even_color:b.displayParams.bcEven});
Ext.Msg.alert(d.save_result_title,d.save_success)},failure:function(a,b){Ext.Msg.alert(d.save_result_title,d.save_fail+" :</br>"+b.result.errorMessage)}})}},{xtype:"button",cls:"backdefault_greenbutton",tooltip:d.load_def_format,width:30,height:30,x:590,y:3,handler:function(){var a=this.up("panel").up("panel").items.get(1);Ext.MessageBox.confirm(d.load_def_confirm_title,d.load_def_confirm_msg,function(b){"yes"==b&&Ext.Ajax.request({method:"POST",url:"../../Funcs/EKB/KanBan.dsc",params:{DCITag:e,uid:p,
action:"loadDefFormat",datas:"dodelete",gridid:k.func_id},success:function(b){a.setCss({grid_font_size:13,grid_font_color:"000000",grid_row_height:28,grid_row_color:null,grid_row_even_color:null});null!=h&&(h.rmCusFormatIcon(),h.setPopupWidth(200),null!=C&&0<C.getCount()&&C.load(function(a){h.reloadBodyGridFormat(a[0].get("cols"),y)}));Ext.Msg.alert(d.load_def_result_title,d.load_def_success)},failure:function(a,b){Ext.Msg.alert(d.load_def_result_title,d.load_def_fail+" :</br>"+b.result.errorMessage)}})})}},
{xtype:"button",cls:"save-toolbar",tooltip:d.save_condi,width:30,height:30,x:620,y:3,handler:function(){var a=this.up("panel"),b=this.up("panel").up("panel").items.get(1),c={},f=null,g;for(g in a.condiParams)c[g]=a.condiParams[g];for(g in b.sortParams)c[g]=b.sortParams[g];if(null==c.condi_col||""==c.condi_col)c.condi_type="",c.condi_value="";if(null==c.sort_col||""==c.sort_col)c.sort_type="";null!=q&&null!=q.getCondiValue()&&0<q.getCondiValue().length&&(f=Ext.encode(q.getCondiValue()));Ext.Ajax.request({method:"POST",
url:"../../Funcs/EKB/KanBan.dsc",params:{DCITag:e,uid:p,action:"saveCondi",sql_id:k.func_id,datas:Ext.encode(c),advDatas:f},success:function(b){k.relation_filter="";a.targetGrid.getStore().gridreload(a.up("panel"),q.condiStr);Ext.Msg.alert(d.save_result_title,d.save_success)},failure:function(a,b){Ext.Msg.alert(d.save_result_title,d.save_fail+" :</br>"+b.result.errorMessage)}})}},{xtype:"button",cls:"backdefault_bluebutton",tooltip:d.load_def_condi,width:30,height:30,x:650,y:3,handler:function(){var a=
this.up("panel").up("panel"),b=a.items.get(0),c=a.items.get(1);Ext.MessageBox.confirm(d.load_def_confirm_title,d.load_def_confirm_msg,function(f){"yes"==f&&Ext.Ajax.request({method:"POST",url:"../../Funcs/EKB/KanBan.dsc",params:{action:"loadDefCondi",uid:p,datas:"dodelete",DCITag:e,sql_id:k.func_id},success:function(g){g={filter_col:"",filter_condi:"",filter_value:"",sort_col:"",sort_type:"",page_size:20};b.setInitData(g);if(null!=q){var f=q.items.get(1).getStore();null!=f&&f.removeAll()}c.setInitData(g);
b.targetGrid.getStore().gridreload(a);Ext.Msg.alert(d.load_def_result_title,d.load_def_success)},failure:function(a,b){Ext.Msg.alert(d.load_def_result_title,d.load_def_fail+" :</br>"+b.result.errorMessage)}})})}}],setComboData:function(a,b){var c=this.items.get(0),f=c.getStore();a.unshift({label:d.no_query,value:"",col_type:"CHAR",config_value:""});null!=f&&(f.loadData(a),null==b||""==b?c.loadDefault():c.setValue(b));a.shift()},setInitData:function(a){var b=this.items.get(0);null==a.filter_col||""==
a.filter_col?b.loadDefault():b.setValue(a.filter_col);b=this.items.get(1);null==a.filter_condi||""==a.filter_condi?b.loadDefault():b.setValue(a.filter_condi);b=this.items.get(2);null==a.filter_value||""==a.filter_value?b.loadDefault():b.setValue(a.filter_value);b=this.up("panel");null==a.op_is_open||0==a.op_is_open.length?b.expand():"0"==a.op_is_open?b.collapse():b.expand()}}),B=Ext.create("Ext.panel.Panel",{title:"",anchor:"100% 50%",layout:"absolute",border:0,bodyStyle:{background:"#d3e1f1"},bodyPadding:0,
sortParams:{sort_col:"",sort_type:"",page_size:20},displayParams:{fs:13,fc:"000000",rh:28,bc:"FFFFFF",bcEven:"CCE4F6"},bodygrid:null,items:[Ext.create("DCI.Customer.ComboBox",{fieldLabel:d.sort_column,name:"sort_column",labelWidth:90,width:250,x:0,y:8,listeners:{change:function(a,b,c,f){this.up("panel").sortParams.sort_col=b}}}),Ext.create("DCI.Customer.ComboBox",{fieldLabel:"",labelWidth:0,width:90,store:{fields:["label","value"],data:[{label:d.asc,value:"asc"},{label:d.desc,value:"desc"}]},x:250,
y:8,listeners:{change:function(a,b,c,f){this.up("panel").sortParams.sort_type=b}}}),Ext.create("DCI.Customer.NumberBox",{fieldLabel:d.page_size,labelWidth:60,defaultvalue:20,maxValue:9999,minValue:1,width:150,x:340,y:8,listeners:{change:function(a,b,c,f){this.up("panel").sortParams.page_size=b}}}),{xtype:"button",cls:"configbutton",tooltip:d.favorties_setup,x:500,y:5,width:30,height:30,handler:function(){var a=this.up("panel").displayParams;Ext.create("Ext.window.Window",{title:d.favorties_setup,
width:500,height:300,minWidth:300,minHeight:200,layout:"fit",plain:!0,modal:!0,items:[{xtype:"panel",layout:"anchor",items:[{xtype:"slider",anchor:"80% 25%",fieldLabel:d.font_size,border:1,value:a.fs,minValue:8,maxValue:48,increment:1,plugins:new Ext.slider.Tip,listeners:{change:function(b,c,f,g){changeKanbanGrid(c,n,"FS",h);if(null!=h&&0<h.columns.length)try{var d=h.columns[0].width;h.columns[0].setWidth(d+10);h.columns[0].setWidth(d)}catch(l){window.console&&console.log(l.message)}a.fs=c},afterrender:function(a,
c){this.labelCell.dom.attributes.getNamedItem("valign").value="middle"}}},{xtype:"dcicolorpicker",fieldLabel:d.font_color,defaultColor:"000000",curColor:a.fc,width:180,listeners:{change:function(b,c,f,g){changeKanbanGrid(c,n,"FC",h);a.fc=c}}},{xtype:"slider",anchor:"80% 25%",fieldLabel:d.row_height,value:a.rh,minValue:16,maxValue:100,increment:4,plugins:new Ext.slider.Tip,listeners:{change:function(b,c,f,g){changeKanbanGrid(c,n,"RH",h);a.rh=c},afterrender:function(a,c){this.labelCell.dom.attributes.getNamedItem("valign").value=
"middle"}}},{bodyStyle:"border:0 ;",items:[{layout:"column",bodyStyle:"border:0 ;",items:[{columnWidth:0.4,bodyStyle:"border:0;",items:[{xtype:"dcicolorpicker",fieldLabel:d.bg_color,defaultColor:"FFFFFF",curColor:a.bc,width:180,listeners:{change:function(b,c,f,g){changeKanbanGrid(c,n,"BC",h);a.bc=c}}}]},{columnWidth:0.5,bodyStyle:"border:0;",items:[{xtype:"dcicolorpicker",defaultColor:"CCE4F6",curColor:a.bcEven,width:70,listeners:{change:function(b,c,f,g){changeKanbanGrid(c,n,"BcEven",h);a.bcEven=
c}}}]}]}]}]}],buttons:[{text:d.close,handler:function(){this.up(".window").close()}}]}).show()}},{xtype:"button",cls:"toexcelbutton",tooltip:d.to_excel,width:30,height:30,x:530,y:5,handler:function(){var a=this.up("panel").bodygrid;null!=a&&Ext.create("Ext.form.Panel",{standardSubmit:!0,url:"../../Funcs/EKB/KanBan.dsc",method:"POST"}).submit({target:"_blank",params:{DCITag:e,uid:p,conn_id:k.conn_id,func_id:k.func_id,action:"excel",filter:a.getStore().getProxy().extraParams.filter,sort:a.getStore().getProxy().extraParams.sort,
cols:Ext.encode(buildColObj(a.columns)),ctype:"1"}})}},{xtype:"button",cls:"tohtmlbutton",tooltip:d.to_html,width:30,height:30,x:560,y:5,handler:function(){var a=this.up("panel").bodygrid;null!=a&&Ext.create("Ext.form.Panel",{standardSubmit:!0,url:"../../Funcs/EKB/KanBan.dsc",method:"POST"}).submit({target:"_blank",params:{DCITag:e,uid:p,conn_id:k.conn_id,func_id:k.func_id,action:"html",filter:a.getStore().getProxy().extraParams.filter,sort:a.getStore().getProxy().extraParams.sort,cols:Ext.encode(buildColObj(a.columns)),
ctype:"2"}})}}],setComboData:function(a){var b=this.items.get(0),c=b.getStore();a.unshift({label:d.no_sort,value:""});null!=c&&(c.loadData(a),b.loadDefault());a.shift()},setCss:function(a){var b="",c="",f="";removeAllStyle(n);null!=a.grid_font_size&&""!=a.grid_font_size?(b+="font-size:"+a.grid_font_size+"pt;",f+="font-size:"+a.grid_font_size+"pt;",c+="font-size:"+a.grid_font_size+"pt;",this.displayParams.fs=a.grid_font_size,Ext.util.CSS.createStyleSheet("."+n+" .x-progress-text {font-size:"+(a.grid_font_size-
2)+"pt;}",n)):(b+="font-size:13pt;",f+="font-size:13pt;",c+="font-size:13pt;",this.displayParams.fs="13",Ext.util.CSS.createStyleSheet("."+n+" .x-progress-text {font-size:11pt}",n));null!=a.grid_font_color&&""!=a.grid_font_color?(b+="color:#"+a.grid_font_color+";",f+="color:#"+a.grid_font_color+";",c+="color:#"+a.grid_font_color+";",this.displayParams.fc=a.grid_font_color):(b+="color:black;",f+="color:black;",c+="color:black;",this.displayParams.fc="000000");null!=a.grid_row_height&&""!=a.grid_row_height?
(b+="height:"+a.grid_row_height+"px;",f+="height:"+a.grid_row_height+"px;",this.displayParams.rh=a.grid_row_height,Ext.util.CSS.createStyleSheet("."+n+" .x-progress-default {height:"+(a.grid_row_height-8)+"px;}",n),Ext.util.CSS.createStyleSheet("."+n+" .x-progress-text {line-height:"+(a.grid_row_height-8)+"px;}",n),setLightSize(n.substring(0,n.length-4),h,a.grid_row_height)):(b+="height:28px;",f+="height:28px;",this.displayParams.rh="28",Ext.util.CSS.createStyleSheet("."+n+" .x-progress-default {height:20px;}",
n),Ext.util.CSS.createStyleSheet("."+n+" .x-progress-text {line-height:20px;}",n),setLightSize(n.substring(0,n.length-4),h,"16"));null!=a.grid_row_color&&""!=a.grid_row_color?(b+="background-color:#"+a.grid_row_color+";",this.displayParams.bc=a.grid_row_color):(b+="background-color:withe;",this.displayParams.bc="FFFFFF");null!=a.grid_row_even_color&&""!=a.grid_row_even_color?(f+="background-color:#"+a.grid_row_even_color+";",this.displayParams.bcEven=a.grid_row_even_color):(f+="background-color:#cce4f6;",
this.displayParams.bcEven="cce4f6");Ext.util.CSS.createStyleSheet("."+n+" .x-grid-row .x-grid-cell {"+b+"}",n);Ext.util.CSS.createStyleSheet("."+n+" .x-grid-row-alt .x-grid-cell {"+f+"}",n);Ext.util.CSS.createStyleSheet("."+n+" .x-column-header {"+c+"}",n)},setInitData:function(a,b){var c=this.items.get(0);null==a.sort_col||""==a.sort_col?c.loadDefault():c.setValue(a.sort_col);c=this.items.get(1);null==a.sort_type||""==a.sort_type?c.loadDefault():c.setValue(a.sort_type);c=this.items.get(2);null!=
a.page_size&&""!=a.page_size?c.setValue(a.page_size):c.loadDefault();this.bodygrid=b}}),z=Ext.create("Ext.panel.Panel",{region:"north",height:120,collapsible:!0,title:"",header:{height:35},layout:"anchor",items:[u,B],listeners:{collapse:function(){updatePanelOpen(k,e,p,d,"0")},expand:function(){updatePanelOpen(k,e,p,d,"1")}}}),h=Ext.create("Ext.grid.Panel",{region:"center",renderer:"component",stripeRows:!0,autoScroll:!0,loadMask:!0,allowDeselect:!0,usePopup:!0,popupImgPath:"",popupImgCols:[],popupTitleCols:[],
popup_refresh_gap:600,selModel:{allowDeselect:!0},enableTextSelection:!0,viewConfig:{forceFit:!1,autoLoad:!1},store:null,bodyCls:n,componentCls:n,columns:[],sqlRelationStore:Ext.create("Ext.data.Store",{fields:["col_id","target_sql_id","target_col_id","target_sql_name"],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}}),currpage:0,totalpage:0,timer:null,dockedItems:[{xtype:"pagingtoolbar",store:null,dock:"bottom",displayInfo:!1,items:["-",{enableToggle:!0,width:50,tooltip:"",cls:"starttimerbutton",
toggleHandler:function(a,b){null!=D&&!D.globalRunning&&this.btnClick(a,b)},btnClick:function(a,b){var c=this.up("panel").timer;null!=c&&(b?c.executeTask():c.stopTask())}},"-",{xtype:"label",text:d.refresh_gap},{xtype:"label",text:"",margin:"0 0 0 10"},"-",Ext.create("DCI.Customer.Img",{src:"../../images/icons/CusGridFormat.png",width:20,height:20,hidden:!0,listeners:{afterrender:function(a){Ext.create("Ext.tip.ToolTip",{target:a.getEl(),html:d.cus_format})}}}),Ext.create("DCI.Customer.Img",{src:"../../images/button_icon/BtnCrossDatabase.png",
width:20,height:20,hidden:!0,listeners:{afterrender:function(a){Ext.create("Ext.tip.ToolTip",{target:a.getEl(),html:d.cross_db})}}})],listeners:{beforechange:function(a,b,c){this.store.getProxy().extraParams.hasOwnProperty("page")&&(null==b||0==b?this.store.getProxy().extraParams.page=1:this.store.getProxy().extraParams.page=b);this.store.load()},change:function(a,b,c){null==b||null==b.currentPage||null==b.pageCount?(this.up("panel").setCurrPage(0),this.up("panel").setTotlaPage(0)):(this.up("panel").setCurrPage(b.currentPage),
this.up("panel").setTotlaPage(b.pageCount))}}},r,{xtype:"panel",height:"100%",width:200,border:5,title:"",dock:"right",layout:"fit",collapsible:!0,collapseDirection:"right",animCollapse:!1,hidden:!1,buttonAlign:"left",resizable:!0,items:[{xtype:"panel",height:"100%",title:"",width:"100%",border:0}],header:{items:[{xtype:"button",cls:"playbutton",pressedCls:"pausebutton",width:15,height:15,enableToggle:!0,handler:function(){null!=v&&(this.pressed?(v.executeTask(),null!=h&&h.nextSelectedRow()):v.stopTask())}}]},
showPopup:function(a,b){var c=this.items.get(0),f=this.items.get(0);null!=f&&(null==a||""==a?f.setTitle(" "):f.setTitle(a),Ext.Ajax.request({method:"POST",url:"./../../PublicCtrl.dsc",params:{DCITag:e,uid:p,action:"B64Encode",str:b},success:function(a){a=Ext.JSON.decode(a.responseText);a="<img width="+c.getWidth()+" height="+c.getHeight()+' src="./../../ImageLoader.dsc?imgpath='+a.result+'"/>';c.update(a)}}))}}],listeners:{selectionchange:function(a,b,c){if(this.usePopup&&0<b.length){c=a="";for(var f=
this.dockedItems.get(3),g=0;g<this.popupImgCols.length;g++)a=0==g?b[0].get(this.popupImgCols[g]):a+("--"+b[0].get(this.popupImgCols[g]));for(g=0;g<this.popupTitleCols.length;g++)c=0==g?b[0].get(this.popupTitleCols[g]):c+("--"+b[0].get(this.popupTitleCols[g]));null!=f&&(b=this.popupImgPath.replace("\\",'"'),b=b.replace('"',"\\")+"\\",f.showPopup(c,b+a+".jpg"))}},celldblclick:function(a,b,c,f,g,d,l,e){},cellcontextmenu:function(a,b,c,f,g,d,l,h){if(null!=this.sqlRelationStore&&0<this.sqlRelationStore.getCount()){a=
Ext.create("Ext.menu.Menu",{mpanel:D.parentComp,items:[],clickEvent:function(a,b,c){var g=this;null!=g.mpanel&&Ext.Ajax.request({method:"POST",url:"./../../Funcs/EKB/KanBan.dsc",params:{action:"funcInfo",uid:p,DCITag:e,func_id:b,conn_id:k.conn_id},success:function(f){null==f.responseText||""==f.responseText||0==f.responseText.length?alert("open kanban "+b+" fail"):(f=Ext.JSON.decode(f.responseText),g.mpanel.beforeAddCheck(b,k.conn_id,{url:f.url,text:f.text,func_package:f.func_package,can_edit:f.can_edit,
filter:" and "+c+" = '"+a+"'"},!0))}})}});for(b=0;b<this.sqlRelationStore.getCount();b++)this.columns[c].dataIndex==this.sqlRelationStore.getAt(b).get("col_id")&&a.add({text:this.sqlRelationStore.getAt(b).get("target_sql_name"),currcol:this.sqlRelationStore.getAt(b).get("col_id"),cellValue:f.get(this.columns[c].dataIndex),targetsql:this.sqlRelationStore.getAt(b).get("target_sql_id"),targetcol:this.sqlRelationStore.getAt(b).get("target_col_id"),handler:function(){this.up("menu").clickEvent(this.cellValue,
this.targetsql,this.targetcol)}});0<a.items.length&&(l.stopEvent(),a.showAt(l.getXY()))}}},addCusFormatIcon:function(){this.dockedItems.items[1].items.get(17).show()},rmCusFormatIcon:function(){this.dockedItems.items[1].items.get(17).hide()},setCrossDBIcon:function(a){var b=this.dockedItems.items[1];a?b.items.get(18).show():b.items.get(18).hide()},initBodyGrid:function(a,b,c,f){this.timer=a;var g=this,d=[];Ext.create("Ext.data.Store",{autoLoad:!1,fields:["colFormats"],proxy:{type:"ajax",url:"./../../PublicCtrl.dsc",
actionMethods:{read:"POST"},reader:{type:"json"},extraParams:{DCITag:e,uid:p,action:"getGFormat",gridid:k.func_id}}}).load(function(a){if(0<a.length){var e=Ext.create("Ext.data.Store",{fields:["col_id","col_index","col_width","col_visible"],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}});e.loadData(a[0].get("colFormats"));if(0<e.getCount()){g.addCusFormatIcon();for(a=0;a<e.getCount();a++)for(var h=0;h<b.length;h++)if(b[h].colid==e.getAt(a).get("col_id")){"1"==e.getAt(a).get("col_visible")?
(b[h].hasOwnProperty("hidden"),b[h].hidden=!1,0!=e.getAt(a).get("col_width")&&(b[h].hasOwnProperty("width"),b[h].width=parseInt(e.getAt(a).get("col_width")))):(0!=e.getAt(a).get("col_width")&&(b[h].hasOwnProperty("width"),b[h].width=parseInt(e.getAt(a).get("col_width"))),b[h].hasOwnProperty("hidden"),b[h].hidden=!0);d.push(b[h]);b.splice(h,1);break}if(null!=b&&0!=b.length)for(a=0;a<b.length;a++)b[a].hidden=!0,d.push(b[a])}else d=b;if(null!=f)for(h=0;h<d.length;h++)for(a=0;a<f.length;a++)if("col"+
f[a].col_id==d[h].colid){d[h].hasOwnProperty("componentCls");d[h].componentCls="dci-realtion-column-header";break}g.reconfigure(c,d)}else{if(null!=f)for(h=0;h<b.length;h++)for(a=0;a<f.length;a++)if("col"+f[a].col_id==b[h].colid){b[h].hasOwnProperty("componentCls");b[h].componentCls="dci-realtion-column-header";break}g.reconfigure(c,b)}g.child("pagingtoolbar").bindStore(y);null!=u&&(u.targetGrid=g)});g.sqlRelationStore.loadData(f)},reloadBodyGridFormat:function(a,b){var c=this,f=[];Ext.create("Ext.data.Store",
{autoLoad:!1,fields:["colFormats"],proxy:{type:"ajax",url:"./../../PublicCtrl.dsc",actionMethods:{read:"POST"},reader:{type:"json"},extraParams:{DCITag:e,uid:p,action:"getGFormat",gridid:k.func_id}}}).load(function(g){if(0<g.length){var d=Ext.create("Ext.data.Store",{fields:["col_id","col_index","col_width","col_visible"],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}});d.loadData(g[0].get("colFormats"));if(0<d.getCount()){c.addCusFormatIcon();for(g=0;g<d.getCount();g++)for(var e=0;e<a.length;e++)if(a[e].colid==
d.getAt(g).get("col_id")){"1"==d.getAt(g).get("col_visible")?(a[e].hasOwnProperty("hidden"),a[e].hidden=!1,0!=d.getAt(g).get("col_width")&&(a[e].hasOwnProperty("width"),a[e].width=parseInt(d.getAt(g).get("col_width")))):(0!=d.getAt(g).get("col_width")&&(a[e].hasOwnProperty("width"),a[e].width=parseInt(d.getAt(g).get("col_width"))),a[e].hasOwnProperty("hidden"),a[e].hidden=!0);f.push(a[e]);a.splice(e,1);break}if(null!=a&&0!=a.length)for(g=0;g<a.length;g++)a[g].hidden=!0,f.push(a[g])}else f=a;if(null!=
c.sqlRelationStore)for(e=0;e<f.length;e++)for(g=0;g<c.sqlRelationStore.getCount();g++)if("col"+c.sqlRelationStore.getAt(g).data.col_id==f[e].colid){f[e].hasOwnProperty("componentCls");f[e].componentCls="dci-realtion-column-header";break}c.reconfigure(b,f)}else{if(null!=c.sqlRelationStore)for(e=0;e<a.length;e++)for(g=0;g<c.sqlRelationStore.getCount();g++)if("col"+c.sqlRelationStore.getAt(g).data.col_id==a[e].colid){a[e].hasOwnProperty("componentCls");a[e].componentCls="dci-realtion-column-header";
break}c.reconfigure(b,a)}c.child("pagingtoolbar").bindStore(y);null!=u&&(u.targetGrid=c)})},setCurrPage:function(a){this.currpage=a},setTotlaPage:function(a){this.totalpage=a},nextPage:function(){var a=0,b=this;null==b.currpage||0==b.currpage?a=1:(a=b.currpage+1,a>b.totalpage&&(a=1));b.store.getProxy().extraParams.hasOwnProperty("page")&&(b.store.getProxy().extraParams.page=a,b.store.currentPage=a);b.store.load(function(c){b.getSelectionModel().deselectAll();b.setCurrPage(a);b.setRefreshTime()})},
globalNextPage:function(a){var b=0,c=this;if(-1==a)c.store.getProxy().extraParams.hasOwnProperty("page")&&(c.store.getProxy().extraParams.page=1,c.store.currentPage=1),c.store.load(function(a){c.getSelectionModel().deselectAll();c.setCurrPage(1);c.setRefreshTime();c.usePopup&&(a=c.getSelectionModel(),null!=a&&a.select(0))});else if(b=c.currpage+1,b>c.totalpage&&(b=1),c.usePopup){var d=c.getSelectionModel();null!=d&&(a=0,null==d.lastSelected?d.select(0):d.lastSelected.index%c.getStore().pageSize==
c.getStore().getCount()-1||null==d.getSelection()||0==d.getSelection().length?(c.store.getProxy().extraParams.hasOwnProperty("page")&&(c.store.getProxy().extraParams.page=b,c.store.currentPage=b),c.store.load(function(a){d.deselectAll();c.setCurrPage(b);c.setRefreshTime();c.getSelectionModel().select(0)})):(a=(d.lastSelected.index+1)%c.getStore().pageSize,c.getSelectionModel().select(a)))}else c.store.getProxy().extraParams.hasOwnProperty("page")&&(c.store.getProxy().extraParams.page=b,c.store.currentPage=
b),c.store.load(function(a){c.getSelectionModel().deselectAll();c.setCurrPage(b);c.setRefreshTime()})},nextSelectedRow:function(){var a=this.getSelectionModel();if(null!=a){var b=0;null!=a.lastSelected&&(b=this.getSelectionModel().lastSelected.index%this.getStore().pageSize>=this.getStore().getCount()-1||null==a.getSelection()||0==a.getSelection().length?0:(this.getSelectionModel().lastSelected.index+1)%this.getStore().pageSize);a.select(b)}},setRefreshTimeTitle:function(a,b){var c=this.dockedItems.get(1).items.get(14);
null!=c&&c.setText(d.refresh_gap+"  "+a+"  "+b)},setRefreshTime:function(){var a=this.dockedItems.get(1).items.get(15);null!=a&&a.setText(Ext.Date.format(new Date(Ext.Date.now()),"Y/m/d H:i:s"))},setButtonStatus:function(a){var b=this.dockedItems.get(1).items.get(12);b.toggle(a);b.btnClick(b,a)},setPopupInfo:function(a){var b=this.dockedItems.get(3);null!=a&&(a.use_popup?(b.setVisible(!0),this.usePopup=a.use_popup,this.popupImgPath=a.popup_dir,this.popup_refresh_gap=a.popup_refresh_gap,null!=a.imgcols&&
0<a.imgcols.trim().length&&(this.popupImgCols=a.imgcols.split(";")),null!=a.titlecols&&0<a.titlecols.trim().length&&(this.popupTitleCols=a.titlecols.split(";"))):(b.setVisible(!1),this.usePopup=!1,this.popupImgPath="",this.popupImgCols=[],this.popupTitleCols=[],this.popup_refresh_gap=600));null!=v&&v.setTimeGap(this.popup_refresh_gap);this.usePopup&&(b.header.items.get(0).toggle(!0),b.header.items.get(0).handler())},getPopupWidth:function(){var a=this.dockedItems.get(3),b=200;null!=a&&(b=a.getWidth());
return b},setPopupWidth:function(a){var b=this.dockedItems.get(3);null!=b&&b.setWidth(a)},changeIcon:function(a){var b=this.dockedItems.get(1).items.get(12);(b.pressed=a)?(b.removeCls("starttimerbutton"),b.addCls("stoptimerbutton"),b.setTooltip(d.stop_timer)):(b.removeCls("stoptimerbutton"),b.addCls("starttimerbutton"),b.setTooltip(d.start_timer))}}),D=Ext.create("DCI.Customer.SubPanel",{id:k.func_id+"Main",renderTo:"indkbPage",autoDestroy:!0,pagetype:"kanban",border:0,bodyPadding:"0 5 5 5",layout:"border",
widthChangeControls:[z,h],items:[z,h],plugins:["fittoparent"],globalRunning:!1,beforeClose:function(){null!=r&&r.stopScrollTask();null!=t&&t.stopTask();null!=v&&v.stopTask();removeAllStyle(n)},focusPage:function(){this.globalRunning||(m&&t.executeTask(),w&&v.executeTask(),null!=Ext.get(this.renderTo)&&this.resize(Ext.get(this.renderTo).getWidth(),Ext.get(this.renderTo).getHeight()),null!=h&&h.setRefreshTimeTitle(t.getDisplayGap(),d.minutes))},leavePage:function(){m&&t.stop();w&&v.stop()},globalTimerEvent:function(a,
b){null!=t&&(t.stop(),null!=h&&h.changeIcon(!1));null!=v&&v.stop();null!=h&&(h.setRefreshTimeTitle(b,d.seconds),h.globalNextPage(a));this.globalRunning=!0;return h.currpage},globalTimerStop:function(){this.globalRunning=!1;m&&t.executeTask();w&&v.executeTask();null!=h&&h.setRefreshTimeTitle(t.getDisplayGap(),d.minutes)},switchToNextTab:function(){var a=!1;if(h.currpage==h.totalpage)if(h.usePopup){var b=h.getSelectionModel();null!=b&&null!=b.lastSelected&&b.lastSelected.index%h.getStore().pageSize>=
h.getStore().getCount()-1&&(a=!0)}else a=!0;else a=!1;return a},relationReload:function(a){k.relation_filter=a;this.items.get(1).getStore().gridreload(this.items.get(0),"reload")}}),C=Ext.create("Ext.data.Store",{autoLoad:!1,fields:"cols fields legend marquee refresh display combo lights popup advances relation is_cross".split(" "),proxy:{type:"ajax",url:"./../../Funcs/EKB/KanBan.dsc",actionMethods:{read:"POST"},reader:{type:"json"},extraParams:{DCITag:e,uid:p,action:"init",sql_id:k.func_id}}}),t=
E.newTask({timegap:600,displaygap:30,run:function(){null!=h&&h.nextPage()},setTimeGap:function(a){this.timegap=null==a||""==a||1>a?600:a},getTimeGap:function(){return this.timegap},setDisplayGap:function(a){this.displaygap=null==a||""==a||1>a?600:a},getDisplayGap:function(){return this.displaygap},executeTask:function(){this.start(1E3*this.timegap);m=!0;null!=h&&h.changeIcon(!0)},stopTask:function(){this.stop();m=!1;null!=h&&h.changeIcon(!1)}}),v=E.newTask({timegap:600,run:function(){null!=h&&h.nextSelectedRow()},
setTimeGap:function(a){this.timegap=null==a||""==a||1>a?600:a},executeTask:function(){this.start(1E3*this.timegap);w=!0},stopTask:function(){this.stop();w=!1}});C.load(function(a){if(0<a.length){if(null!=y){for(var b=a[0].get("fields"),c=0;c<b.length;c++)""==b[c].sortType&&(b[c].sortType=function(a){a=parseFloat(String(a).replace(/,/g,"").replace("$",""));return isNaN(a)?0:a});y.model.setFields(b);if(null!=h){h.setCrossDBIcon(a[0].get("is_cross"));h.initBodyGrid(t,a[0].get("cols"),y,a[0].get("relation"));
h.setPopupInfo(a[0].get("popup"));c=a[0].get("display");b="16";null!=c.grid_row_height&&""!=c.grid_row_height&&(b=c.grid_row_height,b=28>=b?16:b-12);for(var c=a[0].get("cols"),f=0;f<c.length;f++)void 0!=c[f].xtype&&"dcilightcolumn"==c[f].xtype&&(c[f].rowHeight=b)}null!=r&&(b=a[0].get("marquee"),1==b.use_marquee?("1"==b.marquee_location?r.setDocked("bottom"):r.setDocked("top"),h.doLayout(),r.startMarquee(r,b.marquee_refresh_gap,b.marquee_type)):r.setVisible(!1));null!=t&&(b=a[0].get("refresh"),t.setTimeGap(b.refresh_gap),
t.setDisplayGap(b.display_gap),h.setRefreshTimeTitle(b.display_gap,d.minutes),"1"==b.auto_refresh&&t.executeTask(),h.setButtonStatus("1"==b.auto_refresh));null!=u&&(u.lightsData=a[0].get("lights"));null!=u&&null!=B&&(c=a[0].get("display"),B.setCss(c),u.setComboData(a[0].get("combo")),B.setComboData(a[0].get("combo")),u.setInitData(c),B.setInitData(c,h),h.setPopupWidth(c.popup_width));null!=q&&(q.setComboData(a[0].get("combo")),q.lightsData=a[0].get("lights"),q.setInitData(z,y,q,a[0].get("advances")));
y.gridreload(z,q.condiStr)}null!=z&&(b=a[0].get("legend"),null==b||0==b.length?z.setTitle("<table><tr><td><font size='2'>"+k.func_name+"</font></td></tr></table>"):z.setTitle(a[0].get("legend").replace("$$$kn$$$",k.func_name)))}})}var e="close search save add _delete edit exit errmsg save_format to_edit to_view mode_view mode_edit no_edit_auth expand collapse refersh clear system_error ok cancel toolbar_query_title condi_col save_msg load_def_fail load_def_success load_def_result_title load_def_confirm_title load_def_confirm_msg save_fail save_success save_result_title save_fail sort_column page_size no_query no_sort asc desc refresh_gap minutes favorties_setup start_with end_with bigger bigger_equal smaller smaller_equal equal not_equal like not_like font_size row_height bg_color font_color condi_relation adv_search save_condi load_def_format load_def_condi to_excel to_html start_timer stop_timer seconds cus_format cross_db".split(" ");
this.dcistore.setMultiLangKeys(e);this.dcistore.setUid(globeuid);this.dcistore.load(function(k){if(null!=k&&1==k.length){var s=buildMultiLangObjct(e,k[0].get("langValues")),d=k[0].get("dcitagValue");Ext.EventManager.on(window,"unload",function(){if("Firefox"==navigator.userAgent.match("Firefox")){var e=new XMLHttpRequest;e&&(e.open("GET","./../../Login.dsc?action=logout&uid="+globeuid+"&DCITag="+d,!1),e.send(""))}else"Microsoft Internet Explorer"==navigator.appName||"Netscape"==navigator.appName?
window.navigate("./../../Login.dsc?action=logout&uid="+globeuid+"&DCITag="+d):Ext.Ajax.request({method:"POST",url:"./../../Login.dsc",params:{DCITag:d,uid:globeuid,action:"logout"}})});Ext.Ajax.request({method:"POST",url:"./../../EKB/OpenLink/IndKanBan.dsc",params:{DCITag:d,uid:globeuid,action:"getparams",pagekey:pagekey},success:function(e){if(-1!=e.responseText.indexOf("@dcifiltererrtag@$")){if(e=e.responseText.split("$"),2<=e.length){var k=Ext.JSON.decode(e[1]);Ext.Msg.alert(s.errmsg,k.msg,function(){iserror=
!0;logout(d,globeuid);window.location=k.result})}}else if(e=Ext.JSON.decode(e.responseText),!0==e.success){Ext.getDoc().dom.title=e.params.func_name;var w={};w.func_id=e.params.func_id;w.func_name=e.params.func_name;w.conn_id=e.params.conn_id;w.relation_filter=e.params.relation_filter;m(w,d,s,globeuid)}else Ext.Msg.alert(s.errmsg,s.kanban_not_exist)}})}})});
