var pagekey,globeuid;function logout(n,f){"Microsoft Internet Explorer"==navigator.appName?window.navigate("./../../Login.dsc?action=logout&uid="+f+"&DCITag="+n):Ext.Ajax.request({method:"POST",url:"./../../Login.dsc",params:{DCITag:n,uid:f,action:"logout"}})}function removeAllStyle(n){for(var f=0;null!=document.getElementById(n);){Ext.util.CSS.removeStyleSheet(n);if(10<=f)break;f++}}
function changeKanbanGrid(n,f,l){try{var r=null,e=null;"FS"==l?(r="font-size",e=n+"pt",Ext.util.CSS.updateRule("."+f+" .x-progress-text",r,n-2+"pt")):"FC"==l?(r="color",e="#"+n):"BC"==l?(r="background-color",e="#"+n):"RH"==l&&(r="height",e=n+"px",Ext.util.CSS.updateRule("."+f+" .x-progress-default",r,n-8+"px"),Ext.util.CSS.updateRule("."+f+" .x-progress-text","line-height",n-8+"px"));null!=r&&(Ext.util.CSS.updateRule("."+f+" .x-grid-row .x-grid-cell",r,e),"background-color"!=r&&"height"!=r&&Ext.util.CSS.updateRule("."+
f+" .x-column-header",r,e))}catch(s){window.console&&console.log(s.message)}}
function filterComboData(n,f){var l=null;return l="NUM"==n||"DATE"==n?[{label:f.bigger,value:">"},{label:f.bigger_equal,value:">="},{label:f.smaller,value:"<"},{label:f.smaller_equal,value:"<="},{label:f.equal,value:"="},{label:f.not_equal,value:"<>"}]:"LIGHT"==n||"MAPPING"==n?[{label:f.equal,value:"="},{label:f.not_equal,value:"<>"}]:[{label:f.start_with,value:"startwith"},{label:f.end_with,value:"endwith"},{label:f.bigger,value:">"},{label:f.bigger_equal,value:">="},{label:f.smaller,value:"<"},
{label:f.smaller_equal,value:"<="},{label:f.equal,value:"="},{label:f.not_equal,value:"<>"},{label:f.like,value:"like"},{label:f.not_like,value:"notlike"}]}
Ext.onReady(function(){function n(l,f,e,s){Ext.define("DCI.Customer.LightColumnCus",{extend:"Ext.grid.column.Column",xtype:"dcilightcolumnCus",alias:"DCI.Customer.LightColumn",colid:"",width:100,renderer:function(a){return"<img src='./../../ImageLoader.dsc?iconid="+a+"' width=70% hight=70%/>"}});var n=!1,x=!1,E=new Ext.util.TaskRunner,p=l.func_id+"grid",z=Ext.create("Ext.data.Store",{autoLoad:!1,fields:[],proxy:{type:"ajax",url:"./../../Funcs/EKB/KanBan.dsc",actionMethods:{read:"POST"},reader:{root:"items",
totalProperty:"total"},extraParams:{DCITag:f,uid:s,action:"query",page:1,pagesize:20,filter:"",sort:"",sql_id:l.func_id,conn_id:l.conn_id}},pageSize:20,gridreload:function(a,b){var c=a.items.get(0),g=a.items.get(1),d="",e="";if(null==b||0==b.length){var h=c.condiParams.condi_col,f=c.condiParams.condi_type,y=c.condiParams.condi_value;null!=h&&""!=h&&(d=" and "+h+" ",d="startwith"==f?d+("like '"+y+"%' "):"endwith"==f?d+("like '%"+y+"' "):"like"==f?d+("like '%"+y+"%' "):"notlike"==f?d+("not like '%"+
y+"%' "):d+(f+" '"+y+"' "))}else d=b;null!=g.displayParams.sort_col&&""!=g.displayParams.sort_col&&(e=g.displayParams.sort_col+" "+g.displayParams.sort_type);this.getProxy().extraParams.hasOwnProperty("page")&&(this.currentPage=this.getProxy().extraParams.page=1);this.getProxy().extraParams.hasOwnProperty("pagesize")&&(this.pageSize=this.getProxy().extraParams.pagesize=g.sortParams.page_size);this.getProxy().extraParams.hasOwnProperty("filter")&&(null!=l.relation_filter&&0<l.relation_filter.length?
this.getProxy().extraParams.filter=l.relation_filter:this.getProxy().extraParams.filter=d);this.getProxy().extraParams.hasOwnProperty("sort")&&(this.getProxy().extraParams.sort=e);this.load();null!=c.targetGrid&&c.targetGrid.getSelectionModel().deselectAll()}}),t=Ext.create("Ext.panel.Panel",{region:"north",height:30,width:"100%",border:2,title:"",dock:"top",dataTask:null,scrollTask:null,marqueeUrl:"./../../Funcs/EKB/KanBan.dsc",html:"",startMarquee:function(a,b,c){function g(b){null!=h&&h.load(function(d){if(0<
d.length){var h="";if("1"==c){for(var g=0;g<d.length;g++)h=0==g?'<div style="font-size:22px;"><Marquee height="'+a.height+'" scrollamount="3" onmouseover="this.stop()" onmouseout="this.start()">'+d[g].get("message"):h+("                              "+d[g].get("message")),g==d.length-1&&(h+="</div></Marquee>");a.update(h)}else{null!=a.scrollTask&&(a.scrollTask.stop(),a.body.dom.scrollTop=0);for(var e="",g=0;g<d.length;g++)0==g?(e='<div style="font-size:22px;text-align:center;overflow:hidden;height:'+
a.height+'px;">'+d[g].get("message")+"</div>",h="<div>"+e):h+='<div  style="font-size:22px;text-align:center;overflow:hidden;height:'+a.height+'px;">'+d[g].get("message")+"</div>",g==d.length-1&&(h+=e+"</div>");a.update(h);null!=a.scrollTask&&a.scrollTask.start(5E3)}b(a)}})}var d=new Ext.util.TaskRunner,e=null,h=Ext.create("Ext.data.Store",{autoLoad:!1,fields:["message"],proxy:{type:"ajax",url:this.marqueeUrl,actionMethods:{read:"POST"},reader:{root:"marquee"},extraParams:{DCITag:f,uid:s,action:"marqueeData",
sql_id:l.func_id,conn_id:l.conn_id}}}),k=d.newTask({run:function(){g(function(a){})}});this.dataTask=k;g(function(a){k.start(1E3*b);var g=0;"2"==c?(e=d.newTask({run:function(){0<h.getCount()&&(0==g&&(a.body.dom.scrollTop=0),g==h.getCount()-1?g=0:g++,a.scrollBy(0,a.height,!0))}}),a.scrollTask=e,e.start(5E3)):a.scrollTask=null})},stopScrollTask:function(){null!=this.dataTask&&this.dataTask.stop();null!=this.scrollTask&&this.scrollTask.stop()},listeners:{el:{mouseover:function(a,b,c){null!=t&&null!=
t.scrollTask&&t.scrollTask.stop()}},body:{mouseout:function(a,b,c){null!=t&&null!=t.scrollTask&&t.scrollTask.start(5E3)}}}}),q=Ext.create("Ext.window.Window",{layout:"border",title:e.toolbar_query_title,closeAction:"hide",height:300,width:520,minHeight:300,minWidth:520,modal:!0,plain:!0,condiStr:"",kanbanStore:null,headPanel:null,lightsData:null,langObj:e,items:[{xtype:"panel",region:"north",layout:"anchor",border:0,height:70,items:[{xtype:"panel",layout:"absolute",anchor:"100% 50%",height:35,condiParams:{condi_col:"",
condi_type:"",condi_value:"",dcondi_col:"",dcondi_type:"",dcondi_value:""},items:[Ext.create("DCI.Customer.ComboBox",{fieldLabel:e.condi_col,store:{fields:["label","value","col_type","config_value"],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}},labelWidth:90,width:250,x:0,y:5,listeners:{change:function(a,b,c,g){c=this.up("panel");var d=c.items.get(1),m=a.getStore();g=c.items.get(2);for(var h=null,f=null,y=null,k=0;k<m.getCount();k++)if(b==m.getAt(k).get("value")){h=m.getAt(k).get("col_type");
y=m.getAt(k).get("config_value");break}if(null!=h){d.getStore().loadData(filterComboData(h,e));d.loadDefault();if("DATE"==h)f=Ext.create("DCI.Customer.DateField",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:c,x:340,y:5,listeners:{change:function(a,b,c,d){a.parentPanel.condiParams.condi_value=Ext.Date.format(new Date(b),"Ymd");a.parentPanel.condiParams.dcondi_value=Ext.Date.format(new Date(b),"Y/m/d")}}});else if("MAPPING"==h||"LIGHT"==h){f=Ext.create("DCI.Customer.ComboBox",
{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:c,x:340,y:5,listeners:{change:function(b,c,d,h){b.parentPanel.condiParams.condi_value=c;b.parentPanel.condiParams.dcondi_value=a.getRawValue()}}});if("MAPPING"==h){d=[];y=y.split(";");m=null;for(k=0;k<y.length;k++)m=y[k].split("="),null!=m&&2==m.length&&d.push({value:m[0],label:m[1]});f.getStore().loadData(d)}else null!=c.up("panel").up("window").lightsData&&f.getStore().loadData(c.up("panel").up("window").lightsData);
f.loadDefault()}else f=Ext.create("DCI.Customer.TextField",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:c,x:340,y:5,listeners:{change:function(a,b,c,d){a.parentPanel.condiParams.condi_value=b;a.parentPanel.condiParams.dcondi_value=b}}});c.remove(g.getId());c.insert(2,f)}c.condiParams.condi_col=b;c.condiParams.dcondi_col=a.getRawValue()}}}),Ext.create("DCI.Customer.ComboBox",{fieldLabel:"",labelWidth:0,width:90,x:250,y:5,listeners:{change:function(a,b,c,g){c=
this.up("panel");c.condiParams.condi_type=b;c.condiParams.dcondi_type=a.getRawValue()}}}),Ext.create("DCI.Customer.TextField",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",x:340,y:5})]},{xtype:"panel",anchor:"100% 50%",layout:"absolute",items:[{xtype:"radiogroup",fieldLabel:e.condi_relation,columns:2,vertical:!0,width:200,x:0,y:5,items:[{boxLabel:"AND",name:"rb",inputValue:"AND",checked:!0},{boxLabel:"OR",name:"rb",inputValue:"OR"}]},{xtype:"button",text:e.add,x:200,y:5,
handler:function(){var a=this.up("panel"),b=a.up("panel").items.get(0),c=a.up("panel").up("window").items.get(1).getStore(),a=a.items.get(0).getValue();null!=c&&c.add({condi_relation:a.rb,condi_col_display:b.condiParams.dcondi_col,condi_type_display:b.condiParams.dcondi_type,condi_value_display:b.condiParams.dcondi_value,condi_col:b.condiParams.condi_col,condi_type:b.condiParams.condi_type,condi_value:b.condiParams.condi_value})}},{xtype:"button",text:e._delete,x:250,y:5,handler:function(){var a=
this.up("panel").up("panel").up("window").items.get(1);a.getSelectionModel().hasSelection()&&a.getStore().remove(a.getSelectionModel().getSelection()[0])}},{xtype:"button",text:e.clear,x:300,y:5,handler:function(){var a=this.up("panel").up("panel").up("window").items.get(1).getStore();null!=a&&a.removeAll()}}]}]},{xtype:"grid",region:"center",renderer:"component",border:0,stripeRows:!0,autoScroll:!0,loadMask:!0,hideHeaders:!0,enableTextSelection:!0,viewConfig:{forceFit:!1,autoLoad:!1},columns:[{dataIndex:"condi_relation",
width:50},{dataIndex:"condi_col_display",width:150},{text:e.conn_id,dataIndex:"condi_type_display",width:100},{text:e.conn_id,dataIndex:"condi_value_display",width:200}],store:Ext.create("Ext.data.Store",{fields:"condi_relation condi_col_display condi_type_display condi_value_display condi_col condi_type condi_value".split(" "),autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}},syncCondiString:function(a){for(var b="",c=0;c<this.getCount();c++)b+=" "+this.getAt(c).get("condi_relation")+" "+this.getAt(c).get("condi_col")+
" ",b="startwith"==this.getAt(c).get("condi_type")?b+("like '"+this.getAt(c).get("condi_value")+"%' "):"endwith"==this.getAt(c).get("condi_type")?b+("like '%"+this.getAt(c).get("condi_value")+"' "):"like"==this.getAt(c).get("condi_type")?b+("like '%"+this.getAt(c).get("condi_value")+"%' "):"notlike"==this.getAt(c).get("condi_type")?b+("not like '%"+this.getAt(c).get("condi_value")+"%' "):b+(this.getAt(c).get("condi_type")+" '"+this.getAt(c).get("condi_value")+"' ");a.condiStr=b},listeners:{datachanged:function(a,
b){var c=null;null!=v&&(c=v.items.get(4),null!=c&&(0<a.getCount()?c.getEl().setStyle({borderWidth:"2px 2px 2px 2px",borderColor:"red",boderStyle:"solid"}):c.getEl().setStyle({borderWidth:"1px 1px 1px 1px",borderColor:"",boderStyle:""})))}}})}],buttons:[{xtype:"button",text:e.ok,handler:function(){var a=this.up("window"),b=a.items.get(1).getStore();null!=b&&(b.syncCondiString(a),null!=a.kanbanStore&&a.kanbanStore.gridreload(a.headPanel,a.condiStr));a.close()}},{xtype:"button",text:e.cancel,handler:function(){this.up("window").close()}}],
setComboData:function(a,b){var c=this.items.get(0).items.get(0).items.get(0),g=c.getStore();null!=g&&(g.loadData(a),null==b||""==b?c.loadDefault():c.setValue(b))},setInitData:function(a,b,c,g){var d=this.items.get(0).items.get(0).items.get(0);null==c.filter_col||""==c.filter_col?d.loadDefault():d.setValue(c.filter_col);d=this.items.get(0).items.get(0).items.get(1);null==c.filter_condi||""==c.filter_condi?d.loadDefault():d.setValue(c.filter_condi);d=this.items.get(0).items.get(0).items.get(2);null==
c.filter_value||""==c.filter_value?d.loadDefault():d.setValue(c.filter_value);this.headPanel=a;this.kanbanStore=b;null!=g&&(this.items.get(1).getStore().loadData(g),this.items.get(1).getStore().syncCondiString(q));var m=this.items.get(0).items.get(0);g=m.items.get(0).getStore();d=m.items.get(1);a=m.items.get(2);var h=null;c=b=null;if(null!=g&&0<g.getCount()&&(h=g.getAt(0).get("col_type"),c=g.getAt(0).get("config_value"),null!=h)){d.getStore().loadData(filterComboData(h,e));d.loadDefault();if("DATE"==
h)b=Ext.create("DCI.Customer.DateField",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:m,x:340,y:5,listeners:{change:function(a,b,c,d){a.parentPanel.condiParams.condi_value=Ext.Date.format(new Date(b),"Ymd");a.parentPanel.condiParams.dcondi_value=Ext.Date.format(new Date(b),"Y/m/d")}}});else if("MAPPING"==h||"LIGHT"==h){b=Ext.create("DCI.Customer.ComboBox",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:m,x:340,y:5,listeners:{change:function(a,
b,c,d){a.parentPanel.condiParams.condi_value=b;a.parentPanel.condiParams.dcondi_value=m.items.get(2).getRawValue()}}});if("MAPPING"==h){g=[];c=c.split(";");d=null;for(h=0;h<c.length;h++)d=c[h].split("="),null!=d&&2==d.length&&g.push({value:d[0],label:d[1]});b.getStore().loadData(g)}else null!=this.lightsData&&b.getStore().loadData(this.lightsData);b.loadDefault();m.condiParams.condi_value=b.getValue();m.condiParams.dcondi_value=b.getRawValue()}else b=Ext.create("DCI.Customer.TextField",{fieldLabel:"",
labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:m,x:340,y:5,listeners:{change:function(a,b,c,d){a.parentPanel.condiParams.condi_value=b;a.parentPanel.condiParams.dcondi_value=b}}});m.remove(a.getId());m.insert(2,b)}},getCondiValue:function(){var a=[],b=this.items.get(1).getStore();if(null!=b)for(var c=0;c<b.getCount();c++)a.push({condi_relation:b.getAt(c).get("condi_relation"),condi_col:b.getAt(c).get("condi_col"),condi_type:b.getAt(c).get("condi_type"),condi_value:b.getAt(c).get("condi_value"),
condi_col_display:b.getAt(c).get("condi_col_display"),condi_type_display:b.getAt(c).get("condi_type_display"),condi_value_display:b.getAt(c).get("condi_value_display"),seq:c});return a}}),v=Ext.create("Ext.panel.Panel",{title:"",anchor:"100% 50%",layout:"absolute",border:0,bodyStyle:{background:"#d3e1f1"},bodyPadding:0,targetGrid:null,lightsData:null,condiParams:{condi_col:"",condi_type:"",condi_value:""},items:[Ext.create("DCI.Customer.ComboBox",{fieldLabel:e.condi_col,store:{fields:["label","value",
"col_type","config_value"],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}},labelWidth:90,width:250,x:0,y:8,listeners:{change:function(a,b,c,g){c=this.up("panel");var d=c.items.get(1),m=a.getStore();a=c.items.get(2);for(var h=null,f=g=null,k=0;k<m.getCount();k++)if(b==m.getAt(k).get("value")){h=m.getAt(k).get("col_type");f=m.getAt(k).get("config_value");break}if(null!=h){d.getStore().loadData(filterComboData(h,e));d.loadDefault();if("DATE"==h)g=Ext.create("DCI.Customer.DateField",{fieldLabel:"",
labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:c,x:340,y:8,listeners:{change:function(a,b,c,d){a.parentPanel.condiParams.condi_value=Ext.Date.format(new Date(b),"Ymd")}}});else if("MAPPING"==h||"LIGHT"==h){g=Ext.create("DCI.Customer.ComboBox",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:c,x:340,y:8,listeners:{change:function(a,b,c,d){a.parentPanel.condiParams.condi_value=b}}});if("MAPPING"==h){d=[];f=f.split(";");m=null;for(k=0;k<f.length;k++)m=
f[k].split("="),null!=m&&2==m.length&&d.push({value:m[0],label:m[1]});g.getStore().loadData(d)}else g.getStore().loadData(c.lightsData);g.loadDefault()}else g=Ext.create("DCI.Customer.TextField",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",parentPanel:c,x:340,y:8,listeners:{change:function(a,b,c,d){a.parentPanel.condiParams.condi_value=b}}});c.remove(a.getId());c.insert(2,g)}c.condiParams.condi_col=b}}}),Ext.create("DCI.Customer.ComboBox",{fieldLabel:"",labelWidth:0,width:90,
x:250,y:8,listeners:{change:function(a,b,c,g){this.up("panel").condiParams.condi_type=b}}}),Ext.create("DCI.Customer.TextField",{fieldLabel:"",labelWidth:0,width:150,name:"condi_value",defaultvalue:"",x:340,y:8}),{xtype:"button",cls:"search-toolbar",tooltip:e.search,width:30,height:30,x:500,y:3,handler:function(){var a=this.up("panel"),b=a.targetGrid.getStore();l.relation_filter="";b.gridreload(a.up("panel"),q.condiStr)}},{xtype:"button",cls:"advsearchbutton",tooltip:e.adv_search,width:30,height:30,
x:530,y:3,handler:function(){null!=q&&q.show()}},{xtype:"button",cls:"savebutton",tooltip:e.save_format,width:30,height:30,x:560,y:3,handler:function(){var a=this.up("panel"),b=this.up("panel").up("panel").items.get(1),c=this.up("panel").targetGrid.columns,g=[],d={},k=a.targetGrid;d.popup_width=null==k?200:k.getPopupWidth();for(var h in b.displayParams)d[h]=b.displayParams[h];for(a=0;a<c.length;a++)h={},h.col_id=c[a].colid,h.col_index=c[a].getIndex(),h.col_width=c[a].width,h.col_visible=c[a].hidden?
0:1,g.push(h);Ext.Ajax.request({method:"POST",url:"../../Funcs/EKB/KanBan.dsc",params:{DCITag:f,uid:s,action:"saveFormat",gridid:l.func_id,datas:Ext.encode(d),coldatas:Ext.encode(g)},success:function(a){null!=k&&k.addCusFormatIcon();b.setCss({grid_font_size:b.displayParams.fs,grid_font_color:b.displayParams.fc,grid_row_height:b.displayParams.rh,grid_row_color:b.displayParams.bc});Ext.Msg.alert(e.save_result_title,e.save_success)},failure:function(a,b){Ext.Msg.alert(e.save_result_title,e.save_fail+
" :</br>"+b.result.errorMessage)}})}},{xtype:"button",cls:"backdefault_greenbutton",tooltip:e.load_def_format,width:30,height:30,x:590,y:3,handler:function(){var a=this.up("panel").up("panel").items.get(1);Ext.MessageBox.confirm(e.load_def_confirm_title,e.load_def_confirm_msg,function(b){"yes"==b&&Ext.Ajax.request({method:"POST",url:"../../Funcs/EKB/KanBan.dsc",params:{DCITag:f,uid:s,action:"loadDefFormat",datas:"dodelete",gridid:l.func_id},success:function(b){a.setCss({grid_font_size:13,grid_font_color:"000000",
grid_row_height:28,grid_row_color:null});null!=k&&(k.rmCusFormatIcon(),k.setPopupWidth(200),null!=C&&0<C.getCount()&&C.load(function(a){k.reloadBodyGridFormat(a[0].get("cols"),z)}));Ext.Msg.alert(e.load_def_result_title,e.load_def_success)},failure:function(a,b){Ext.Msg.alert(e.load_def_result_title,e.load_def_fail+" :</br>"+b.result.errorMessage)}})})}},{xtype:"button",cls:"save-toolbar",tooltip:e.save_condi,width:30,height:30,x:620,y:3,handler:function(){var a=this.up("panel"),b=this.up("panel").up("panel").items.get(1),
c={},g=null,d;for(d in a.condiParams)c[d]=a.condiParams[d];for(d in b.sortParams)c[d]=b.sortParams[d];if(null==c.condi_col||""==c.condi_col)c.condi_type="",c.condi_value="";if(null==c.sort_col||""==c.sort_col)c.sort_type="";null!=q&&null!=q.getCondiValue()&&0<q.getCondiValue().length&&(g=Ext.encode(q.getCondiValue()));Ext.Ajax.request({method:"POST",url:"../../Funcs/EKB/KanBan.dsc",params:{DCITag:f,uid:s,action:"saveCondi",sql_id:l.func_id,datas:Ext.encode(c),advDatas:g},success:function(b){l.relation_filter=
"";a.targetGrid.getStore().gridreload(a.up("panel"),q.condiStr);Ext.Msg.alert(e.save_result_title,e.save_success)},failure:function(a,b){Ext.Msg.alert(e.save_result_title,e.save_fail+" :</br>"+b.result.errorMessage)}})}},{xtype:"button",cls:"backdefault_bluebutton",tooltip:e.load_def_condi,width:30,height:30,x:650,y:3,handler:function(){var a=this.up("panel").up("panel"),b=a.items.get(0),c=a.items.get(1);Ext.MessageBox.confirm(e.load_def_confirm_title,e.load_def_confirm_msg,function(g){"yes"==g&&
Ext.Ajax.request({method:"POST",url:"../../Funcs/EKB/KanBan.dsc",params:{action:"loadDefCondi",uid:s,datas:"dodelete",DCITag:f,sql_id:l.func_id},success:function(d){d={filter_col:"",filter_condi:"",filter_value:"",sort_col:"",sort_type:"",page_size:20};b.setInitData(d);if(null!=q){var g=q.items.get(1).getStore();null!=g&&g.removeAll()}c.setInitData(d);b.targetGrid.getStore().gridreload(a);Ext.Msg.alert(e.load_def_result_title,e.load_def_success)},failure:function(a,b){Ext.Msg.alert(e.load_def_result_title,
e.load_def_fail+" :</br>"+b.result.errorMessage)}})})}}],setComboData:function(a,b){var c=this.items.get(0),g=c.getStore();console.log(a);a.unshift({label:e.no_query,value:"",col_type:"CHAR",config_value:""});null!=g&&(g.loadData(a),null==b||""==b?c.loadDefault():c.setValue(b));a.shift()},setInitData:function(a){var b=this.items.get(0);null==a.filter_col||""==a.filter_col?b.loadDefault():b.setValue(a.filter_col);b=this.items.get(1);null==a.filter_condi||""==a.filter_condi?b.loadDefault():b.setValue(a.filter_condi);
b=this.items.get(2);null==a.filter_value||""==a.filter_value?b.loadDefault():b.setValue(a.filter_value)}}),B=Ext.create("Ext.panel.Panel",{title:"",anchor:"100% 50%",layout:"absolute",border:0,bodyStyle:{background:"#d3e1f1"},bodyPadding:0,sortParams:{sort_col:"",sort_type:"",page_size:20},displayParams:{fs:13,fc:"000000",rh:28,bc:"FFFFFF"},bodygrid:null,items:[Ext.create("DCI.Customer.ComboBox",{fieldLabel:e.sort_column,name:"sort_column",labelWidth:90,width:250,x:0,y:8,listeners:{change:function(a,
b,c,g){this.up("panel").sortParams.sort_col=b}}}),Ext.create("DCI.Customer.ComboBox",{fieldLabel:"",labelWidth:0,width:90,store:{fields:["label","value"],data:[{label:e.asc,value:"asc"},{label:e.desc,value:"desc"}]},x:250,y:8,listeners:{change:function(a,b,c,g){this.up("panel").sortParams.sort_type=b}}}),Ext.create("DCI.Customer.NumberBox",{fieldLabel:e.page_size,labelWidth:60,defaultvalue:20,maxValue:9999,minValue:1,width:150,x:340,y:8,listeners:{change:function(a,b,c,g){this.up("panel").sortParams.page_size=
b}}}),{xtype:"button",cls:"configbutton",tooltip:e.favorties_setup,x:500,y:5,width:30,height:30,handler:function(){var a=this.up("panel").displayParams;Ext.create("Ext.window.Window",{title:e.favorties_setup,width:500,height:300,minWidth:300,minHeight:200,layout:"fit",plain:!0,modal:!0,items:[{xtype:"panel",layout:"anchor",items:[{xtype:"slider",anchor:"80% 25%",fieldLabel:e.font_size,border:1,value:a.fs,minValue:8,maxValue:48,increment:1,plugins:new Ext.slider.Tip,listeners:{change:function(b,c,
g,d){changeKanbanGrid(c,p,"FS");if(null!=k&&0<k.columns.length)try{var e=k.columns[0].width;k.columns[0].setWidth(e+10);k.columns[0].setWidth(e)}catch(h){window.console&&console.log(h.message)}a.fs=c},afterrender:function(a,c){this.labelCell.dom.attributes.getNamedItem("valign").value="middle"}}},{xtype:"dcicolorpicker",fieldLabel:e.font_color,defaultColor:"000000",curColor:a.fc,width:180,listeners:{change:function(b,c,g,d){changeKanbanGrid(c,p,"FC");a.fc=c}}},{xtype:"slider",anchor:"80% 25%",fieldLabel:e.row_height,
value:a.rh,minValue:16,maxValue:100,increment:4,plugins:new Ext.slider.Tip,listeners:{change:function(b,c,g,d){changeKanbanGrid(c,p,"RH");a.rh=c},afterrender:function(a,c){this.labelCell.dom.attributes.getNamedItem("valign").value="middle"}}},{xtype:"dcicolorpicker",fieldLabel:e.bg_color,defaultColor:"FFFFFF",curColor:a.bc,width:180,listeners:{change:function(b,c,g,d){changeKanbanGrid(c,p,"BC");a.bc=c}}}]}],buttons:[{text:e.close,handler:function(){this.up(".window").close()}}]}).show()}},{xtype:"button",
cls:"toexcelbutton",tooltip:e.to_excel,width:30,height:30,x:530,y:5,handler:function(){var a=this.up("panel").bodygrid;null!=a&&Ext.create("Ext.form.Panel",{standardSubmit:!0,url:"../../Funcs/EKB/KanBan.dsc",method:"POST"}).submit({target:"_blank",params:{DCITag:f,uid:s,conn_id:l.conn_id,func_id:l.func_id,action:"excel",filter:a.getStore().getProxy().extraParams.filter,sort:a.getStore().getProxy().extraParams.sort,cols:Ext.encode(buildColObj(a.columns)),ctype:"1"}})}},{xtype:"button",cls:"tohtmlbutton",
tooltip:e.to_html,width:30,height:30,x:560,y:5,handler:function(){var a=this.up("panel").bodygrid;null!=a&&Ext.create("Ext.form.Panel",{standardSubmit:!0,url:"../../Funcs/EKB/KanBan.dsc",method:"POST"}).submit({target:"_blank",params:{DCITag:f,uid:s,conn_id:l.conn_id,func_id:l.func_id,action:"html",filter:a.getStore().getProxy().extraParams.filter,sort:a.getStore().getProxy().extraParams.sort,cols:Ext.encode(buildColObj(a.columns)),ctype:"2"}})}}],setComboData:function(a){var b=this.items.get(0),
c=b.getStore();a.unshift({label:e.no_sort,value:""});null!=c&&(c.loadData(a),b.loadDefault());a.shift()},setCss:function(a){var b="",c="";removeAllStyle(p);null!=a.grid_font_size&&""!=a.grid_font_size?(b+="font-size:"+a.grid_font_size+"pt;",c+="font-size:"+a.grid_font_size+"pt;",this.displayParams.fs=a.grid_font_size,Ext.util.CSS.createStyleSheet("."+p+" .x-progress-text {font-size:"+(a.grid_font_size-2)+"pt;}",p)):(b+="font-size:13pt;",c+="font-size:13pt;",this.displayParams.fs="13",Ext.util.CSS.createStyleSheet("."+
p+" .x-progress-text {font-size:11pt}",p));null!=a.grid_font_color&&""!=a.grid_font_color?(b+="color:#"+a.grid_font_color+";",c+="color:#"+a.grid_font_color+";",this.displayParams.fc=a.grid_font_color):(b+="color:black;",c+="color:black;",this.displayParams.fc="000000");null!=a.grid_row_height&&""!=a.grid_row_height?(b+="height:"+a.grid_row_height+"px;",this.displayParams.rh=a.grid_row_height,Ext.util.CSS.createStyleSheet("."+p+" .x-progress-default {height:"+(a.grid_row_height-8)+"px;}",p),Ext.util.CSS.createStyleSheet("."+
p+" .x-progress-text {line-height:"+(a.grid_row_height-8)+"px;}",p)):(b+="height:28px;",this.displayParams.rh="28",Ext.util.CSS.createStyleSheet("."+p+" .x-progress-default {height:20px;}",p),Ext.util.CSS.createStyleSheet("."+p+" .x-progress-text {line-height:20px;}",p));null!=a.grid_row_color&&""!=a.grid_row_color?(b+="background-color:#"+a.grid_row_color+";",this.displayParams.bc=a.grid_row_color):(b+="background-color:withe;",this.displayParams.bc="FFFFFF",Ext.util.CSS.createStyleSheet("."+p+" .x-grid-row-alt .x-grid-cell {background-color:#cce4f6}",
p));Ext.util.CSS.createStyleSheet("."+p+" .x-grid-row .x-grid-cell {"+b+"}",p);Ext.util.CSS.createStyleSheet("."+p+" .x-column-header {"+c+"}",p)},setInitData:function(a,b){var c=this.items.get(0);null==a.sort_col||""==a.sort_col?c.loadDefault():c.setValue(a.sort_col);c=this.items.get(1);null==a.sort_type||""==a.sort_type?c.loadDefault():c.setValue(a.sort_type);c=this.items.get(2);null!=a.page_size&&""!=a.page_size?c.setValue(a.page_size):c.loadDefault();this.bodygrid=b}}),A=Ext.create("Ext.panel.Panel",
{region:"north",height:120,collapsible:!0,title:"",header:{height:35},layout:"anchor",items:[v,B]}),k=Ext.create("Ext.grid.Panel",{region:"center",renderer:"component",stripeRows:!0,autoScroll:!0,loadMask:!0,allowDeselect:!0,usePopup:!0,popupImgPath:"",popupImgCols:[],popupTitleCols:[],popup_refresh_gap:600,selModel:{allowDeselect:!0},enableTextSelection:!0,viewConfig:{forceFit:!1,autoLoad:!1},store:null,bodyCls:p,componentCls:p,columns:[],sqlRelationStore:Ext.create("Ext.data.Store",{fields:["col_id",
"target_sql_id","target_col_id","target_sql_name"],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}}),currpage:0,totalpage:0,timer:null,dockedItems:[{xtype:"pagingtoolbar",store:null,dock:"bottom",displayInfo:!1,items:["-",{enableToggle:!0,width:50,tooltip:"",cls:"starttimerbutton",toggleHandler:function(a,b){null!=D&&!D.globalRunning&&this.btnClick(a,b)},btnClick:function(a,b){var c=this.up("panel").timer;null!=c&&(b?c.executeTask():c.stopTask())}},"-",{xtype:"label",text:e.refresh_gap},{xtype:"label",
text:"",margin:"0 0 0 10"},"-",Ext.create("DCI.Customer.Img",{src:"../../images/icons/CusGridFormat.png",width:20,height:20,hidden:!0,listeners:{afterrender:function(a){Ext.create("Ext.tip.ToolTip",{target:a.getEl(),html:e.cus_format})}}}),Ext.create("DCI.Customer.Img",{src:"../../images/button_icon/BtnCrossDatabase.png",width:20,height:20,hidden:!0,listeners:{afterrender:function(a){Ext.create("Ext.tip.ToolTip",{target:a.getEl(),html:e.cross_db})}}})],listeners:{beforechange:function(a,b,c){this.store.getProxy().extraParams.hasOwnProperty("page")&&
(null==b||0==b?this.store.getProxy().extraParams.page=1:this.store.getProxy().extraParams.page=b);this.store.load()},change:function(a,b,c){null==b||null==b.currentPage||null==b.pageCount?(this.up("panel").setCurrPage(0),this.up("panel").setTotlaPage(0)):(this.up("panel").setCurrPage(b.currentPage),this.up("panel").setTotlaPage(b.pageCount))}}},t,{xtype:"panel",height:"100%",width:200,border:5,title:"",dock:"right",layout:"fit",collapsible:!0,collapseDirection:"right",animCollapse:!1,hidden:!1,buttonAlign:"left",
resizable:!0,items:[{xtype:"panel",height:"100%",title:"",width:"100%",border:0}],header:{items:[{xtype:"button",cls:"playbutton",pressedCls:"pausebutton",width:15,height:15,enableToggle:!0,handler:function(){null!=w&&(this.pressed?(w.executeTask(),null!=k&&k.nextSelectedRow()):w.stopTask())}}]},showPopup:function(a,b){var c=this.items.get(0),g=this.items.get(0);null!=g&&(null==a||""==a?g.setTitle(" "):g.setTitle(a),Ext.Ajax.request({method:"POST",url:"./../../PublicCtrl.dsc",params:{DCITag:f,uid:s,
action:"B64Encode",str:b},success:function(a){a=Ext.JSON.decode(a.responseText);a="<img width="+c.getWidth()+" height="+c.getHeight()+' src="./../../ImageLoader.dsc?imgpath='+a.result+'"/>';c.update(a)}}))}}],listeners:{selectionchange:function(a,b,c){if(this.usePopup&&0<b.length){c=a="";for(var g=this.dockedItems.get(3),d=0;d<this.popupImgCols.length;d++)a=0==d?b[0].get(this.popupImgCols[d]):a+("--"+b[0].get(this.popupImgCols[d]));for(d=0;d<this.popupTitleCols.length;d++)c=0==d?b[0].get(this.popupTitleCols[d]):
c+("--"+b[0].get(this.popupTitleCols[d]));null!=g&&(b=this.popupImgPath.replace("\\",'"'),b=b.replace('"',"\\")+"\\",g.showPopup(c,b+a+".jpg"))}},celldblclick:function(a,b,c,g,d,e,h,k){},cellcontextmenu:function(a,b,c,g,d,e,h,k){if(null!=this.sqlRelationStore&&0<this.sqlRelationStore.getCount()){a=Ext.create("Ext.menu.Menu",{mpanel:D.parentComp,items:[],clickEvent:function(a,b,c){var d=this;null!=d.mpanel&&Ext.Ajax.request({method:"POST",url:"./../../Funcs/EKB/KanBan.dsc",params:{action:"funcInfo",
uid:s,DCITag:f,func_id:b,conn_id:l.conn_id},success:function(h){null==h.responseText||""==h.responseText||0==h.responseText.length?alert("open kanban "+b+" fail"):(h=Ext.JSON.decode(h.responseText),d.mpanel.beforeAddCheck(b,l.conn_id,{url:h.url,text:h.text,func_package:h.func_package,can_edit:h.can_edit,filter:" and "+c+" = '"+a+"'"},!0))}})}});for(b=0;b<this.sqlRelationStore.getCount();b++)this.columns[c].dataIndex==this.sqlRelationStore.getAt(b).get("col_id")&&a.add({text:this.sqlRelationStore.getAt(b).get("target_sql_name"),
currcol:this.sqlRelationStore.getAt(b).get("col_id"),cellValue:g.get(this.columns[c].dataIndex),targetsql:this.sqlRelationStore.getAt(b).get("target_sql_id"),targetcol:this.sqlRelationStore.getAt(b).get("target_col_id"),handler:function(){this.up("menu").clickEvent(this.cellValue,this.targetsql,this.targetcol)}});0<a.items.length&&(h.stopEvent(),a.showAt(h.getXY()))}}},addCusFormatIcon:function(){this.dockedItems.items[1].items.get(17).show()},rmCusFormatIcon:function(){this.dockedItems.items[1].items.get(17).hide()},
setCrossDBIcon:function(a){var b=this.dockedItems.items[1];a?b.items.get(18).show():b.items.get(18).hide()},initBodyGrid:function(a,b,c,g){this.timer=a;var d=this,e=[];Ext.create("Ext.data.Store",{autoLoad:!1,fields:["colFormats"],proxy:{type:"ajax",url:"./../../PublicCtrl.dsc",actionMethods:{read:"POST"},reader:{type:"json"},extraParams:{DCITag:f,uid:s,action:"getGFormat",gridid:l.func_id}}}).load(function(a){if(0<a.length){var k=Ext.create("Ext.data.Store",{fields:["col_id","col_index","col_width",
"col_visible"],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}});k.loadData(a[0].get("colFormats"));if(0<k.getCount()){d.addCusFormatIcon();for(a=0;a<k.getCount();a++)for(var f=0;f<b.length;f++)if(b[f].colid==k.getAt(a).get("col_id")){"1"==k.getAt(a).get("col_visible")?(b[f].hasOwnProperty("hidden"),b[f].hidden=!1,0!=k.getAt(a).get("col_width")&&(b[f].hasOwnProperty("width"),b[f].width=parseInt(k.getAt(a).get("col_width")))):(0!=k.getAt(a).get("col_width")&&(b[f].hasOwnProperty("width"),b[f].width=
parseInt(k.getAt(a).get("col_width"))),b[f].hasOwnProperty("hidden"),b[f].hidden=!0);e.push(b[f]);b.splice(f,1);break}if(null!=b&&0!=b.length)for(a=0;a<b.length;a++)b[a].hidden=!0,e.push(b[a])}else e=b;if(null!=g)for(f=0;f<e.length;f++)for(a=0;a<g.length;a++)if("col"+g[a].col_id==e[f].colid){e[f].hasOwnProperty("componentCls");e[f].componentCls="dci-realtion-column-header";break}d.reconfigure(c,e)}else{if(null!=g)for(f=0;f<b.length;f++)for(a=0;a<g.length;a++)if("col"+g[a].col_id==b[f].colid){b[f].hasOwnProperty("componentCls");
b[f].componentCls="dci-realtion-column-header";break}d.reconfigure(c,b)}d.child("pagingtoolbar").bindStore(z);null!=v&&(v.targetGrid=d)});d.sqlRelationStore.loadData(g)},reloadBodyGridFormat:function(a,b){var c=this,g=[];Ext.create("Ext.data.Store",{autoLoad:!1,fields:["colFormats"],proxy:{type:"ajax",url:"./../../PublicCtrl.dsc",actionMethods:{read:"POST"},reader:{type:"json"},extraParams:{DCITag:f,uid:s,action:"getGFormat",gridid:l.func_id}}}).load(function(d){if(0<d.length){var e=Ext.create("Ext.data.Store",
{fields:["col_id","col_index","col_width","col_visible"],autoLoad:!1,proxy:{type:"memory",reader:{type:"json"}}});e.loadData(d[0].get("colFormats"));if(0<e.getCount()){c.addCusFormatIcon();for(d=0;d<e.getCount();d++)for(var h=0;h<a.length;h++)if(a[h].colid==e.getAt(d).get("col_id")){"1"==e.getAt(d).get("col_visible")?(a[h].hasOwnProperty("hidden"),a[h].hidden=!1,0!=e.getAt(d).get("col_width")&&(a[h].hasOwnProperty("width"),a[h].width=parseInt(e.getAt(d).get("col_width")))):(0!=e.getAt(d).get("col_width")&&
(a[h].hasOwnProperty("width"),a[h].width=parseInt(e.getAt(d).get("col_width"))),a[h].hasOwnProperty("hidden"),a[h].hidden=!0);g.push(a[h]);a.splice(h,1);break}if(null!=a&&0!=a.length)for(d=0;d<a.length;d++)a[d].hidden=!0,g.push(a[d])}else g=a;if(null!=c.sqlRelationStore)for(h=0;h<g.length;h++)for(d=0;d<c.sqlRelationStore.getCount();d++)if("col"+c.sqlRelationStore.getAt(d).data.col_id==g[h].colid){g[h].hasOwnProperty("componentCls");g[h].componentCls="dci-realtion-column-header";break}c.reconfigure(b,
g)}else{if(null!=c.sqlRelationStore)for(h=0;h<a.length;h++)for(d=0;d<c.sqlRelationStore.getCount();d++)if("col"+c.sqlRelationStore.getAt(d).data.col_id==a[h].colid){a[h].hasOwnProperty("componentCls");a[h].componentCls="dci-realtion-column-header";break}c.reconfigure(b,a)}c.child("pagingtoolbar").bindStore(z);null!=v&&(v.targetGrid=c)})},setCurrPage:function(a){this.currpage=a},setTotlaPage:function(a){this.totalpage=a},nextPage:function(){var a=0,b=this;null==b.currpage||0==b.currpage?a=1:(a=b.currpage+
1,a>b.totalpage&&(a=1));b.store.getProxy().extraParams.hasOwnProperty("page")&&(b.store.getProxy().extraParams.page=a,b.store.currentPage=a);b.store.load(function(c){b.getSelectionModel().deselectAll();b.setCurrPage(a);b.setRefreshTime()})},globalNextPage:function(a){var b=0,c=this;if(-1==a)c.store.getProxy().extraParams.hasOwnProperty("page")&&(c.store.getProxy().extraParams.page=1,c.store.currentPage=1),c.store.load(function(a){c.getSelectionModel().deselectAll();c.setCurrPage(1);c.setRefreshTime();
c.usePopup&&(a=c.getSelectionModel(),null!=a&&a.select(0))});else if(b=c.currpage+1,b>c.totalpage&&(b=1),c.usePopup){var e=c.getSelectionModel();null!=e&&(a=0,null==e.lastSelected?e.select(0):e.lastSelected.index%c.getStore().pageSize==c.getStore().getCount()-1||null==e.getSelection()||0==e.getSelection().length?(c.store.getProxy().extraParams.hasOwnProperty("page")&&(c.store.getProxy().extraParams.page=b,c.store.currentPage=b),c.store.load(function(a){e.deselectAll();c.setCurrPage(b);c.setRefreshTime();
c.getSelectionModel().select(0)})):(a=(e.lastSelected.index+1)%c.getStore().pageSize,c.getSelectionModel().select(a)))}else c.store.getProxy().extraParams.hasOwnProperty("page")&&(c.store.getProxy().extraParams.page=b,c.store.currentPage=b),c.store.load(function(a){c.getSelectionModel().deselectAll();c.setCurrPage(b);c.setRefreshTime()})},nextSelectedRow:function(){var a=this.getSelectionModel();if(null!=a){var b=0;null!=a.lastSelected&&(b=this.getSelectionModel().lastSelected.index%this.getStore().pageSize>=
this.getStore().getCount()-1||null==a.getSelection()||0==a.getSelection().length?0:(this.getSelectionModel().lastSelected.index+1)%this.getStore().pageSize);a.select(b)}},setRefreshTimeTitle:function(a,b){var c=this.dockedItems.get(1).items.get(14);null!=c&&c.setText(e.refresh_gap+"  "+a+"  "+b)},setRefreshTime:function(){var a=this.dockedItems.get(1).items.get(15);null!=a&&a.setText(Ext.Date.format(new Date(Ext.Date.now()),"Y/m/d H:i:s"))},setButtonStatus:function(a){var b=this.dockedItems.get(1).items.get(12);
b.toggle(a);b.btnClick(b,a)},setPopupInfo:function(a){var b=this.dockedItems.get(3);null!=a&&(a.use_popup?(b.setVisible(!0),this.usePopup=a.use_popup,this.popupImgPath=a.popup_dir,this.popup_refresh_gap=a.popup_refresh_gap,null!=a.imgcols&&0<a.imgcols.trim().length&&(this.popupImgCols=a.imgcols.split(";")),null!=a.titlecols&&0<a.titlecols.trim().length&&(this.popupTitleCols=a.titlecols.split(";"))):(b.setVisible(!1),this.usePopup=!1,this.popupImgPath="",this.popupImgCols=[],this.popupTitleCols=[],
this.popup_refresh_gap=600));null!=w&&w.setTimeGap(this.popup_refresh_gap);this.usePopup&&(b.header.items.get(0).toggle(!0),b.header.items.get(0).handler())},getPopupWidth:function(){var a=this.dockedItems.get(3),b=200;null!=a&&(b=a.getWidth());return b},setPopupWidth:function(a){var b=this.dockedItems.get(3);null!=b&&b.setWidth(a)},changeIcon:function(a){var b=this.dockedItems.get(1).items.get(12);(b.pressed=a)?(b.removeCls("starttimerbutton"),b.addCls("stoptimerbutton"),b.setTooltip(e.stop_timer)):
(b.removeCls("stoptimerbutton"),b.addCls("starttimerbutton"),b.setTooltip(e.start_timer))}}),D=Ext.create("DCI.Customer.SubPanel",{id:l.func_id+"Main",renderTo:"indkbPage",autoDestroy:!0,pagetype:"kanban",border:0,bodyPadding:"0 5 5 5",layout:"border",widthChangeControls:[A,k],items:[A,k],plugins:["fittoparent"],globalRunning:!1,beforeClose:function(){null!=t&&t.stopScrollTask();null!=u&&u.stopTask();null!=w&&w.stopTask();removeAllStyle(p)},focusPage:function(){this.globalRunning||(n&&u.executeTask(),
x&&w.executeTask(),null!=Ext.get(this.renderTo)&&this.resize(Ext.get(this.renderTo).getWidth(),Ext.get(this.renderTo).getHeight()),null!=k&&k.setRefreshTimeTitle(u.getDisplayGap(),e.minutes))},leavePage:function(){n&&u.stop();x&&w.stop()},globalTimerEvent:function(a,b){null!=u&&(u.stop(),null!=k&&k.changeIcon(!1));null!=w&&w.stop();null!=k&&(k.setRefreshTimeTitle(b,e.seconds),k.globalNextPage(a));this.globalRunning=!0;return k.currpage},globalTimerStop:function(){this.globalRunning=!1;n&&u.executeTask();
x&&w.executeTask();null!=k&&k.setRefreshTimeTitle(u.getDisplayGap(),e.minutes)},switchToNextTab:function(){var a=!1;if(k.currpage==k.totalpage)if(k.usePopup){var b=k.getSelectionModel();null!=b&&null!=b.lastSelected&&b.lastSelected.index%k.getStore().pageSize>=k.getStore().getCount()-1&&(a=!0)}else a=!0;else a=!1;return a},relationReload:function(a){l.relation_filter=a;this.items.get(1).getStore().gridreload(this.items.get(0),"reload")}}),C=Ext.create("Ext.data.Store",{autoLoad:!1,fields:"cols fields legend marquee refresh display combo lights popup advances relation is_cross".split(" "),
proxy:{type:"ajax",url:"../../CUS/Funcs/EKB/SubKanBan06100137.dsc",actionMethods:{read:"POST"},reader:{type:"json"},extraParams:{DCITag:f,uid:s,action:"init",sql_id:l.func_id}}}),u=E.newTask({timegap:600,displaygap:30,run:function(){null!=k&&k.nextPage()},setTimeGap:function(a){this.timegap=null==a||""==a||1>a?600:a},getTimeGap:function(){return this.timegap},setDisplayGap:function(a){this.displaygap=null==a||""==a||1>a?600:a},getDisplayGap:function(){return this.displaygap},executeTask:function(){this.start(1E3*
this.timegap);n=!0;null!=k&&k.changeIcon(!0)},stopTask:function(){this.stop();n=!1;null!=k&&k.changeIcon(!1)}}),w=E.newTask({timegap:600,run:function(){null!=k&&k.nextSelectedRow()},setTimeGap:function(a){this.timegap=null==a||""==a||1>a?600:a},executeTask:function(){this.start(1E3*this.timegap);x=!0},stopTask:function(){this.stop();x=!1}});C.load(function(a){if(0<a.length){console.log(a[0]);if(null!=z){var b=a[0].get("fields").split(";");z.model.setFields(b);null!=k&&(k.setCrossDBIcon(a[0].get("is_cross")),
k.initBodyGrid(u,a[0].get("cols"),z,a[0].get("relation")),k.setPopupInfo(a[0].get("popup")));null!=t&&(b=a[0].get("marquee"),1==b.use_marquee?("1"==b.marquee_location?t.setDocked("bottom"):t.setDocked("top"),k.doLayout(),t.startMarquee(t,b.marquee_refresh_gap,b.marquee_type)):t.setVisible(!1));null!=u&&(b=a[0].get("refresh"),u.setTimeGap(b.refresh_gap),u.setDisplayGap(b.display_gap),k.setRefreshTimeTitle(b.display_gap,e.minutes),"1"==b.auto_refresh&&u.executeTask(),k.setButtonStatus("1"==b.auto_refresh));
null!=v&&(v.lightsData=a[0].get("lights"));null!=v&&null!=B&&(b=a[0].get("display"),B.setCss(b),v.setComboData(a[0].get("combo")),B.setComboData(a[0].get("combo")),v.setInitData(b),B.setInitData(b,k),k.setPopupWidth(b.popup_width));null!=q&&(q.setComboData(a[0].get("combo")),q.lightsData=a[0].get("lights"),q.setInitData(A,z,q,a[0].get("advances")));z.gridreload(A,q.condiStr)}null!=A&&(b=a[0].get("legend"),null==b||0==b.length?A.setTitle("<table><tr><td><font size='2'>"+l.func_name+"</font></td></tr></table>"):
A.setTitle(a[0].get("legend").replace("$$$kn$$$",l.func_name)))}})}var f="close search save add _delete edit exit errmsg save_format to_edit to_view mode_view mode_edit no_edit_auth expand collapse refersh clear system_error ok cancel toolbar_query_title condi_col save_msg load_def_fail load_def_success load_def_result_title load_def_confirm_title load_def_confirm_msg save_fail save_success save_result_title save_fail sort_column page_size no_query no_sort asc desc refresh_gap minutes favorties_setup start_with end_with bigger bigger_equal smaller smaller_equal equal not_equal like not_like font_size row_height bg_color font_color condi_relation adv_search save_condi load_def_format load_def_condi to_excel to_html start_timer stop_timer seconds cus_format cross_db".split(" ");
this.dcistore.setMultiLangKeys(f);this.dcistore.setUid(globeuid);this.dcistore.load(function(l){if(null!=l&&1==l.length){var r=buildMultiLangObjct(f,l[0].get("langValues")),e=l[0].get("dcitagValue");Ext.EventManager.on(window,"unload",function(){"Microsoft Internet Explorer"==navigator.appName?window.navigate("./../../Login.dsc?action=logout&uid="+globeuid+"&DCITag="+e):Ext.Ajax.request({method:"POST",url:"./../../Login.dsc",params:{DCITag:e,uid:globeuid,action:"logout"}})});Ext.Ajax.request({method:"POST",
url:"./../../EKB/OpenLink/IndKanBan.dsc",params:{DCITag:e,uid:globeuid,action:"getparams",pagekey:pagekey},success:function(f){if(-1!=f.responseText.indexOf("@dcifiltererrtag@$")){if(f=f.responseText.split("$"),2<=f.length){var l=Ext.JSON.decode(f[1]);Ext.Msg.alert(r.errmsg,l.msg,function(){iserror=!0;logout(e,globeuid);window.location=l.result})}}else if(f=Ext.JSON.decode(f.responseText),!0==f.success){Ext.getDoc().dom.title=f.params.func_name;var x={};x.func_id=f.params.func_id;x.func_name=f.params.func_name;
x.conn_id=f.params.conn_id;x.relation_filter=f.params.relation_filter;n(x,e,r,globeuid)}else Ext.Msg.alert(r.errmsg,r.kanban_not_exist)}})}})});
