/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-01-25 07:00:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.FuncViews.Configs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserConfig_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/FuncViews/Configs/./../../dcitag/dcitag.tld", Long.valueOf(1452650348276L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\">\r\n");
      out.write("<title>");
      if (_jspx_meth_dcitag_005freqParam_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" charset=\"UTF-8\">\r\n");
      out.write("\tExt.onReady(function() {\r\n");
      out.write("\t\tvar localKeys = [ \"user_group\", \"user_id\", \"user_name\", \"user_pwd\", \"visible\", \"enable\", \"disable\", \"save_msg\", \"delete_msg\", \"delete_fail\", \"delete_success\",\r\n");
      out.write("\t\t\t\t\"delete_result_title\", \"delete_confirm_title\", \"delete_confirm_msg\", \"delete_fail\", \"save_fail\", \"save_success\", \"save_result_title\", \"save_fail\", \"func_id\",\r\n");
      out.write("\t\t\t\t\"conn_id\", \"can_edit\", \"user_role_edit\", \"toolbar_query_title\", \"system_def_can_not_delete\", \"confirm_title\", \"data_lose_warning\", \"load_def_format\",\r\n");
      out.write("\t\t\t\t\"load_def_fail\", \"load_def_success\", \"load_def_result_title\", \"load_def_confirm_title\", \"load_def_confirm_msg\", \"cus_format\" ];\r\n");
      out.write("\t\tvar keys = localKeys.concat(globeKeys);\r\n");
      out.write("\t\tvar uid = '");
      if (_jspx_meth_dcitag_005freqParam_005f1(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tthis.dcistore.setMultiLangKeys(keys);\r\n");
      out.write("\t\tthis.dcistore.setUid(uid);\r\n");
      out.write("\t\tthis.dcistore.load(function(records) {\r\n");
      out.write("\t\t\tif (records != null && records.length == 1) {\r\n");
      out.write("\t\t\t\tvar langs = buildMultiLangObjct(keys, records[0].get('langValues'));\r\n");
      out.write("\t\t\t\tshowPage(records[0].get('dcitagValue'), langs, '");
      if (_jspx_meth_dcitag_005freqParam_005f2(_jspx_page_context))
        return;
      out.write("', uid);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction showPage(postvalue, langs, recvAuth, uid) {\r\n");
      out.write("\t\tvar canEdit = recvAuth == \"1\";\r\n");
      out.write("\t\tvar group_combo = Ext.create('DCI.Customer.ComboBox', {\r\n");
      out.write("\t\t\tfieldLabel : langs.user_group,\r\n");
      out.write("\t\t\tname : 'group_id',\r\n");
      out.write("\t\t\tx : 500,\r\n");
      out.write("\t\t\ty : 10\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar visible_combo = Ext.create('DCI.Customer.ComboBox', {\r\n");
      out.write("\t\t\tfieldLabel : langs.visible,\r\n");
      out.write("\t\t\tname : 'visible',\r\n");
      out.write("\t\t\tstore : {\r\n");
      out.write("\t\t\t\tfields : [ 'label', 'value' ],\r\n");
      out.write("\t\t\t\tdata : [ {\r\n");
      out.write("\t\t\t\t\t\"label\" : langs.enable,\r\n");
      out.write("\t\t\t\t\t\"value\" : '1'\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\"label\" : langs.disable,\r\n");
      out.write("\t\t\t\t\t\"value\" : '0'\r\n");
      out.write("\t\t\t\t} ]\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdefaultvalue : '1',\r\n");
      out.write("\t\t\tx : 250,\r\n");
      out.write("\t\t\ty : 50\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar headform = Ext.create('DCI.Customer.HeadFormPanel', {\r\n");
      out.write("\t\t\theight : 100,\r\n");
      out.write("\t\t\turl : '../../Configs/UserConfig.dsc',\r\n");
      out.write("\t\t\tlanguageObj : langs,\r\n");
      out.write("\t\t\titems : [ Ext.create('DCI.Customer.TextField', {\r\n");
      out.write("\t\t\t\tfieldLabel : langs.user_id,\r\n");
      out.write("\t\t\t\temptyText : '',\r\n");
      out.write("\t\t\t\tname : 'user_id',\r\n");
      out.write("\t\t\t\tallowBlank : false,\r\n");
      out.write("\t\t\t\tispk : true,\r\n");
      out.write("\t\t\t\tx : 0,\r\n");
      out.write("\t\t\t\ty : 10\r\n");
      out.write("\t\t\t}), Ext.create('DCI.Customer.TextField', {\r\n");
      out.write("\t\t\t\tfieldLabel : langs.user_name,\r\n");
      out.write("\t\t\t\temptyText : '',\r\n");
      out.write("\t\t\t\tname : 'user_name',\r\n");
      out.write("\t\t\t\tallowBlank : true,\r\n");
      out.write("\t\t\t\tx : 250,\r\n");
      out.write("\t\t\t\ty : 10\r\n");
      out.write("\t\t\t}), Ext.create('DCI.Customer.TextField', {\r\n");
      out.write("\t\t\t\tfieldLabel : langs.user_pwd,\r\n");
      out.write("\t\t\t\temptyText : '',\r\n");
      out.write("\t\t\t\tname : 'user_pwd',\r\n");
      out.write("\t\t\t\tallowBlank : false,\r\n");
      out.write("\t\t\t\tinputType : 'password',\r\n");
      out.write("\t\t\t\tx : 0,\r\n");
      out.write("\t\t\t\ty : 50\r\n");
      out.write("\t\t\t}), group_combo, visible_combo ],\r\n");
      out.write("\t\t\tshowQueryWindow : function() {\r\n");
      out.write("\t\t\t\tvar me = this;\r\n");
      out.write("\t\t\t\tme.initQueryWindow();\r\n");
      out.write("\t\t\t\tvar pageSize = 10;\r\n");
      out.write("\t\t\t\tvar initStore = Ext.create('Ext.data.Store', {\r\n");
      out.write("\t\t\t\t\tautoLoad : false,\r\n");
      out.write("\t\t\t\t\tfields : [ 'cols' ],\r\n");
      out.write("\t\t\t\t\tproxy : {\r\n");
      out.write("\t\t\t\t\t\ttype : 'ajax',\r\n");
      out.write("\t\t\t\t\t\turl : '../../Configs/UserConfig.dsc',\r\n");
      out.write("\t\t\t\t\t\tactionMethods : {\r\n");
      out.write("\t\t\t\t\t\t\tread : 'POST'\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\treader : {\r\n");
      out.write("\t\t\t\t\t\t\ttype : 'json'\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\textraParams : {\r\n");
      out.write("\t\t\t\t\t\t\tDCITag : postvalue,\r\n");
      out.write("\t\t\t\t\t\t\tuid : uid\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar gstore = Ext.create('Ext.data.Store', {\r\n");
      out.write("\t\t\t\t\tautoLoad : false,\r\n");
      out.write("\t\t\t\t\tfields : [ 'user_id', 'user_name', 'user_pwd', 'group_id', 'visible' ],\r\n");
      out.write("\t\t\t\t\tproxy : {\r\n");
      out.write("\t\t\t\t\t\ttype : 'ajax',\r\n");
      out.write("\t\t\t\t\t\turl : '../../Configs/UserConfig.dsc',\r\n");
      out.write("\t\t\t\t\t\tactionMethods : {\r\n");
      out.write("\t\t\t\t\t\t\tread : 'POST'\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\treader : {\r\n");
      out.write("\t\t\t\t\t\t\troot : 'items',\r\n");
      out.write("\t\t\t\t\t\t\ttotalProperty : 'total'\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\textraParams : {\r\n");
      out.write("\t\t\t\t\t\t\tDCITag : postvalue,\r\n");
      out.write("\t\t\t\t\t\t\tuid : uid,\r\n");
      out.write("\t\t\t\t\t\t\taction : 'search',\r\n");
      out.write("\t\t\t\t\t\t\tpage : 1,\r\n");
      out.write("\t\t\t\t\t\t\tpagesize : pageSize,\r\n");
      out.write("\t\t\t\t\t\t\tfilter : ''\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tpageSize : pageSize\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar gridColumns = [ {\r\n");
      out.write("\t\t\t\t\ttext : langs.user_id,\r\n");
      out.write("\t\t\t\t\tdataIndex : 'user_id',\r\n");
      out.write("\t\t\t\t\twidth : 200\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\ttext : langs.user_name,\r\n");
      out.write("\t\t\t\t\tdataIndex : 'user_name',\r\n");
      out.write("\t\t\t\t\twidth : 200\r\n");
      out.write("\t\t\t\t} ];\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar openwin = Ext.create('DCI.Customer.QueryWindow', {\r\n");
      out.write("\t\t\t\t\theight : 335,\r\n");
      out.write("\t\t\t\t\twidth : 450,\r\n");
      out.write("\t\t\t\t\theadform : me,\r\n");
      out.write("\t\t\t\t\ttitle : langs.toolbar_query_title,\r\n");
      out.write("\t\t\t\t\tloadHeadData : function(record) {\r\n");
      out.write("\t\t\t\t\t\tthis.headform.loadRecord(record);\r\n");
      out.write("\t\t\t\t\t\tthis.headform.setDataLoaded(true);\r\n");
      out.write("\t\t\t\t\t\tif (bodyStore != null) {\r\n");
      out.write("\t\t\t\t\t\t\tif (bodyStore.getProxy().extraParams.hasOwnProperty('keys')) {\r\n");
      out.write("\t\t\t\t\t\t\t\tbodyStore.getProxy().extraParams['keys'] = record.get(\"user_id\");\r\n");
      out.write("\t\t\t\t\t\t\t\tbodyStore.load();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif (bodypanel != null) {\r\n");
      out.write("\t\t\t\t\t\t\tvar obj = new Object();\r\n");
      out.write("\t\t\t\t\t\t\tobj[\"user_id\"] = record.get(\"user_id\");\r\n");
      out.write("\t\t\t\t\t\t\tbodypanel.headKeys = obj;\r\n");
      out.write("\t\t\t\t\t\t\tbodypanel.dataloaded(this.headform.dataloaded);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tthis.close();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tinitStore.load(function(records) {\r\n");
      out.write("\t\t\t\t\topenwin.setInitObjects(records, gstore, gridColumns);\r\n");
      out.write("\t\t\t\t\tme.searchWin = openwin;\r\n");
      out.write("\t\t\t\t\tme.searchStore = gstore;\r\n");
      out.write("\t\t\t\t\topenwin.show();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar headpanel = Ext.create('DCI.Customer.HeadPanel', {\r\n");
      out.write("\t\t\theight : 200,\r\n");
      out.write("\t\t\twidth : '100%',\r\n");
      out.write("\t\t\theadform : headform,\r\n");
      out.write("\t\t\tpostvalue : postvalue,\r\n");
      out.write("\t\t\tuid : uid,\r\n");
      out.write("\t\t\tcanEdit : canEdit,\r\n");
      out.write("\t\t\tkeepAdd : false,\r\n");
      out.write("\t\t\texceptionDeleteAuth : function() {\r\n");
      out.write("\t\t\t\tvar result = [ \"1\", \"\" ];\r\n");
      out.write("\t\t\t\tvar form = this.bindform;\r\n");
      out.write("\t\t\t\tif (headform != null) {\r\n");
      out.write("\t\t\t\t\tif (form.items.get(0).getValue() == \"DS\") {\r\n");
      out.write("\t\t\t\t\t\tresult = [ \"0\", langs.system_def_can_not_delete ];\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn result;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar bodypanel = Ext.create('DCI.Customer.BodyGridPanel', {\r\n");
      out.write("\t\t\ttitle : langs.user_role_edit,\r\n");
      out.write("\t\t\tlanguageObj : langs,\r\n");
      out.write("\t\t\tgridid : 'UserConfig_G01',\r\n");
      out.write("\t\t\tactionurl : '../../Configs/UserConfig.dsc',\r\n");
      out.write("\t\t\tpostvalue : postvalue,\r\n");
      out.write("\t\t\theadform : headform,\r\n");
      out.write("\t\t\tuid : uid,\r\n");
      out.write("\t\t\tkeyfields : [ 'conn_id', 'role_id', 'func_id' ],\r\n");
      out.write("\t\t\tcanEdit : canEdit,\r\n");
      out.write("\t\t\ttransSource : [],\r\n");
      out.write("\t\t\ttransSource2 : [],\r\n");
      out.write("\t\t\ttransType : function(value) {\r\n");
      out.write("\t\t\t\tfor ( var i = 0; i < this.transSource.length; i++) {\r\n");
      out.write("\t\t\t\t\tif (this.transSource[i].value == value) {\r\n");
      out.write("\t\t\t\t\t\tvalue = this.transSource[i].label;\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn value;\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttransType2 : function(value) {\r\n");
      out.write("\t\t\t\tfor ( var i = 0; i < this.transSource2.length; i++) {\r\n");
      out.write("\t\t\t\t\tif (this.transSource2[i].value == value) {\r\n");
      out.write("\t\t\t\t\t\tvalue = this.transSource2[i].label;\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn value;\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\taddNewRow : function() {\r\n");
      out.write("\t\t\t\tvar grid = this.items.get(1);\r\n");
      out.write("\t\t\t\tvar gridStore = grid.getStore();\r\n");
      out.write("\t\t\t\tif (gridStore != null) {\r\n");
      out.write("\t\t\t\t\tgridStore.add({\r\n");
      out.write("\t\t\t\t\t\tconn_id : '',\r\n");
      out.write("\t\t\t\t\t\tuser_id : this.headKeys.user_id,\r\n");
      out.write("\t\t\t\t\t\tfunc_id : '',\r\n");
      out.write("\t\t\t\t\t\tcan_edit : false,\r\n");
      out.write("\t\t\t\t\t\tmoditag : 1,\r\n");
      out.write("\t\t\t\t\t\tmoditp : 'add'\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tgrid.getView().select(gridStore.getCount() - 1);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsetNewCondi : function() {\r\n");
      out.write("\t\t\t\tvar me = this;\r\n");
      out.write("\t\t\t\tvar grid = me.getGrid();\r\n");
      out.write("\t\t\t\tvar store = grid.getStore();\r\n");
      out.write("\t\t\t\tvar head = me.headform;\r\n");
      out.write("\t\t\t\tif (store != null) {\r\n");
      out.write("\t\t\t\t\tif (store.getProxy().extraParams.hasOwnProperty('keys')) {\r\n");
      out.write("\t\t\t\t\t\tstore.getProxy().extraParams['keys'] = head.items.get(0).getValue();\r\n");
      out.write("\t\t\t\t\t\tvar obj = new Object();\r\n");
      out.write("\t\t\t\t\t\tobj[\"user_id\"] = head.items.get(0).getValue();\r\n");
      out.write("\t\t\t\t\t\tme.headKeys = obj;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar conn_Combo = Ext.create('DCI.Customer.ComboBox', {\r\n");
      out.write("\t\t\tlabelWidth : 0\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar func_Combo = Ext.create('DCI.Customer.ComboBox', {\r\n");
      out.write("\t\t\tlabelWidth : 0,\r\n");
      out.write("\t\t\tstore : {\r\n");
      out.write("\t\t\t\tfields : [ 'label', 'value', 'package' ],\r\n");
      out.write("\t\t\t\tautoLoad : false,\r\n");
      out.write("\t\t\t\tproxy : {\r\n");
      out.write("\t\t\t\t\ttype : 'memory',\r\n");
      out.write("\t\t\t\t\treader : {\r\n");
      out.write("\t\t\t\t\t\ttype : 'json'\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tlisteners : {\r\n");
      out.write("\t\t\t\tchange : function(comp, newValue, oldValue, eOpts) {\r\n");
      out.write("\t\t\t\t\tvar me = this;\r\n");
      out.write("\t\t\t\t\tvar store = me.getStore();\r\n");
      out.write("\t\t\t\t\tvar gridStore = me.up().up().getStore();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfor ( var i = 0; i < store.getCount(); i++) {\r\n");
      out.write("\t\t\t\t\t\tif (store.getAt(i).get(\"value\") == newValue) {\r\n");
      out.write("\t\t\t\t\t\t\tif (gridStore != null) {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar ridx = gridStore.getCount() - 1;\r\n");
      out.write("\t\t\t\t\t\t\t\tif (ridx < 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tridx = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tif (store.getAt(i).get(\"package\") == \"EKB\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgridStore.getAt(ridx).set(\"can_edit\", false);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tgridStore.getAt(ridx).set(\"func_package\", store.getAt(i).get(\"package\"));\r\n");
      out.write("\t\t\t\t\t\t\t\tgridStore.getAt(ridx).commit();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tresize : function(combo, width, height, oldWidth, oldHeight, eOpts) {\r\n");
      out.write("\t\t\t\t\tcombo.listConfig = {\r\n");
      out.write("\t\t\t\t\t\tminWidth : width - combo.labelWidth\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar bodyColumns = [ {\r\n");
      out.write("\t\t\txtype : 'rownumberer',\r\n");
      out.write("\t\t\tcolid : 'colrownum',\r\n");
      out.write("\t\t\twidth : 40,\r\n");
      out.write("\t\t\tsortable : false,\r\n");
      out.write("\t\t\tlocked : true\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\ttext : langs.conn_id,\r\n");
      out.write("\t\t\tdataIndex : 'conn_id',\r\n");
      out.write("\t\t\tcolid : 'colconn_id',\r\n");
      out.write("\t\t\twidth : 200,\r\n");
      out.write("\t\t\trenderer : function(value) {\r\n");
      out.write("\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\tvalue = this.up().transType(value);\r\n");
      out.write("\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\tif (window.console) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(e.message);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn value;\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tlisteners : {\r\n");
      out.write("\t\t\t\trender : function(comp, eOpts) {\r\n");
      out.write("\t\t\t\t\tvar e = Ext.create('DCI.Customer.ComboBox', {\r\n");
      out.write("\t\t\t\t\t\tlabelWidth : 0\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\te.getStore().loadData(this.up('panel').up('panel').transSource);\r\n");
      out.write("\t\t\t\t\tthis.setEditor(e);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\ttext : langs.func_id,\r\n");
      out.write("\t\t\tdataIndex : 'func_id',\r\n");
      out.write("\t\t\tcolid : 'colfunc_id',\r\n");
      out.write("\t\t\twidth : 200,\r\n");
      out.write("\t\t\t//editor : func_Combo,\r\n");
      out.write("\t\t\trenderer : function(value) {\r\n");
      out.write("\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\tvalue = this.up().transType2(value);\r\n");
      out.write("\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\tif (window.console) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(e.message);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn value;\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tlisteners : {\r\n");
      out.write("\t\t\t\trender : function(comp, eOpts) {\r\n");
      out.write("\t\t\t\t\tvar e = Ext.create('DCI.Customer.ComboBox', {\r\n");
      out.write("\t\t\t\t\t\tlabelWidth : 0,\r\n");
      out.write("\t\t\t\t\t\tstore : {\r\n");
      out.write("\t\t\t\t\t\t\tfields : [ 'label', 'value', 'package' ],\r\n");
      out.write("\t\t\t\t\t\t\tautoLoad : false,\r\n");
      out.write("\t\t\t\t\t\t\tproxy : {\r\n");
      out.write("\t\t\t\t\t\t\t\ttype : 'memory',\r\n");
      out.write("\t\t\t\t\t\t\t\treader : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype : 'json'\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tlisteners : {\r\n");
      out.write("\t\t\t\t\t\t\tchange : function(comp, newValue, oldValue, eOpts) {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar me = this;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar store = me.getStore();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar gridStore = me.up().up().getStore();\r\n");
      out.write("\t\t\t\t\t\t\t\tfor ( var i = 0; i < store.getCount(); i++) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (store.getAt(i).get(\"value\") == newValue) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif (gridStore != null) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar ridx = gridStore.getCount() - 1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif (ridx < 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tridx = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif (store.getAt(i).get(\"package\") == \"EKB\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tgridStore.getAt(ridx).set(\"can_edit\", false);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tgridStore.getAt(ridx).set(\"func_package\", store.getAt(i).get(\"package\"));\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tgridStore.getAt(ridx).commit();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tresize : function(combo, width, height, oldWidth, oldHeight, eOpts) {\r\n");
      out.write("\t\t\t\t\t\t\t\tcombo.listConfig = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tminWidth : width - combo.labelWidth\r\n");
      out.write("\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\te.getStore().loadData(this.up('panel').up('panel').transSource2);\r\n");
      out.write("\t\t\t\t\tthis.setEditor(e);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\txtype : 'dcicheckcolumn',\r\n");
      out.write("\t\t\ttext : langs.can_edit,\r\n");
      out.write("\t\t\tdataIndex : 'can_edit',\r\n");
      out.write("\t\t\tcolid : 'colcan_edit',\r\n");
      out.write("\t\t\tcanEditControl : function(col, rowIndex) {\r\n");
      out.write("\t\t\t\tvar me = this;\r\n");
      out.write("\t\t\t\tvar gridStore = me.up().up().getStore();\r\n");
      out.write("\t\t\t\tif (gridStore == null) {\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\treturn gridStore.getAt(rowIndex).get(\"func_package\") != \"EKB\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} /* , Ext.create('DCI.Customer.CheckColumn', {\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttext : langs.can_edit,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdataIndex : 'can_edit',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcolid : 'colcan_edit'\r\n");
      out.write("\t\t\t\t\t\t\t\t}) */];\r\n");
      out.write("\r\n");
      out.write("\t\tvar bodyStore = Ext.create('Ext.data.Store', {\r\n");
      out.write("\t\t\tautoLoad : false,\r\n");
      out.write("\t\t\tfields : [ 'user_id', 'func_id', 'conn_id', 'func_package', 'can_edit', 'moditag', 'moditp' ],\r\n");
      out.write("\t\t\tproxy : {\r\n");
      out.write("\t\t\t\ttype : 'ajax',\r\n");
      out.write("\t\t\t\turl : '../../Configs/UserConfig.dsc',\r\n");
      out.write("\t\t\t\tactionMethods : {\r\n");
      out.write("\t\t\t\t\tread : 'POST'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\treader : {\r\n");
      out.write("\t\t\t\t\troot : 'items'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\textraParams : {\r\n");
      out.write("\t\t\t\t\tDCITag : postvalue,\r\n");
      out.write("\t\t\t\t\tuid : uid,\r\n");
      out.write("\t\t\t\t\taction : 'bodyData',\r\n");
      out.write("\t\t\t\t\tkeys : ''\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//bodypanel.initBody(bodyStore, bodyColumns);\r\n");
      out.write("\r\n");
      out.write("\t\tvar main = Ext.create('DCI.Customer.SubPanel', {\r\n");
      out.write("\t\t\tid : 'UserConfigMain',\r\n");
      out.write("\t\t\trenderTo : 'UserConfigPage',\r\n");
      out.write("\t\t\tborder : 0,\r\n");
      out.write("\t\t\tbodyPadding : '0 5 5 5',\r\n");
      out.write("\t\t\tlayout : 'border',\r\n");
      out.write("\t\t\twidthChangeControls : [ headpanel, bodypanel ],\r\n");
      out.write("\t\t\titems : [ headpanel, bodypanel ]\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar initQueryStore = Ext.create('Ext.data.Store', {\r\n");
      out.write("\t\t\tautoLoad : false,\r\n");
      out.write("\t\t\tfields : [ 'groups', 'conns', 'funcs' ],\r\n");
      out.write("\t\t\tproxy : {\r\n");
      out.write("\t\t\t\ttype : 'ajax',\r\n");
      out.write("\t\t\t\turl : '../../Configs/UserConfig.dsc',\r\n");
      out.write("\t\t\t\tactionMethods : {\r\n");
      out.write("\t\t\t\t\tread : 'POST'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\treader : {\r\n");
      out.write("\t\t\t\t\ttype : 'json'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\textraParams : {\r\n");
      out.write("\t\t\t\t\tDCITag : postvalue,\r\n");
      out.write("\t\t\t\t\tuid : uid,\r\n");
      out.write("\t\t\t\t\taction : 'init'\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tinitQueryStore.load(function(record) {\r\n");
      out.write("\t\t\tif (record.length > 0) {\r\n");
      out.write("\t\t\t\tgroup_combo.getStore().loadData(record[0].get(\"groups\"));\r\n");
      out.write("\t\t\t\tgroup_combo.loadDefault();\r\n");
      out.write("\t\t\t\tvisible_combo.loadDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tgroup_combo.listConfig = {\r\n");
      out.write("\t\t\t\t\tminWidth : group_combo.getWidth() - group_combo.getLabelWidth()\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tvisible_combo.listConfig = {\r\n");
      out.write("\t\t\t\t\tminWidth : visible_combo.getWidth() - visible_combo.getLabelWidth()\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tconn_Combo.getStore().loadData(record[0].get(\"conns\"));\r\n");
      out.write("\t\t\t\tfunc_Combo.getStore().loadData(record[0].get(\"funcs\"));\r\n");
      out.write("\t\t\t\tbodypanel.transSource = record[0].get(\"conns\");\r\n");
      out.write("\t\t\t\tbodypanel.transSource2 = record[0].get(\"funcs\");\r\n");
      out.write("\t\t\t\tbodypanel.initBody(bodyStore, bodyColumns);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tmain.resize(Ext.get(\"UserConfigPage\").getWidth(), Ext.get(\"UserConfigPage\").getHeight());\r\n");
      out.write("\t}\r\n");
      out.write("\t//class=\"page_div\" #eaf1fb\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"UserConfigPage\" class=\"page_div\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_dcitag_005freqParam_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dcitag:reqParam
    com.dci.jweb.DCITags.Request.getReqParameter _jspx_th_dcitag_005freqParam_005f0 = (new com.dci.jweb.DCITags.Request.getReqParameter());
    _jsp_instancemanager.newInstance(_jspx_th_dcitag_005freqParam_005f0);
    _jspx_th_dcitag_005freqParam_005f0.setJspContext(_jspx_page_context);
    // /FuncViews/Configs/UserConfig.jsp(8,7) name = paramName type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_dcitag_005freqParam_005f0.setParamName("func_name");
    _jspx_th_dcitag_005freqParam_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_dcitag_005freqParam_005f0);
    return false;
  }

  private boolean _jspx_meth_dcitag_005freqParam_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dcitag:reqParam
    com.dci.jweb.DCITags.Request.getReqParameter _jspx_th_dcitag_005freqParam_005f1 = (new com.dci.jweb.DCITags.Request.getReqParameter());
    _jsp_instancemanager.newInstance(_jspx_th_dcitag_005freqParam_005f1);
    _jspx_th_dcitag_005freqParam_005f1.setJspContext(_jspx_page_context);
    // /FuncViews/Configs/UserConfig.jsp(17,13) name = paramName type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_dcitag_005freqParam_005f1.setParamName("uid");
    _jspx_th_dcitag_005freqParam_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_dcitag_005freqParam_005f1);
    return false;
  }

  private boolean _jspx_meth_dcitag_005freqParam_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dcitag:reqParam
    com.dci.jweb.DCITags.Request.getReqParameter _jspx_th_dcitag_005freqParam_005f2 = (new com.dci.jweb.DCITags.Request.getReqParameter());
    _jsp_instancemanager.newInstance(_jspx_th_dcitag_005freqParam_005f2);
    _jspx_th_dcitag_005freqParam_005f2.setJspContext(_jspx_page_context);
    // /FuncViews/Configs/UserConfig.jsp(23,52) name = paramName type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_dcitag_005freqParam_005f2.setParamName("canEdit");
    _jspx_th_dcitag_005freqParam_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_dcitag_005freqParam_005f2);
    return false;
  }
}
